package generate

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"

	"github.com/mtgo-labs/raw/cmd/tlgen/internal/naming"
	"github.com/mtgo-labs/raw/cmd/tlgen/internal/schema"
	"github.com/mtgo-labs/raw/cmd/tlgen/internal/types"
)

const generatorVersion = "tlgen/v1"

// Metadata identifies the exact schema baseline used for generated output.
type Metadata struct {
	Commit string
	Layer  int
}

// Output is one formatted generated Go file.
type Output struct {
	Path string
	Data []byte
}

// Render emits every planned file as formatted Go source.
func Render(
	plan *Plan,
	api, mtp *schema.Schema,
	metadata Metadata,
) ([]Output, error) {
	if plan == nil || api == nil || mtp == nil {
		return nil, fmt.Errorf("nil plan or schema")
	}
	if len(metadata.Commit) != 40 {
		return nil, fmt.Errorf("invalid upstream commit %q", metadata.Commit)
	}
	if _, err := hex.DecodeString(metadata.Commit); err != nil {
		return nil, fmt.Errorf("invalid upstream commit %q", metadata.Commit)
	}
	if metadata.Layer != api.Layer {
		return nil, fmt.Errorf(
			"metadata layer %d does not match API layer %d",
			metadata.Layer,
			api.Layer,
		)
	}

	apiTypes, err := types.NewResolver(api, naming.API)
	if err != nil {
		return nil, fmt.Errorf("build API type resolver: %w", err)
	}
	mtpTypes, err := types.NewResolver(mtp, naming.MTP)
	if err != nil {
		return nil, fmt.Errorf("build MTProto type resolver: %w", err)
	}
	apiSizes := newAllocationSizer(api, apiTypes)
	mtpSizes := newAllocationSizer(mtp, mtpTypes)
	for index := range api.Entries {
		if api.Entries[index].Kind == schema.KindClass {
			if _, err := apiSizes.entry(&api.Entries[index]); err != nil {
				return nil, fmt.Errorf("size API constructor: %w", err)
			}
		}
	}
	for index := range mtp.Entries {
		if mtp.Entries[index].Kind == schema.KindClass {
			if _, err := mtpSizes.entry(&mtp.Entries[index]); err != nil {
				return nil, fmt.Errorf("size MTProto constructor: %w", err)
			}
		}
	}

	outputs := make([]Output, 0, len(plan.Files)+1)
	for _, planned := range plan.Files {
		resolver := apiTypes
		sizer := apiSizes
		if planned.Flavor == naming.MTP {
			resolver = mtpTypes
			sizer = mtpSizes
		}
		data, err := renderFile(
			planned,
			resolver,
			sizer,
			metadata,
			api,
			mtp,
		)
		if err != nil {
			return nil, fmt.Errorf("render %q: %w", planned.Path, err)
		}
		outputs = append(outputs, Output{Path: planned.Path, Data: data})
	}
	dispatchBenchmark, err := renderDispatchBenchmark(
		api,
		mtp,
		apiSizes,
		mtpSizes,
		metadata,
	)
	if err != nil {
		return nil, err
	}
	outputs = append(outputs, Output{
		Path: "tl/api_dispatch_test.go",
		Data: dispatchBenchmark,
	})
	return outputs, nil
}

func renderFile(
	planned *File,
	resolver *types.Resolver,
	sizer *allocationSizer,
	metadata Metadata,
	api, mtp *schema.Schema,
) ([]byte, error) {
	fset := token.NewFileSet()
	file := &ast.File{Name: ast.NewIdent("tl")}
	coreAnchor := planned.Flavor == naming.API &&
		planned.Namespace == "" && planned.Bucket == ""
	if coreAnchor {
		file.Decls = append(file.Decls, layerDecl(metadata.Layer))
	}
	for _, union := range planned.Unions {
		declaration, err := unionDecl(union, planned.Flavor)
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, declaration)
		decoder, err := unionDecoderDecl(union, planned.Flavor, fset)
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, decoder)
	}
	for _, entry := range planned.Entries {
		declarations, err := entryDecls(
			entry,
			planned.Flavor,
			resolver,
			sizer,
			fset,
		)
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, declarations...)
	}
	if coreAnchor {
		decoder, err := objectDecoderDecl(api, mtp, fset)
		if err != nil {
			return nil, err
		}
		file.Decls = append(file.Decls, decoder)
	}

	var body bytes.Buffer
	if err := format.Node(&body, fset, file); err != nil {
		return nil, fmt.Errorf("format AST: %w", err)
	}
	source := append(header(planned.Flavor, metadata), body.Bytes()...)
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format source: %w", err)
	}
	return separateTopLevelFunctions(formatted), nil
}

func separateTopLevelFunctions(source []byte) []byte {
	return bytes.ReplaceAll(source, []byte("}\nfunc "), []byte("}\n\nfunc "))
}

func header(flavor naming.Flavor, metadata Metadata) []byte {
	source := "schema/api-schema.json"
	if flavor == naming.MTP {
		source = "schema/mtp-schema.json"
	}
	return fmt.Appendf(
		nil,
		"// Code generated by cmd/tlgen (%s); DO NOT EDIT.\n"+
			"//\n"+
			"// Source: %s\n"+
			"// Telegram API layer: %d\n\n",
		generatorVersion,
		source,
		metadata.Layer,
	)
}

func layerDecl(layer int) ast.Decl {
	return &ast.GenDecl{
		Doc: comment("Layer is the generated Telegram API schema layer."),
		Tok: token.CONST,
		Specs: []ast.Spec{
			&ast.ValueSpec{
				Names:  []*ast.Ident{ast.NewIdent("Layer")},
				Values: []ast.Expr{integerLiteral(layer)},
			},
		},
	}
}

func unionDecl(union *schema.Union, flavor naming.Flavor) (ast.Decl, error) {
	goName, err := naming.Union(union.Name, flavor)
	if err != nil {
		return nil, err
	}
	methods := &ast.FieldList{
		List: []*ast.Field{
			{Type: ast.NewIdent("Object")},
			{
				Names: []*ast.Ident{ast.NewIdent(unionMarker(goName))},
				Type:  emptyFuncType(),
			},
		},
	}
	return &ast.GenDecl{
		Doc: comment(fmt.Sprintf(
			"%s is the TL union %s.",
			goName,
			union.Name,
		)),
		Tok: token.TYPE,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name: ast.NewIdent(goName),
				Type: &ast.InterfaceType{Methods: methods},
			},
		},
	}, nil
}

func entryDecls(
	entry *schema.Entry,
	flavor naming.Flavor,
	resolver *types.Resolver,
	sizer *allocationSizer,
	fset *token.FileSet,
) ([]ast.Decl, error) {
	goName, err := naming.Entry(entry, flavor)
	if err != nil {
		return nil, err
	}
	fields, err := structFields(entry, resolver)
	if err != nil {
		return nil, err
	}
	typeParameters := genericParameters(entry)
	typeDecl := &ast.GenDecl{
		Doc: comment(fmt.Sprintf(
			"%s represents TL %s %s (ID %#08x).",
			goName,
			entry.Kind,
			entry.Name,
			entry.ID,
		)),
		Tok: token.TYPE,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name:       ast.NewIdent(goName),
				TypeParams: typeParameters,
				Type:       &ast.StructType{Fields: fields},
			},
		},
	}

	constName := goName + "ConstructorID"
	constDecl := &ast.GenDecl{
		Doc: comment(fmt.Sprintf(
			"%s is the TL constructor ID for %s.",
			constName,
			entry.Name,
		)),
		Tok: token.CONST,
		Specs: []ast.Spec{
			&ast.ValueSpec{
				Names:  []*ast.Ident{ast.NewIdent(constName)},
				Type:   ast.NewIdent("uint32"),
				Values: []ast.Expr{hexLiteral(entry.ID)},
			},
		},
	}

	receiver := receiverType(goName, entry.Generics)
	declarations := []ast.Decl{
		typeDecl,
		constDecl,
		constructorIDMethod(receiver, constName),
	}
	if entry.Kind == schema.KindClass {
		unionName, err := naming.Union(entry.Type, flavor)
		if err != nil {
			return nil, err
		}
		declarations = append(
			declarations,
			markerMethod(receiver, unionMarker(unionName)),
		)
	} else {
		result, err := resolver.Result(entry)
		if err != nil {
			return nil, err
		}
		resultSyntax, err := result.GoType()
		if err != nil {
			return nil, err
		}
		resultType, err := parser.ParseExpr(resultSyntax)
		if err != nil {
			return nil, fmt.Errorf("parse result type %q: %w", resultSyntax, err)
		}
		declarations = append(
			declarations,
			requestResultMethod(receiver, resultType),
		)
	}
	encoding, err := encodingDecls(entry, flavor, resolver, fset)
	if err != nil {
		return nil, err
	}
	declarations = append(declarations, encoding...)
	decoding, err := decodingDecls(entry, flavor, resolver, sizer, fset)
	if err != nil {
		return nil, err
	}
	declarations = append(declarations, decoding...)
	return declarations, nil
}

func structFields(
	entry *schema.Entry,
	resolver *types.Resolver,
) (*ast.FieldList, error) {
	fields := make([]*ast.Field, 0, len(entry.Arguments))
	for index := range entry.Arguments {
		argument := &entry.Arguments[index]
		if argument.Type == "#" {
			continue
		}
		fieldName, err := naming.Field(argument.Name)
		if err != nil {
			return nil, err
		}
		resolved, err := resolver.Argument(entry, argument)
		if err != nil {
			return nil, err
		}
		typeSyntax, err := resolved.GoType()
		if err != nil {
			return nil, err
		}
		fieldType, err := parser.ParseExpr(typeSyntax)
		if err != nil {
			return nil, fmt.Errorf("parse field type %q: %w", typeSyntax, err)
		}
		field := &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(fieldName)},
			Type:  fieldType,
		}
		fields = append(fields, field)
	}
	return &ast.FieldList{List: fields}, nil
}

func genericParameters(entry *schema.Entry) *ast.FieldList {
	if len(entry.Generics) == 0 {
		return nil
	}
	fields := make([]*ast.Field, len(entry.Generics))
	for index, generic := range entry.Generics {
		fields[index] = &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(generic.Name)},
			Type:  ast.NewIdent("any"),
		}
	}
	return &ast.FieldList{List: fields}
}

func receiverType(goName string, generics []schema.Generic) ast.Expr {
	var receiver ast.Expr = ast.NewIdent(goName)
	for _, generic := range generics {
		receiver = &ast.IndexExpr{
			X:     receiver,
			Index: ast.NewIdent(generic.Name),
		}
	}
	return &ast.StarExpr{X: receiver}
}

func constructorIDMethod(receiver ast.Expr, constName string) ast.Decl {
	return &ast.FuncDecl{
		Doc:  comment("ConstructorID returns the TL constructor ID."),
		Name: ast.NewIdent("ConstructorID"),
		Recv: unnamedFields(receiver),
		Type: &ast.FuncType{
			Params: unnamedFields(),
			Results: unnamedFields(
				ast.NewIdent("uint32"),
			),
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{ast.NewIdent(constName)},
				},
			},
		},
	}
}

func markerMethod(receiver ast.Expr, name string) ast.Decl {
	return &ast.FuncDecl{
		Name: ast.NewIdent(name),
		Recv: unnamedFields(receiver),
		Type: emptyFuncType(),
		Body: &ast.BlockStmt{},
	}
}

func requestResultMethod(receiver, result ast.Expr) ast.Decl {
	return &ast.FuncDecl{
		Name: ast.NewIdent("requestResult"),
		Recv: unnamedFields(receiver),
		Type: &ast.FuncType{
			Params: unnamedFields(result),
		},
		Body: &ast.BlockStmt{},
	}
}

func emptyFuncType() *ast.FuncType {
	return &ast.FuncType{Params: unnamedFields()}
}

func unnamedFields(values ...ast.Expr) *ast.FieldList {
	fields := make([]*ast.Field, len(values))
	for index, value := range values {
		fields[index] = &ast.Field{Type: value}
	}
	return &ast.FieldList{List: fields}
}

func unionMarker(goName string) string {
	return "is" + goName
}

func integerLiteral(value int) ast.Expr {
	return &ast.BasicLit{Kind: token.INT, Value: fmt.Sprintf("%d", value)}
}

func hexLiteral(value uint32) ast.Expr {
	return &ast.BasicLit{Kind: token.INT, Value: fmt.Sprintf("0x%08x", value)}
}

func comment(value string) *ast.CommentGroup {
	lines := bytes.Split([]byte(value), []byte{'\n'})
	comments := make([]*ast.Comment, 0, len(lines))
	for _, line := range lines {
		comments = append(comments, &ast.Comment{Text: "// " + string(line)})
	}
	return &ast.CommentGroup{List: comments}
}
