package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteOutputsAndRemovesStaleGeneratedFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	stale := filepath.Join(root, "tl", "zz_stale.go")
	if err := os.MkdirAll(filepath.Dir(stale), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(
		stale,
		append(generatedPrefix, []byte("old); DO NOT EDIT.\npackage tl\n")...),
		0o644,
	); err != nil {
		t.Fatalf("write stale file: %v", err)
	}

	outputs := []Output{
		{
			Path: "tl/api.go",
			Data: []byte("// Code generated by cmd/tlgen (test); DO NOT EDIT.\npackage tl\n"),
		},
		{
			Path: "tl/mtp.go",
			Data: []byte("// Code generated by cmd/tlgen (test); DO NOT EDIT.\npackage tl\n"),
		},
	}
	if err := Write(root, outputs); err != nil {
		t.Fatalf("Write: %v", err)
	}
	for _, output := range outputs {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(output.Path)))
		if err != nil {
			t.Fatalf("read %q: %v", output.Path, err)
		}
		if string(data) != string(output.Data) {
			t.Errorf("%q data differs", output.Path)
		}
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Fatalf("stale file still exists: %v", err)
	}
}

func TestWritePreservesHandwrittenFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	target := filepath.Join(root, "tl", "zz_manual.go")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(target, []byte("package tl\n"), 0o644); err != nil {
		t.Fatalf("write manual file: %v", err)
	}

	if err := Write(root, nil); err != nil {
		t.Fatalf("Write: %v", err)
	}
	if _, err := os.Stat(target); err != nil {
		t.Fatalf("manual file was removed: %v", err)
	}
}

func TestWriteRefusesToOverwriteHandwrittenTarget(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	target := filepath.Join(root, "tl", "api.go")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	original := []byte("package tl\n")
	if err := os.WriteFile(target, original, 0o644); err != nil {
		t.Fatalf("write manual file: %v", err)
	}

	err := Write(root, []Output{
		{
			Path: "tl/api.go",
			Data: []byte("// Code generated by cmd/tlgen (test); DO NOT EDIT.\npackage tl\n"),
		},
	})
	if err == nil || !strings.Contains(err.Error(), "refuse to overwrite") {
		t.Fatalf("Write error = %v, want overwrite refusal", err)
	}
	data, readErr := os.ReadFile(target)
	if readErr != nil {
		t.Fatalf("read manual file: %v", readErr)
	}
	if string(data) != string(original) {
		t.Fatal("manual file changed")
	}
}

func TestWriteRejectsUnsafePath(t *testing.T) {
	t.Parallel()

	err := Write(t.TempDir(), []Output{
		{Path: "../tl/api.go", Data: []byte("unsafe")},
	})
	if err == nil || !strings.Contains(err.Error(), "unsafe") {
		t.Fatalf("Write error = %v, want unsafe path", err)
	}
}
