// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// SyntheticDummyUpdate represents TL class mtcute.dummyUpdate (ID 0x24a6b90e).
type SyntheticDummyUpdate struct {
	PTS       int32
	PTSCount  int32
	ChannelID int64
}

// SyntheticDummyUpdateConstructorID is the TL constructor ID for mtcute.dummyUpdate.
const SyntheticDummyUpdateConstructorID uint32 = 0x24a6b90e

// ConstructorID returns the TL constructor ID.
func (*SyntheticDummyUpdate) ConstructorID() uint32 {
	return SyntheticDummyUpdateConstructorID
}

func (*SyntheticDummyUpdate) isUpdateClass() {
}

func (value *SyntheticDummyUpdate) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.dummyUpdate", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SyntheticDummyUpdate) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.dummyUpdate", "", ErrNilObject)
	}
	size := 0
	size += 4
	size += 4
	size += 8
	return size, nil
}

func (value *SyntheticDummyUpdate) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.dummyUpdate", "", ErrNilObject)
	}
	output.putUint32(SyntheticDummyUpdateConstructorID)
	return value.encodeBody(output)
}

func (value *SyntheticDummyUpdate) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.dummyUpdate", "", ErrNilObject)
	}
	output.putInt32(value.PTS)
	output.putInt32(value.PTSCount)
	output.putInt64(value.ChannelID)
	return output, nil
}

// decodeSyntheticDummyUpdate decodes a TL Update.
func decodeSyntheticDummyUpdate(input *decoder) (*SyntheticDummyUpdate, error) {
	if err := input.reserveAllocation("mtcute.dummyUpdate", decodedAllocationSize(16, 24)); err != nil {
		return nil, err
	}
	value := new(SyntheticDummyUpdate)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *SyntheticDummyUpdate) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.PTS = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.PTSCount = _field1
	_field2, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.ChannelID = _field2
	input.leave()
	return nil
}

// SyntheticDummyInputPeerMinChannel represents TL class mtcute.dummyInputPeerMinChannel (ID 0x6b0f6896).
type SyntheticDummyInputPeerMinChannel struct {
	ChannelID int32
}

// SyntheticDummyInputPeerMinChannelConstructorID is the TL constructor ID for mtcute.dummyInputPeerMinChannel.
const SyntheticDummyInputPeerMinChannelConstructorID uint32 = 0x6b0f6896

// ConstructorID returns the TL constructor ID.
func (*SyntheticDummyInputPeerMinChannel) ConstructorID() uint32 {
	return SyntheticDummyInputPeerMinChannelConstructorID
}

func (*SyntheticDummyInputPeerMinChannel) isInputPeerClass() {
}

func (value *SyntheticDummyInputPeerMinChannel) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.dummyInputPeerMinChannel", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SyntheticDummyInputPeerMinChannel) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.dummyInputPeerMinChannel", "", ErrNilObject)
	}
	size := 0
	size += 4
	return size, nil
}

func (value *SyntheticDummyInputPeerMinChannel) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.dummyInputPeerMinChannel", "", ErrNilObject)
	}
	output.putUint32(SyntheticDummyInputPeerMinChannelConstructorID)
	return value.encodeBody(output)
}

func (value *SyntheticDummyInputPeerMinChannel) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.dummyInputPeerMinChannel", "", ErrNilObject)
	}
	output.putInt32(value.ChannelID)
	return output, nil
}

// decodeSyntheticDummyInputPeerMinChannel decodes a TL InputPeer.
func decodeSyntheticDummyInputPeerMinChannel(input *decoder) (*SyntheticDummyInputPeerMinChannel, error) {
	if err := input.reserveAllocation("mtcute.dummyInputPeerMinChannel", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(SyntheticDummyInputPeerMinChannel)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *SyntheticDummyInputPeerMinChannel) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.ChannelID = _field0
	input.leave()
	return nil
}

// SyntheticDummyInputPeerMinUser represents TL class mtcute.dummyInputPeerMinUser (ID 0x858c0622).
type SyntheticDummyInputPeerMinUser struct {
	UserID int32
}

// SyntheticDummyInputPeerMinUserConstructorID is the TL constructor ID for mtcute.dummyInputPeerMinUser.
const SyntheticDummyInputPeerMinUserConstructorID uint32 = 0x858c0622

// ConstructorID returns the TL constructor ID.
func (*SyntheticDummyInputPeerMinUser) ConstructorID() uint32 {
	return SyntheticDummyInputPeerMinUserConstructorID
}

func (*SyntheticDummyInputPeerMinUser) isInputPeerClass() {
}

func (value *SyntheticDummyInputPeerMinUser) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.dummyInputPeerMinUser", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SyntheticDummyInputPeerMinUser) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.dummyInputPeerMinUser", "", ErrNilObject)
	}
	size := 0
	size += 4
	return size, nil
}

func (value *SyntheticDummyInputPeerMinUser) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.dummyInputPeerMinUser", "", ErrNilObject)
	}
	output.putUint32(SyntheticDummyInputPeerMinUserConstructorID)
	return value.encodeBody(output)
}

func (value *SyntheticDummyInputPeerMinUser) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.dummyInputPeerMinUser", "", ErrNilObject)
	}
	output.putInt32(value.UserID)
	return output, nil
}

// decodeSyntheticDummyInputPeerMinUser decodes a TL InputPeer.
func decodeSyntheticDummyInputPeerMinUser(input *decoder) (*SyntheticDummyInputPeerMinUser, error) {
	if err := input.reserveAllocation("mtcute.dummyInputPeerMinUser", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(SyntheticDummyInputPeerMinUser)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *SyntheticDummyInputPeerMinUser) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.UserID = _field0
	input.leave()
	return nil
}

// SyntheticCustomMethodRequest represents TL method mtcute.customMethod (ID 0x9172c8fd).
type SyntheticCustomMethodRequest struct {
	Bytes []byte
}

// SyntheticCustomMethodRequestConstructorID is the TL constructor ID for mtcute.customMethod.
const SyntheticCustomMethodRequestConstructorID uint32 = 0x9172c8fd

// ConstructorID returns the TL constructor ID.
func (*SyntheticCustomMethodRequest) ConstructorID() uint32 {
	return SyntheticCustomMethodRequestConstructorID
}

func (*SyntheticCustomMethodRequest) requestResult([]byte) {}

func (value *SyntheticCustomMethodRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.customMethod", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SyntheticCustomMethodRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("mtcute.customMethod", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.Bytes))
	if err != nil {
		return 0, encodeError("mtcute.customMethod", "bytes", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("mtcute.customMethod", "bytes", err)
	}
	return size, nil
}

func (value *SyntheticCustomMethodRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.customMethod", "", ErrNilObject)
	}
	output.putUint32(SyntheticCustomMethodRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SyntheticCustomMethodRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("mtcute.customMethod", "", ErrNilObject)
	}
	if err := output.putBytes(value.Bytes); err != nil {
		return output, encodeError("mtcute.customMethod", "bytes", err)
	}
	return output, nil
}

func (request *SyntheticCustomMethodRequest) decodeResult(state decoder) ([]byte, decoder, error) {
	var zero []byte
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result []byte
	_field0, err := input.readBytes()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}
