// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// FoldersEditPeerFoldersRequest represents TL method folders.editPeerFolders (ID 0x6847d0ab).
type FoldersEditPeerFoldersRequest struct {
	FolderPeers []InputFolderPeerClass
}

// FoldersEditPeerFoldersRequestConstructorID is the TL constructor ID for folders.editPeerFolders.
const FoldersEditPeerFoldersRequestConstructorID uint32 = 0x6847d0ab

// ConstructorID returns the TL constructor ID.
func (*FoldersEditPeerFoldersRequest) ConstructorID() uint32 {
	return FoldersEditPeerFoldersRequestConstructorID
}

func (*FoldersEditPeerFoldersRequest) requestResult(UpdatesClass) {}

func (value *FoldersEditPeerFoldersRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("folders.editPeerFolders", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *FoldersEditPeerFoldersRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("folders.editPeerFolders", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.FolderPeers)); err != nil {
		return 0, encodeError("folders.editPeerFolders", "folder_peers", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.FolderPeers {
		if value.FolderPeers[_index0] == nil {
			return 0, encodeError("folders.editPeerFolders", "folder_peers", ErrNilObject)
		}
		_fieldSize1, err := value.FolderPeers[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("folders.editPeerFolders", "folder_peers", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("folders.editPeerFolders", "folder_peers", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("folders.editPeerFolders", "folder_peers", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *FoldersEditPeerFoldersRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("folders.editPeerFolders", "", ErrNilObject)
	}
	output.putUint32(FoldersEditPeerFoldersRequestConstructorID)
	return value.encodeBody(output)
}

func (value *FoldersEditPeerFoldersRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("folders.editPeerFolders", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.FolderPeers)); err != nil {
		return output, encodeError("folders.editPeerFolders", "folder_peers", err)
	}
	for _index := range value.FolderPeers {
		if value.FolderPeers[_index] == nil {
			return output, encodeError("folders.editPeerFolders", "folder_peers", ErrNilObject)
		}
		_output0, err := value.FolderPeers[_index].encode(output)
		if err != nil {
			return output, encodeError("folders.editPeerFolders", "folder_peers", err)
		}
		output = _output0
	}
	return output, nil
}

func (request *FoldersEditPeerFoldersRequest) decodeResult(state decoder) (UpdatesClass, decoder, error) {
	var zero UpdatesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesClass
	_field0, err := decodeUpdatesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}
