// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// UploadCDNFileClass is the TL union upload.CdnFile.
type UploadCDNFileClass interface {
	Object
	isUploadCDNFileClass()
}

// decodeUploadCDNFileClass decodes the TL union upload.CdnFile.
func decodeUploadCDNFileClass(input *decoder) (UploadCDNFileClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UploadCDNFileConstructorID:
		value, err := decodeUploadCDNFile(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UploadCDNFileReuploadNeededConstructorID:
		value, err := decodeUploadCDNFileReuploadNeeded(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UploadCDNFileClass", constructor)
	}
}

// UploadFileClass is the TL union upload.File.
type UploadFileClass interface {
	Object
	isUploadFileClass()
}

// decodeUploadFileClass decodes the TL union upload.File.
func decodeUploadFileClass(input *decoder) (UploadFileClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UploadFileConstructorID:
		value, err := decodeUploadFile(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UploadFileCDNRedirectConstructorID:
		value, err := decodeUploadFileCDNRedirect(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UploadFileClass", constructor)
	}
}

// UploadWebFileClass is the TL union upload.WebFile.
type UploadWebFileClass interface {
	Object
	isUploadWebFileClass()
}

// decodeUploadWebFileClass decodes the TL union upload.WebFile.
func decodeUploadWebFileClass(input *decoder) (UploadWebFileClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UploadWebFileConstructorID:
		value, err := decodeUploadWebFile(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UploadWebFileClass", constructor)
	}
}

// UploadFile represents TL class upload.file (ID 0x096a18d5).
type UploadFile struct {
	Type  StorageFileTypeClass
	Mtime int32
	Bytes []byte
}

// UploadFileConstructorID is the TL constructor ID for upload.file.
const UploadFileConstructorID uint32 = 0x096a18d5

// ConstructorID returns the TL constructor ID.
func (*UploadFile) ConstructorID() uint32 {
	return UploadFileConstructorID
}

func (*UploadFile) isUploadFileClass() {
}

func (value *UploadFile) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.file", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadFile) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.file", "", ErrNilObject)
	}
	size := 0
	if value.Type == nil {
		return 0, encodeError("upload.file", "type", ErrNilObject)
	}
	_fieldSize0, err := value.Type.encodedSize()
	if err != nil {
		return 0, encodeError("upload.file", "type", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.file", "type", err)
	}
	size += 4
	_fieldSize1, err := bytesEncodedSize(len(value.Bytes))
	if err != nil {
		return 0, encodeError("upload.file", "bytes", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("upload.file", "bytes", err)
	}
	return size, nil
}

func (value *UploadFile) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.file", "", ErrNilObject)
	}
	output.putUint32(UploadFileConstructorID)
	return value.encodeBody(output)
}

func (value *UploadFile) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.file", "", ErrNilObject)
	}
	if value.Type == nil {
		return output, encodeError("upload.file", "type", ErrNilObject)
	}
	_output0, err := value.Type.encode(output)
	if err != nil {
		return output, encodeError("upload.file", "type", err)
	}
	output = _output0
	output.putInt32(value.Mtime)
	if err := output.putBytes(value.Bytes); err != nil {
		return output, encodeError("upload.file", "bytes", err)
	}
	return output, nil
}

// decodeUploadFile decodes a TL upload.File.
func decodeUploadFile(input *decoder) (*UploadFile, error) {
	if err := input.reserveAllocation("upload.file", decodedAllocationSize(24, 48)); err != nil {
		return nil, err
	}
	value := new(UploadFile)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UploadFile) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := decodeStorageFileTypeClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.Type = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Mtime = _field1
	_field2, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.Bytes = _field2
	input.leave()
	return nil
}

// UploadWebFile represents TL class upload.webFile (ID 0x21e753bc).
type UploadWebFile struct {
	Size     int32
	MimeType string
	FileType StorageFileTypeClass
	Mtime    int32
	Bytes    []byte
}

// UploadWebFileConstructorID is the TL constructor ID for upload.webFile.
const UploadWebFileConstructorID uint32 = 0x21e753bc

// ConstructorID returns the TL constructor ID.
func (*UploadWebFile) ConstructorID() uint32 {
	return UploadWebFileConstructorID
}

func (*UploadWebFile) isUploadWebFileClass() {
}

func (value *UploadWebFile) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.webFile", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadWebFile) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.webFile", "", ErrNilObject)
	}
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.MimeType))
	if err != nil {
		return 0, encodeError("upload.webFile", "mime_type", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.webFile", "mime_type", err)
	}
	if value.FileType == nil {
		return 0, encodeError("upload.webFile", "file_type", ErrNilObject)
	}
	_fieldSize1, err := value.FileType.encodedSize()
	if err != nil {
		return 0, encodeError("upload.webFile", "file_type", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("upload.webFile", "file_type", err)
	}
	size += 4
	_fieldSize2, err := bytesEncodedSize(len(value.Bytes))
	if err != nil {
		return 0, encodeError("upload.webFile", "bytes", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("upload.webFile", "bytes", err)
	}
	return size, nil
}

func (value *UploadWebFile) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.webFile", "", ErrNilObject)
	}
	output.putUint32(UploadWebFileConstructorID)
	return value.encodeBody(output)
}

func (value *UploadWebFile) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.webFile", "", ErrNilObject)
	}
	output.putInt32(value.Size)
	if err := output.putString(value.MimeType); err != nil {
		return output, encodeError("upload.webFile", "mime_type", err)
	}
	if value.FileType == nil {
		return output, encodeError("upload.webFile", "file_type", ErrNilObject)
	}
	_output0, err := value.FileType.encode(output)
	if err != nil {
		return output, encodeError("upload.webFile", "file_type", err)
	}
	output = _output0
	output.putInt32(value.Mtime)
	if err := output.putBytes(value.Bytes); err != nil {
		return output, encodeError("upload.webFile", "bytes", err)
	}
	return output, nil
}

// decodeUploadWebFile decodes a TL upload.WebFile.
func decodeUploadWebFile(input *decoder) (*UploadWebFile, error) {
	if err := input.reserveAllocation("upload.webFile", decodedAllocationSize(36, 72)); err != nil {
		return nil, err
	}
	value := new(UploadWebFile)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UploadWebFile) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Size = _field0
	_field1, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.MimeType = _field1
	_field2, err := decodeStorageFileTypeClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.FileType = _field2
	_field3, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Mtime = _field3
	_field4, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.Bytes = _field4
	input.leave()
	return nil
}

// UploadGetWebFileRequest represents TL method upload.getWebFile (ID 0x24e6818d).
type UploadGetWebFileRequest struct {
	Location InputWebFileLocationClass
	Offset   int32
	Limit    int32
}

// UploadGetWebFileRequestConstructorID is the TL constructor ID for upload.getWebFile.
const UploadGetWebFileRequestConstructorID uint32 = 0x24e6818d

// ConstructorID returns the TL constructor ID.
func (*UploadGetWebFileRequest) ConstructorID() uint32 {
	return UploadGetWebFileRequestConstructorID
}

func (*UploadGetWebFileRequest) requestResult(*UploadWebFile) {}

func (value *UploadGetWebFileRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getWebFile", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadGetWebFileRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getWebFile", "", ErrNilObject)
	}
	size := 0
	if value.Location == nil {
		return 0, encodeError("upload.getWebFile", "location", ErrNilObject)
	}
	_fieldSize0, err := value.Location.encodedSize()
	if err != nil {
		return 0, encodeError("upload.getWebFile", "location", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.getWebFile", "location", err)
	}
	size += 4
	size += 4
	return size, nil
}

func (value *UploadGetWebFileRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getWebFile", "", ErrNilObject)
	}
	output.putUint32(UploadGetWebFileRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadGetWebFileRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getWebFile", "", ErrNilObject)
	}
	if value.Location == nil {
		return output, encodeError("upload.getWebFile", "location", ErrNilObject)
	}
	_output0, err := value.Location.encode(output)
	if err != nil {
		return output, encodeError("upload.getWebFile", "location", err)
	}
	output = _output0
	output.putInt32(value.Offset)
	output.putInt32(value.Limit)
	return output, nil
}

func (request *UploadGetWebFileRequest) decodeResult(state decoder) (*UploadWebFile, decoder, error) {
	var zero *UploadWebFile
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *UploadWebFile
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0x21e753bc {
		err := input.unexpectedConstructor(_start0, "UploadWebFile", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("upload.getWebFile.result", decodedAllocationSize(36, 72)); err != nil {
		return zero, state, err
	}
	_field1 := new(UploadWebFile)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// UploadGetCDNFileRequest represents TL method upload.getCdnFile (ID 0x395f69da).
type UploadGetCDNFileRequest struct {
	FileToken []byte
	Offset    int64
	Limit     int32
}

// UploadGetCDNFileRequestConstructorID is the TL constructor ID for upload.getCdnFile.
const UploadGetCDNFileRequestConstructorID uint32 = 0x395f69da

// ConstructorID returns the TL constructor ID.
func (*UploadGetCDNFileRequest) ConstructorID() uint32 {
	return UploadGetCDNFileRequestConstructorID
}

func (*UploadGetCDNFileRequest) requestResult(UploadCDNFileClass) {}

func (value *UploadGetCDNFileRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getCdnFile", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadGetCDNFileRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getCdnFile", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.FileToken))
	if err != nil {
		return 0, encodeError("upload.getCdnFile", "file_token", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.getCdnFile", "file_token", err)
	}
	size += 8
	size += 4
	return size, nil
}

func (value *UploadGetCDNFileRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getCdnFile", "", ErrNilObject)
	}
	output.putUint32(UploadGetCDNFileRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadGetCDNFileRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getCdnFile", "", ErrNilObject)
	}
	if err := output.putBytes(value.FileToken); err != nil {
		return output, encodeError("upload.getCdnFile", "file_token", err)
	}
	output.putInt64(value.Offset)
	output.putInt32(value.Limit)
	return output, nil
}

func (request *UploadGetCDNFileRequest) decodeResult(state decoder) (UploadCDNFileClass, decoder, error) {
	var zero UploadCDNFileClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UploadCDNFileClass
	_field0, err := decodeUploadCDNFileClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UploadGetFileHashesRequest represents TL method upload.getFileHashes (ID 0x9156982a).
type UploadGetFileHashesRequest struct {
	Location InputFileLocationClass
	Offset   int64
}

// UploadGetFileHashesRequestConstructorID is the TL constructor ID for upload.getFileHashes.
const UploadGetFileHashesRequestConstructorID uint32 = 0x9156982a

// ConstructorID returns the TL constructor ID.
func (*UploadGetFileHashesRequest) ConstructorID() uint32 {
	return UploadGetFileHashesRequestConstructorID
}

func (*UploadGetFileHashesRequest) requestResult([]FileHash) {}

func (value *UploadGetFileHashesRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getFileHashes", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadGetFileHashesRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getFileHashes", "", ErrNilObject)
	}
	size := 0
	if value.Location == nil {
		return 0, encodeError("upload.getFileHashes", "location", ErrNilObject)
	}
	_fieldSize0, err := value.Location.encodedSize()
	if err != nil {
		return 0, encodeError("upload.getFileHashes", "location", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.getFileHashes", "location", err)
	}
	size += 8
	return size, nil
}

func (value *UploadGetFileHashesRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getFileHashes", "", ErrNilObject)
	}
	output.putUint32(UploadGetFileHashesRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadGetFileHashesRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getFileHashes", "", ErrNilObject)
	}
	if value.Location == nil {
		return output, encodeError("upload.getFileHashes", "location", ErrNilObject)
	}
	_output0, err := value.Location.encode(output)
	if err != nil {
		return output, encodeError("upload.getFileHashes", "location", err)
	}
	output = _output0
	output.putInt64(value.Offset)
	return output, nil
}

func (request *UploadGetFileHashesRequest) decodeResult(state decoder) ([]FileHash, decoder, error) {
	var zero []FileHash
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result []FileHash
	_count0, err := input.readVectorHeader()
	if err != nil {
		return zero, state, err
	}
	if err := input.reserveAllocationProduct("upload.getFileHashes.result", _count0, decodedAllocationSize(24, 40)); err != nil {
		return zero, state, err
	}
	result = make([]FileHash, _count0)
	for _index0 := range result {
		_start1 := input.offset
		_constructor1, err := input.readUint32()
		if err != nil {
			return zero, state, err
		}
		if _constructor1 != 0xf39b035c {
			err := input.unexpectedConstructor(_start1, "FileHash", _constructor1)
			return zero, state, err
		}
		if err := result[_index0].decodeBody(input); err != nil {
			return zero, state, err
		}
	}
	return result, state, nil
}

// UploadGetCDNFileHashesRequest represents TL method upload.getCdnFileHashes (ID 0x91dc3f31).
type UploadGetCDNFileHashesRequest struct {
	FileToken []byte
	Offset    int64
}

// UploadGetCDNFileHashesRequestConstructorID is the TL constructor ID for upload.getCdnFileHashes.
const UploadGetCDNFileHashesRequestConstructorID uint32 = 0x91dc3f31

// ConstructorID returns the TL constructor ID.
func (*UploadGetCDNFileHashesRequest) ConstructorID() uint32 {
	return UploadGetCDNFileHashesRequestConstructorID
}

func (*UploadGetCDNFileHashesRequest) requestResult([]FileHash) {}

func (value *UploadGetCDNFileHashesRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getCdnFileHashes", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadGetCDNFileHashesRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getCdnFileHashes", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.FileToken))
	if err != nil {
		return 0, encodeError("upload.getCdnFileHashes", "file_token", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.getCdnFileHashes", "file_token", err)
	}
	size += 8
	return size, nil
}

func (value *UploadGetCDNFileHashesRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getCdnFileHashes", "", ErrNilObject)
	}
	output.putUint32(UploadGetCDNFileHashesRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadGetCDNFileHashesRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getCdnFileHashes", "", ErrNilObject)
	}
	if err := output.putBytes(value.FileToken); err != nil {
		return output, encodeError("upload.getCdnFileHashes", "file_token", err)
	}
	output.putInt64(value.Offset)
	return output, nil
}

func (request *UploadGetCDNFileHashesRequest) decodeResult(state decoder) ([]FileHash, decoder, error) {
	var zero []FileHash
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result []FileHash
	_count0, err := input.readVectorHeader()
	if err != nil {
		return zero, state, err
	}
	if err := input.reserveAllocationProduct("upload.getCdnFileHashes.result", _count0, decodedAllocationSize(24, 40)); err != nil {
		return zero, state, err
	}
	result = make([]FileHash, _count0)
	for _index0 := range result {
		_start1 := input.offset
		_constructor1, err := input.readUint32()
		if err != nil {
			return zero, state, err
		}
		if _constructor1 != 0xf39b035c {
			err := input.unexpectedConstructor(_start1, "FileHash", _constructor1)
			return zero, state, err
		}
		if err := result[_index0].decodeBody(input); err != nil {
			return zero, state, err
		}
	}
	return result, state, nil
}

// UploadReuploadCDNFileRequest represents TL method upload.reuploadCdnFile (ID 0x9b2754a8).
type UploadReuploadCDNFileRequest struct {
	FileToken    []byte
	RequestToken []byte
}

// UploadReuploadCDNFileRequestConstructorID is the TL constructor ID for upload.reuploadCdnFile.
const UploadReuploadCDNFileRequestConstructorID uint32 = 0x9b2754a8

// ConstructorID returns the TL constructor ID.
func (*UploadReuploadCDNFileRequest) ConstructorID() uint32 {
	return UploadReuploadCDNFileRequestConstructorID
}

func (*UploadReuploadCDNFileRequest) requestResult([]FileHash) {}

func (value *UploadReuploadCDNFileRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.reuploadCdnFile", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadReuploadCDNFileRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.reuploadCdnFile", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.FileToken))
	if err != nil {
		return 0, encodeError("upload.reuploadCdnFile", "file_token", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.reuploadCdnFile", "file_token", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.RequestToken))
	if err != nil {
		return 0, encodeError("upload.reuploadCdnFile", "request_token", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("upload.reuploadCdnFile", "request_token", err)
	}
	return size, nil
}

func (value *UploadReuploadCDNFileRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.reuploadCdnFile", "", ErrNilObject)
	}
	output.putUint32(UploadReuploadCDNFileRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadReuploadCDNFileRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.reuploadCdnFile", "", ErrNilObject)
	}
	if err := output.putBytes(value.FileToken); err != nil {
		return output, encodeError("upload.reuploadCdnFile", "file_token", err)
	}
	if err := output.putBytes(value.RequestToken); err != nil {
		return output, encodeError("upload.reuploadCdnFile", "request_token", err)
	}
	return output, nil
}

func (request *UploadReuploadCDNFileRequest) decodeResult(state decoder) ([]FileHash, decoder, error) {
	var zero []FileHash
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result []FileHash
	_count0, err := input.readVectorHeader()
	if err != nil {
		return zero, state, err
	}
	if err := input.reserveAllocationProduct("upload.reuploadCdnFile.result", _count0, decodedAllocationSize(24, 40)); err != nil {
		return zero, state, err
	}
	result = make([]FileHash, _count0)
	for _index0 := range result {
		_start1 := input.offset
		_constructor1, err := input.readUint32()
		if err != nil {
			return zero, state, err
		}
		if _constructor1 != 0xf39b035c {
			err := input.unexpectedConstructor(_start1, "FileHash", _constructor1)
			return zero, state, err
		}
		if err := result[_index0].decodeBody(input); err != nil {
			return zero, state, err
		}
	}
	return result, state, nil
}

// UploadCDNFile represents TL class upload.cdnFile (ID 0xa99fca4f).
type UploadCDNFile struct {
	Bytes []byte
}

// UploadCDNFileConstructorID is the TL constructor ID for upload.cdnFile.
const UploadCDNFileConstructorID uint32 = 0xa99fca4f

// ConstructorID returns the TL constructor ID.
func (*UploadCDNFile) ConstructorID() uint32 {
	return UploadCDNFileConstructorID
}

func (*UploadCDNFile) isUploadCDNFileClass() {
}

func (value *UploadCDNFile) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.cdnFile", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadCDNFile) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.cdnFile", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.Bytes))
	if err != nil {
		return 0, encodeError("upload.cdnFile", "bytes", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.cdnFile", "bytes", err)
	}
	return size, nil
}

func (value *UploadCDNFile) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.cdnFile", "", ErrNilObject)
	}
	output.putUint32(UploadCDNFileConstructorID)
	return value.encodeBody(output)
}

func (value *UploadCDNFile) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.cdnFile", "", ErrNilObject)
	}
	if err := output.putBytes(value.Bytes); err != nil {
		return output, encodeError("upload.cdnFile", "bytes", err)
	}
	return output, nil
}

// decodeUploadCDNFile decodes a TL upload.CdnFile.
func decodeUploadCDNFile(input *decoder) (*UploadCDNFile, error) {
	if err := input.reserveAllocation("upload.cdnFile", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(UploadCDNFile)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UploadCDNFile) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.Bytes = _field0
	input.leave()
	return nil
}

// UploadSaveFilePartRequest represents TL method upload.saveFilePart (ID 0xb304a621).
type UploadSaveFilePartRequest struct {
	FileID   int64
	FilePart int32
	Bytes    []byte
}

// UploadSaveFilePartRequestConstructorID is the TL constructor ID for upload.saveFilePart.
const UploadSaveFilePartRequestConstructorID uint32 = 0xb304a621

// ConstructorID returns the TL constructor ID.
func (*UploadSaveFilePartRequest) ConstructorID() uint32 {
	return UploadSaveFilePartRequestConstructorID
}

func (*UploadSaveFilePartRequest) requestResult(bool) {}

func (value *UploadSaveFilePartRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.saveFilePart", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadSaveFilePartRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.saveFilePart", "", ErrNilObject)
	}
	size := 0
	size += 8
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.Bytes))
	if err != nil {
		return 0, encodeError("upload.saveFilePart", "bytes", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.saveFilePart", "bytes", err)
	}
	return size, nil
}

func (value *UploadSaveFilePartRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.saveFilePart", "", ErrNilObject)
	}
	output.putUint32(UploadSaveFilePartRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadSaveFilePartRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.saveFilePart", "", ErrNilObject)
	}
	output.putInt64(value.FileID)
	output.putInt32(value.FilePart)
	if err := output.putBytes(value.Bytes); err != nil {
		return output, encodeError("upload.saveFilePart", "bytes", err)
	}
	return output, nil
}

func (request *UploadSaveFilePartRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UploadGetFileRequest represents TL method upload.getFile (ID 0xbe5335be).
type UploadGetFileRequest struct {
	Precise      bool
	CDNSupported bool
	Location     InputFileLocationClass
	Offset       int64
	Limit        int32
}

// UploadGetFileRequestConstructorID is the TL constructor ID for upload.getFile.
const UploadGetFileRequestConstructorID uint32 = 0xbe5335be

// ConstructorID returns the TL constructor ID.
func (*UploadGetFileRequest) ConstructorID() uint32 {
	return UploadGetFileRequestConstructorID
}

func (*UploadGetFileRequest) requestResult(UploadFileClass) {}

func (value *UploadGetFileRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getFile", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadGetFileRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.getFile", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Location == nil {
		return 0, encodeError("upload.getFile", "location", ErrNilObject)
	}
	_fieldSize0, err := value.Location.encodedSize()
	if err != nil {
		return 0, encodeError("upload.getFile", "location", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.getFile", "location", err)
	}
	size += 8
	size += 4
	return size, nil
}

func (value *UploadGetFileRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getFile", "", ErrNilObject)
	}
	output.putUint32(UploadGetFileRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadGetFileRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.getFile", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Precise
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.CDNSupported
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	if value.Location == nil {
		return output, encodeError("upload.getFile", "location", ErrNilObject)
	}
	_output0, err := value.Location.encode(output)
	if err != nil {
		return output, encodeError("upload.getFile", "location", err)
	}
	output = _output0
	output.putInt64(value.Offset)
	output.putInt32(value.Limit)
	return output, nil
}

func (request *UploadGetFileRequest) decodeResult(state decoder) (UploadFileClass, decoder, error) {
	var zero UploadFileClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UploadFileClass
	_field0, err := decodeUploadFileClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UploadSaveBigFilePartRequest represents TL method upload.saveBigFilePart (ID 0xde7b673d).
type UploadSaveBigFilePartRequest struct {
	FileID         int64
	FilePart       int32
	FileTotalParts int32
	Bytes          []byte
}

// UploadSaveBigFilePartRequestConstructorID is the TL constructor ID for upload.saveBigFilePart.
const UploadSaveBigFilePartRequestConstructorID uint32 = 0xde7b673d

// ConstructorID returns the TL constructor ID.
func (*UploadSaveBigFilePartRequest) ConstructorID() uint32 {
	return UploadSaveBigFilePartRequestConstructorID
}

func (*UploadSaveBigFilePartRequest) requestResult(bool) {}

func (value *UploadSaveBigFilePartRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.saveBigFilePart", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadSaveBigFilePartRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.saveBigFilePart", "", ErrNilObject)
	}
	size := 0
	size += 8
	size += 4
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.Bytes))
	if err != nil {
		return 0, encodeError("upload.saveBigFilePart", "bytes", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.saveBigFilePart", "bytes", err)
	}
	return size, nil
}

func (value *UploadSaveBigFilePartRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.saveBigFilePart", "", ErrNilObject)
	}
	output.putUint32(UploadSaveBigFilePartRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UploadSaveBigFilePartRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.saveBigFilePart", "", ErrNilObject)
	}
	output.putInt64(value.FileID)
	output.putInt32(value.FilePart)
	output.putInt32(value.FileTotalParts)
	if err := output.putBytes(value.Bytes); err != nil {
		return output, encodeError("upload.saveBigFilePart", "bytes", err)
	}
	return output, nil
}

func (request *UploadSaveBigFilePartRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UploadCDNFileReuploadNeeded represents TL class upload.cdnFileReuploadNeeded (ID 0xeea8e46e).
type UploadCDNFileReuploadNeeded struct {
	RequestToken []byte
}

// UploadCDNFileReuploadNeededConstructorID is the TL constructor ID for upload.cdnFileReuploadNeeded.
const UploadCDNFileReuploadNeededConstructorID uint32 = 0xeea8e46e

// ConstructorID returns the TL constructor ID.
func (*UploadCDNFileReuploadNeeded) ConstructorID() uint32 {
	return UploadCDNFileReuploadNeededConstructorID
}

func (*UploadCDNFileReuploadNeeded) isUploadCDNFileClass() {
}

func (value *UploadCDNFileReuploadNeeded) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.cdnFileReuploadNeeded", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadCDNFileReuploadNeeded) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.cdnFileReuploadNeeded", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.RequestToken))
	if err != nil {
		return 0, encodeError("upload.cdnFileReuploadNeeded", "request_token", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.cdnFileReuploadNeeded", "request_token", err)
	}
	return size, nil
}

func (value *UploadCDNFileReuploadNeeded) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.cdnFileReuploadNeeded", "", ErrNilObject)
	}
	output.putUint32(UploadCDNFileReuploadNeededConstructorID)
	return value.encodeBody(output)
}

func (value *UploadCDNFileReuploadNeeded) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.cdnFileReuploadNeeded", "", ErrNilObject)
	}
	if err := output.putBytes(value.RequestToken); err != nil {
		return output, encodeError("upload.cdnFileReuploadNeeded", "request_token", err)
	}
	return output, nil
}

// decodeUploadCDNFileReuploadNeeded decodes a TL upload.CdnFile.
func decodeUploadCDNFileReuploadNeeded(input *decoder) (*UploadCDNFileReuploadNeeded, error) {
	if err := input.reserveAllocation("upload.cdnFileReuploadNeeded", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(UploadCDNFileReuploadNeeded)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UploadCDNFileReuploadNeeded) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.RequestToken = _field0
	input.leave()
	return nil
}

// UploadFileCDNRedirect represents TL class upload.fileCdnRedirect (ID 0xf18cda44).
type UploadFileCDNRedirect struct {
	DCID          int32
	FileToken     []byte
	EncryptionKey []byte
	EncryptionIv  []byte
	FileHashes    []FileHashClass
}

// UploadFileCDNRedirectConstructorID is the TL constructor ID for upload.fileCdnRedirect.
const UploadFileCDNRedirectConstructorID uint32 = 0xf18cda44

// ConstructorID returns the TL constructor ID.
func (*UploadFileCDNRedirect) ConstructorID() uint32 {
	return UploadFileCDNRedirectConstructorID
}

func (*UploadFileCDNRedirect) isUploadFileClass() {
}

func (value *UploadFileCDNRedirect) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.fileCdnRedirect", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UploadFileCDNRedirect) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("upload.fileCdnRedirect", "", ErrNilObject)
	}
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.FileToken))
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "file_token", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "file_token", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.EncryptionKey))
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "encryption_key", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "encryption_key", err)
	}
	_fieldSize2, err := bytesEncodedSize(len(value.EncryptionIv))
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "encryption_iv", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "encryption_iv", err)
	}
	if err := validateVectorLength(len(value.FileHashes)); err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "file_hashes", err)
	}
	_vectorSize3 := 8
	for _index3 := range value.FileHashes {
		if value.FileHashes[_index3] == nil {
			return 0, encodeError("upload.fileCdnRedirect", "file_hashes", ErrNilObject)
		}
		_fieldSize4, err := value.FileHashes[_index3].encodedSize()
		if err != nil {
			return 0, encodeError("upload.fileCdnRedirect", "file_hashes", err)
		}
		_vectorSize3, err = checkedEncodedSizeAdd(_vectorSize3, _fieldSize4)
		if err != nil {
			return 0, encodeError("upload.fileCdnRedirect", "file_hashes", err)
		}
	}
	_totalSize3, err := checkedEncodedSizeAdd(size, _vectorSize3)
	if err != nil {
		return 0, encodeError("upload.fileCdnRedirect", "file_hashes", err)
	}
	size = _totalSize3
	return size, nil
}

func (value *UploadFileCDNRedirect) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.fileCdnRedirect", "", ErrNilObject)
	}
	output.putUint32(UploadFileCDNRedirectConstructorID)
	return value.encodeBody(output)
}

func (value *UploadFileCDNRedirect) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("upload.fileCdnRedirect", "", ErrNilObject)
	}
	output.putInt32(value.DCID)
	if err := output.putBytes(value.FileToken); err != nil {
		return output, encodeError("upload.fileCdnRedirect", "file_token", err)
	}
	if err := output.putBytes(value.EncryptionKey); err != nil {
		return output, encodeError("upload.fileCdnRedirect", "encryption_key", err)
	}
	if err := output.putBytes(value.EncryptionIv); err != nil {
		return output, encodeError("upload.fileCdnRedirect", "encryption_iv", err)
	}
	if err := output.putVectorHeader(len(value.FileHashes)); err != nil {
		return output, encodeError("upload.fileCdnRedirect", "file_hashes", err)
	}
	for _index := range value.FileHashes {
		if value.FileHashes[_index] == nil {
			return output, encodeError("upload.fileCdnRedirect", "file_hashes", ErrNilObject)
		}
		_output0, err := value.FileHashes[_index].encode(output)
		if err != nil {
			return output, encodeError("upload.fileCdnRedirect", "file_hashes", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeUploadFileCDNRedirect decodes a TL upload.File.
func decodeUploadFileCDNRedirect(input *decoder) (*UploadFileCDNRedirect, error) {
	if err := input.reserveAllocation("upload.fileCdnRedirect", decodedAllocationSize(52, 104)); err != nil {
		return nil, err
	}
	value := new(UploadFileCDNRedirect)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UploadFileCDNRedirect) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.DCID = _field0
	_field1, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.FileToken = _field1
	_field2, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.EncryptionKey = _field2
	_field3, err := input.readBytes()
	if err != nil {
		input.leave()
		return err
	}
	value.EncryptionIv = _field3
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("upload.fileCdnRedirect.file_hashes", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.FileHashes = make([]FileHashClass, _count4)
	for _index4 := range value.FileHashes {
		_field5, err := decodeFileHashClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.FileHashes[_index4] = _field5
	}
	input.leave()
	return nil
}
