// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 230

package tl

// ToncenterAPIResponseClass is the TL union toncenter.ApiResponse.
type ToncenterAPIResponseClass interface {
	Object
	isToncenterAPIResponseClass()
}

// decodeToncenterAPIResponseClass decodes the TL union toncenter.ApiResponse.
func decodeToncenterAPIResponseClass(input *decoder) (ToncenterAPIResponseClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case ToncenterAPIResponseConstructorID:
		value, err := decodeToncenterAPIResponse(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "ToncenterAPIResponseClass", constructor)
	}
}

// ToncenterStreamingURLClass is the TL union toncenter.StreamingUrl.
type ToncenterStreamingURLClass interface {
	Object
	isToncenterStreamingURLClass()
}

// decodeToncenterStreamingURLClass decodes the TL union toncenter.StreamingUrl.
func decodeToncenterStreamingURLClass(input *decoder) (ToncenterStreamingURLClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case ToncenterStreamingURLConstructorID:
		value, err := decodeToncenterStreamingURL(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "ToncenterStreamingURLClass", constructor)
	}
}

// ToncenterStreamingURL represents TL class toncenter.streamingUrl (ID 0x19887601).
type ToncenterStreamingURL struct {
	URL     string
	Expires int32
}

// ToncenterStreamingURLConstructorID is the TL constructor ID for toncenter.streamingUrl.
const ToncenterStreamingURLConstructorID uint32 = 0x19887601

// ConstructorID returns the TL constructor ID.
func (*ToncenterStreamingURL) ConstructorID() uint32 {
	return ToncenterStreamingURLConstructorID
}

func (*ToncenterStreamingURL) isToncenterStreamingURLClass() {
}

func (value *ToncenterStreamingURL) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.streamingUrl", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *ToncenterStreamingURL) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.streamingUrl", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.URL))
	if err != nil {
		return 0, encodeError("toncenter.streamingUrl", "url", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("toncenter.streamingUrl", "url", err)
	}
	size += 4
	return size, nil
}

func (value *ToncenterStreamingURL) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.streamingUrl", "", ErrNilObject)
	}
	output.putUint32(ToncenterStreamingURLConstructorID)
	return value.encodeBody(output)
}

func (value *ToncenterStreamingURL) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.streamingUrl", "", ErrNilObject)
	}
	if err := output.putString(value.URL); err != nil {
		return output, encodeError("toncenter.streamingUrl", "url", err)
	}
	output.putInt32(value.Expires)
	return output, nil
}

// decodeToncenterStreamingURL decodes a TL toncenter.StreamingUrl.
func decodeToncenterStreamingURL(input *decoder) (*ToncenterStreamingURL, error) {
	if err := input.reserveAllocation("toncenter.streamingUrl", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(ToncenterStreamingURL)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *ToncenterStreamingURL) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.URL = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Expires = _field1
	input.leave()
	return nil
}

// ToncenterPerformAPIRequestRequest represents TL method toncenter.performApiRequest (ID 0x8d7bdd61).
type ToncenterPerformAPIRequestRequest struct {
	Post     bool
	Endpoint string
	Query    *string
	Payload  *string
}

// ToncenterPerformAPIRequestRequestConstructorID is the TL constructor ID for toncenter.performApiRequest.
const ToncenterPerformAPIRequestRequestConstructorID uint32 = 0x8d7bdd61

// ConstructorID returns the TL constructor ID.
func (*ToncenterPerformAPIRequestRequest) ConstructorID() uint32 {
	return ToncenterPerformAPIRequestRequestConstructorID
}

func (*ToncenterPerformAPIRequestRequest) requestResult(ToncenterAPIResponseClass) {}

func (value *ToncenterPerformAPIRequestRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.performApiRequest", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *ToncenterPerformAPIRequestRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.performApiRequest", "", ErrNilObject)
	}
	_present1 := value.Query != nil
	_present2 := value.Payload != nil
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.Endpoint))
	if err != nil {
		return 0, encodeError("toncenter.performApiRequest", "endpoint", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("toncenter.performApiRequest", "endpoint", err)
	}
	if _present1 {
		_fieldSize1, err := bytesEncodedSize(len(*value.Query))
		if err != nil {
			return 0, encodeError("toncenter.performApiRequest", "query", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("toncenter.performApiRequest", "query", err)
		}
	}
	if _present2 {
		_fieldSize2, err := bytesEncodedSize(len(*value.Payload))
		if err != nil {
			return 0, encodeError("toncenter.performApiRequest", "payload", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("toncenter.performApiRequest", "payload", err)
		}
	}
	return size, nil
}

func (value *ToncenterPerformAPIRequestRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.performApiRequest", "", ErrNilObject)
	}
	output.putUint32(ToncenterPerformAPIRequestRequestConstructorID)
	return value.encodeBody(output)
}

func (value *ToncenterPerformAPIRequestRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.performApiRequest", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Post
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.Query != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.Payload != nil
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	output.putUint32(_flags0)
	if err := output.putString(value.Endpoint); err != nil {
		return output, encodeError("toncenter.performApiRequest", "endpoint", err)
	}
	if _present1 {
		if err := output.putString(*value.Query); err != nil {
			return output, encodeError("toncenter.performApiRequest", "query", err)
		}
	}
	if _present2 {
		if err := output.putString(*value.Payload); err != nil {
			return output, encodeError("toncenter.performApiRequest", "payload", err)
		}
	}
	return output, nil
}

func (request *ToncenterPerformAPIRequestRequest) decodeResult(state decoder) (ToncenterAPIResponseClass, decoder, error) {
	var zero ToncenterAPIResponseClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result ToncenterAPIResponseClass
	_field0, err := decodeToncenterAPIResponseClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// ToncenterAPIResponse represents TL class toncenter.apiResponse (ID 0xac8dfe19).
type ToncenterAPIResponse struct {
	Response DataJSONClass
}

// ToncenterAPIResponseConstructorID is the TL constructor ID for toncenter.apiResponse.
const ToncenterAPIResponseConstructorID uint32 = 0xac8dfe19

// ConstructorID returns the TL constructor ID.
func (*ToncenterAPIResponse) ConstructorID() uint32 {
	return ToncenterAPIResponseConstructorID
}

func (*ToncenterAPIResponse) isToncenterAPIResponseClass() {
}

func (value *ToncenterAPIResponse) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.apiResponse", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *ToncenterAPIResponse) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.apiResponse", "", ErrNilObject)
	}
	size := 0
	if value.Response == nil {
		return 0, encodeError("toncenter.apiResponse", "response", ErrNilObject)
	}
	_fieldSize0, err := value.Response.encodedSize()
	if err != nil {
		return 0, encodeError("toncenter.apiResponse", "response", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("toncenter.apiResponse", "response", err)
	}
	return size, nil
}

func (value *ToncenterAPIResponse) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.apiResponse", "", ErrNilObject)
	}
	output.putUint32(ToncenterAPIResponseConstructorID)
	return value.encodeBody(output)
}

func (value *ToncenterAPIResponse) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.apiResponse", "", ErrNilObject)
	}
	if value.Response == nil {
		return output, encodeError("toncenter.apiResponse", "response", ErrNilObject)
	}
	_output0, err := value.Response.encode(output)
	if err != nil {
		return output, encodeError("toncenter.apiResponse", "response", err)
	}
	output = _output0
	return output, nil
}

// decodeToncenterAPIResponse decodes a TL toncenter.ApiResponse.
func decodeToncenterAPIResponse(input *decoder) (*ToncenterAPIResponse, error) {
	if err := input.reserveAllocation("toncenter.apiResponse", decodedAllocationSize(8, 16)); err != nil {
		return nil, err
	}
	value := new(ToncenterAPIResponse)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *ToncenterAPIResponse) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := decodeDataJSONClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.Response = _field0
	input.leave()
	return nil
}

// ToncenterGetStreamingURLRequest represents TL method toncenter.getStreamingUrl (ID 0xcdaf63c7).
type ToncenterGetStreamingURLRequest struct {
}

// ToncenterGetStreamingURLRequestConstructorID is the TL constructor ID for toncenter.getStreamingUrl.
const ToncenterGetStreamingURLRequestConstructorID uint32 = 0xcdaf63c7

// ConstructorID returns the TL constructor ID.
func (*ToncenterGetStreamingURLRequest) ConstructorID() uint32 {
	return ToncenterGetStreamingURLRequestConstructorID
}

func (*ToncenterGetStreamingURLRequest) requestResult(ToncenterStreamingURLClass) {}

func (value *ToncenterGetStreamingURLRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.getStreamingUrl", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *ToncenterGetStreamingURLRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("toncenter.getStreamingUrl", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *ToncenterGetStreamingURLRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.getStreamingUrl", "", ErrNilObject)
	}
	output.putUint32(ToncenterGetStreamingURLRequestConstructorID)
	return value.encodeBody(output)
}

func (value *ToncenterGetStreamingURLRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("toncenter.getStreamingUrl", "", ErrNilObject)
	}
	return output, nil
}

func (request *ToncenterGetStreamingURLRequest) decodeResult(state decoder) (ToncenterStreamingURLClass, decoder, error) {
	var zero ToncenterStreamingURLClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result ToncenterStreamingURLClass
	_field0, err := decodeToncenterStreamingURLClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}
