// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 228

package tl

// UpdatesChannelDifferenceClass is the TL union updates.ChannelDifference.
type UpdatesChannelDifferenceClass interface {
	Object
	isUpdatesChannelDifferenceClass()
}

// decodeUpdatesChannelDifferenceClass decodes the TL union updates.ChannelDifference.
func decodeUpdatesChannelDifferenceClass(input *decoder) (UpdatesChannelDifferenceClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UpdatesChannelDifferenceConstructorID:
		value, err := decodeUpdatesChannelDifference(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UpdatesChannelDifferenceEmptyConstructorID:
		value, err := decodeUpdatesChannelDifferenceEmpty(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UpdatesChannelDifferenceTooLongConstructorID:
		value, err := decodeUpdatesChannelDifferenceTooLong(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UpdatesChannelDifferenceClass", constructor)
	}
}

// UpdatesDifferenceClass is the TL union updates.Difference.
type UpdatesDifferenceClass interface {
	Object
	isUpdatesDifferenceClass()
}

// decodeUpdatesDifferenceClass decodes the TL union updates.Difference.
func decodeUpdatesDifferenceClass(input *decoder) (UpdatesDifferenceClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UpdatesDifferenceConstructorID:
		value, err := decodeUpdatesDifference(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UpdatesDifferenceTooLongConstructorID:
		value, err := decodeUpdatesDifferenceTooLong(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UpdatesDifferenceEmptyConstructorID:
		value, err := decodeUpdatesDifferenceEmpty(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UpdatesDifferenceSliceConstructorID:
		value, err := decodeUpdatesDifferenceSlice(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UpdatesDifferenceClass", constructor)
	}
}

// UpdatesStateClass is the TL union updates.State.
type UpdatesStateClass interface {
	Object
	isUpdatesStateClass()
}

// decodeUpdatesStateClass decodes the TL union updates.State.
func decodeUpdatesStateClass(input *decoder) (UpdatesStateClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UpdatesStateConstructorID:
		value, err := decodeUpdatesState(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UpdatesStateClass", constructor)
	}
}

// UpdatesDifference represents TL class updates.difference (ID 0x00f49ca0).
type UpdatesDifference struct {
	NewMessages          []MessageClass
	NewEncryptedMessages []EncryptedMessageClass
	OtherUpdates         []UpdateClass
	Chats                []ChatClass
	Users                []UserClass
	State                UpdatesStateClass
}

// UpdatesDifferenceConstructorID is the TL constructor ID for updates.difference.
const UpdatesDifferenceConstructorID uint32 = 0x00f49ca0

// ConstructorID returns the TL constructor ID.
func (*UpdatesDifference) ConstructorID() uint32 {
	return UpdatesDifferenceConstructorID
}

func (*UpdatesDifference) isUpdatesDifferenceClass() {
}

func (value *UpdatesDifference) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.difference", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesDifference) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.difference", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.NewMessages)); err != nil {
		return 0, encodeError("updates.difference", "new_messages", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.NewMessages {
		if value.NewMessages[_index0] == nil {
			return 0, encodeError("updates.difference", "new_messages", ErrNilObject)
		}
		_fieldSize1, err := value.NewMessages[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("updates.difference", "new_messages", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("updates.difference", "new_messages", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("updates.difference", "new_messages", err)
	}
	size = _totalSize0
	if err := validateVectorLength(len(value.NewEncryptedMessages)); err != nil {
		return 0, encodeError("updates.difference", "new_encrypted_messages", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.NewEncryptedMessages {
		if value.NewEncryptedMessages[_index2] == nil {
			return 0, encodeError("updates.difference", "new_encrypted_messages", ErrNilObject)
		}
		_fieldSize3, err := value.NewEncryptedMessages[_index2].encodedSize()
		if err != nil {
			return 0, encodeError("updates.difference", "new_encrypted_messages", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("updates.difference", "new_encrypted_messages", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("updates.difference", "new_encrypted_messages", err)
	}
	size = _totalSize2
	if err := validateVectorLength(len(value.OtherUpdates)); err != nil {
		return 0, encodeError("updates.difference", "other_updates", err)
	}
	_vectorSize4 := 8
	for _index4 := range value.OtherUpdates {
		if value.OtherUpdates[_index4] == nil {
			return 0, encodeError("updates.difference", "other_updates", ErrNilObject)
		}
		_fieldSize5, err := value.OtherUpdates[_index4].encodedSize()
		if err != nil {
			return 0, encodeError("updates.difference", "other_updates", err)
		}
		_vectorSize4, err = checkedEncodedSizeAdd(_vectorSize4, _fieldSize5)
		if err != nil {
			return 0, encodeError("updates.difference", "other_updates", err)
		}
	}
	_totalSize4, err := checkedEncodedSizeAdd(size, _vectorSize4)
	if err != nil {
		return 0, encodeError("updates.difference", "other_updates", err)
	}
	size = _totalSize4
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("updates.difference", "chats", err)
	}
	_vectorSize6 := 8
	for _index6 := range value.Chats {
		if value.Chats[_index6] == nil {
			return 0, encodeError("updates.difference", "chats", ErrNilObject)
		}
		_fieldSize7, err := value.Chats[_index6].encodedSize()
		if err != nil {
			return 0, encodeError("updates.difference", "chats", err)
		}
		_vectorSize6, err = checkedEncodedSizeAdd(_vectorSize6, _fieldSize7)
		if err != nil {
			return 0, encodeError("updates.difference", "chats", err)
		}
	}
	_totalSize6, err := checkedEncodedSizeAdd(size, _vectorSize6)
	if err != nil {
		return 0, encodeError("updates.difference", "chats", err)
	}
	size = _totalSize6
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("updates.difference", "users", err)
	}
	_vectorSize8 := 8
	for _index8 := range value.Users {
		if value.Users[_index8] == nil {
			return 0, encodeError("updates.difference", "users", ErrNilObject)
		}
		_fieldSize9, err := value.Users[_index8].encodedSize()
		if err != nil {
			return 0, encodeError("updates.difference", "users", err)
		}
		_vectorSize8, err = checkedEncodedSizeAdd(_vectorSize8, _fieldSize9)
		if err != nil {
			return 0, encodeError("updates.difference", "users", err)
		}
	}
	_totalSize8, err := checkedEncodedSizeAdd(size, _vectorSize8)
	if err != nil {
		return 0, encodeError("updates.difference", "users", err)
	}
	size = _totalSize8
	if value.State == nil {
		return 0, encodeError("updates.difference", "state", ErrNilObject)
	}
	_fieldSize10, err := value.State.encodedSize()
	if err != nil {
		return 0, encodeError("updates.difference", "state", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize10)
	if err != nil {
		return 0, encodeError("updates.difference", "state", err)
	}
	return size, nil
}

func (value *UpdatesDifference) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.difference", "", ErrNilObject)
	}
	output.putUint32(UpdatesDifferenceConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesDifference) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.difference", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.NewMessages)); err != nil {
		return output, encodeError("updates.difference", "new_messages", err)
	}
	for _index := range value.NewMessages {
		if value.NewMessages[_index] == nil {
			return output, encodeError("updates.difference", "new_messages", ErrNilObject)
		}
		_output0, err := value.NewMessages[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.difference", "new_messages", err)
		}
		output = _output0
	}
	if err := output.putVectorHeader(len(value.NewEncryptedMessages)); err != nil {
		return output, encodeError("updates.difference", "new_encrypted_messages", err)
	}
	for _index := range value.NewEncryptedMessages {
		if value.NewEncryptedMessages[_index] == nil {
			return output, encodeError("updates.difference", "new_encrypted_messages", ErrNilObject)
		}
		_output1, err := value.NewEncryptedMessages[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.difference", "new_encrypted_messages", err)
		}
		output = _output1
	}
	if err := output.putVectorHeader(len(value.OtherUpdates)); err != nil {
		return output, encodeError("updates.difference", "other_updates", err)
	}
	for _index := range value.OtherUpdates {
		if value.OtherUpdates[_index] == nil {
			return output, encodeError("updates.difference", "other_updates", ErrNilObject)
		}
		_output2, err := value.OtherUpdates[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.difference", "other_updates", err)
		}
		output = _output2
	}
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("updates.difference", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("updates.difference", "chats", ErrNilObject)
		}
		_output3, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.difference", "chats", err)
		}
		output = _output3
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("updates.difference", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("updates.difference", "users", ErrNilObject)
		}
		_output4, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.difference", "users", err)
		}
		output = _output4
	}
	if value.State == nil {
		return output, encodeError("updates.difference", "state", ErrNilObject)
	}
	_output5, err := value.State.encode(output)
	if err != nil {
		return output, encodeError("updates.difference", "state", err)
	}
	output = _output5
	return output, nil
}

// decodeUpdatesDifference decodes a TL updates.Difference.
func decodeUpdatesDifference(input *decoder) (*UpdatesDifference, error) {
	if err := input.reserveAllocation("updates.difference", decodedAllocationSize(68, 136)); err != nil {
		return nil, err
	}
	value := new(UpdatesDifference)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesDifference) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_count0, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.difference.new_messages", _count0, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.NewMessages = make([]MessageClass, _count0)
	for _index0 := range value.NewMessages {
		_field1, err := decodeMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.NewMessages[_index0] = _field1
	}
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.difference.new_encrypted_messages", _count2, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.NewEncryptedMessages = make([]EncryptedMessageClass, _count2)
	for _index2 := range value.NewEncryptedMessages {
		_field3, err := decodeEncryptedMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.NewEncryptedMessages[_index2] = _field3
	}
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.difference.other_updates", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.OtherUpdates = make([]UpdateClass, _count4)
	for _index4 := range value.OtherUpdates {
		_field5, err := decodeUpdateClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.OtherUpdates[_index4] = _field5
	}
	_count6, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.difference.chats", _count6, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count6)
	for _index6 := range value.Chats {
		_field7, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index6] = _field7
	}
	_count8, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.difference.users", _count8, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count8)
	for _index8 := range value.Users {
		_field9, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index8] = _field9
	}
	_field10, err := decodeUpdatesStateClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.State = _field10
	input.leave()
	return nil
}

// UpdatesGetChannelDifferenceRequest represents TL method updates.getChannelDifference (ID 0x03173d78).
type UpdatesGetChannelDifferenceRequest struct {
	Force   bool
	Channel InputChannelClass
	Filter  ChannelMessagesFilterClass
	PTS     int32
	Limit   int32
}

// UpdatesGetChannelDifferenceRequestConstructorID is the TL constructor ID for updates.getChannelDifference.
const UpdatesGetChannelDifferenceRequestConstructorID uint32 = 0x03173d78

// ConstructorID returns the TL constructor ID.
func (*UpdatesGetChannelDifferenceRequest) ConstructorID() uint32 {
	return UpdatesGetChannelDifferenceRequestConstructorID
}

func (*UpdatesGetChannelDifferenceRequest) requestResult(UpdatesChannelDifferenceClass) {}

func (value *UpdatesGetChannelDifferenceRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.getChannelDifference", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesGetChannelDifferenceRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.getChannelDifference", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Channel == nil {
		return 0, encodeError("updates.getChannelDifference", "channel", ErrNilObject)
	}
	_fieldSize0, err := value.Channel.encodedSize()
	if err != nil {
		return 0, encodeError("updates.getChannelDifference", "channel", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("updates.getChannelDifference", "channel", err)
	}
	if value.Filter == nil {
		return 0, encodeError("updates.getChannelDifference", "filter", ErrNilObject)
	}
	_fieldSize1, err := value.Filter.encodedSize()
	if err != nil {
		return 0, encodeError("updates.getChannelDifference", "filter", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("updates.getChannelDifference", "filter", err)
	}
	size += 4
	size += 4
	return size, nil
}

func (value *UpdatesGetChannelDifferenceRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.getChannelDifference", "", ErrNilObject)
	}
	output.putUint32(UpdatesGetChannelDifferenceRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesGetChannelDifferenceRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.getChannelDifference", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Force
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if value.Channel == nil {
		return output, encodeError("updates.getChannelDifference", "channel", ErrNilObject)
	}
	_output0, err := value.Channel.encode(output)
	if err != nil {
		return output, encodeError("updates.getChannelDifference", "channel", err)
	}
	output = _output0
	if value.Filter == nil {
		return output, encodeError("updates.getChannelDifference", "filter", ErrNilObject)
	}
	_output1, err := value.Filter.encode(output)
	if err != nil {
		return output, encodeError("updates.getChannelDifference", "filter", err)
	}
	output = _output1
	output.putInt32(value.PTS)
	output.putInt32(value.Limit)
	return output, nil
}

func (request *UpdatesGetChannelDifferenceRequest) decodeResult(state decoder) (UpdatesChannelDifferenceClass, decoder, error) {
	var zero UpdatesChannelDifferenceClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesChannelDifferenceClass
	_field0, err := decodeUpdatesChannelDifferenceClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UpdatesGetDifferenceRequest represents TL method updates.getDifference (ID 0x19c2f763).
type UpdatesGetDifferenceRequest struct {
	PTS           int32
	PTSLimit      *int32
	PTSTotalLimit *int32
	Date          int32
	QTS           int32
	QTSLimit      *int32
}

// UpdatesGetDifferenceRequestConstructorID is the TL constructor ID for updates.getDifference.
const UpdatesGetDifferenceRequestConstructorID uint32 = 0x19c2f763

// ConstructorID returns the TL constructor ID.
func (*UpdatesGetDifferenceRequest) ConstructorID() uint32 {
	return UpdatesGetDifferenceRequestConstructorID
}

func (*UpdatesGetDifferenceRequest) requestResult(UpdatesDifferenceClass) {}

func (value *UpdatesGetDifferenceRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.getDifference", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesGetDifferenceRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.getDifference", "", ErrNilObject)
	}
	_present0 := value.PTSLimit != nil
	_present1 := value.PTSTotalLimit != nil
	_present2 := value.QTSLimit != nil
	size := 0
	size += 4
	size += 4
	if _present0 {
		size += 4
	}
	if _present1 {
		size += 4
	}
	size += 4
	size += 4
	if _present2 {
		size += 4
	}
	return size, nil
}

func (value *UpdatesGetDifferenceRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.getDifference", "", ErrNilObject)
	}
	output.putUint32(UpdatesGetDifferenceRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesGetDifferenceRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.getDifference", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.PTSLimit != nil
	if _present0 {
		_flags0 |= uint32(1) << 1
	}
	_present1 := value.PTSTotalLimit != nil
	if _present1 {
		_flags0 |= uint32(1) << 0
	}
	_present2 := value.QTSLimit != nil
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	output.putUint32(_flags0)
	output.putInt32(value.PTS)
	if _present0 {
		output.putInt32(*value.PTSLimit)
	}
	if _present1 {
		output.putInt32(*value.PTSTotalLimit)
	}
	output.putInt32(value.Date)
	output.putInt32(value.QTS)
	if _present2 {
		output.putInt32(*value.QTSLimit)
	}
	return output, nil
}

func (request *UpdatesGetDifferenceRequest) decodeResult(state decoder) (UpdatesDifferenceClass, decoder, error) {
	var zero UpdatesDifferenceClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesDifferenceClass
	_field0, err := decodeUpdatesDifferenceClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UpdatesChannelDifference represents TL class updates.channelDifference (ID 0x2064674e).
type UpdatesChannelDifference struct {
	Final        bool
	PTS          int32
	Timeout      *int32
	NewMessages  []MessageClass
	OtherUpdates []UpdateClass
	Chats        []ChatClass
	Users        []UserClass
}

// UpdatesChannelDifferenceConstructorID is the TL constructor ID for updates.channelDifference.
const UpdatesChannelDifferenceConstructorID uint32 = 0x2064674e

// ConstructorID returns the TL constructor ID.
func (*UpdatesChannelDifference) ConstructorID() uint32 {
	return UpdatesChannelDifferenceConstructorID
}

func (*UpdatesChannelDifference) isUpdatesChannelDifferenceClass() {
}

func (value *UpdatesChannelDifference) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.channelDifference", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesChannelDifference) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.channelDifference", "", ErrNilObject)
	}
	_present1 := value.Timeout != nil
	size := 0
	size += 4
	size += 4
	if _present1 {
		size += 4
	}
	if err := validateVectorLength(len(value.NewMessages)); err != nil {
		return 0, encodeError("updates.channelDifference", "new_messages", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.NewMessages {
		if value.NewMessages[_index0] == nil {
			return 0, encodeError("updates.channelDifference", "new_messages", ErrNilObject)
		}
		_fieldSize1, err := value.NewMessages[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifference", "new_messages", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("updates.channelDifference", "new_messages", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("updates.channelDifference", "new_messages", err)
	}
	size = _totalSize0
	if err := validateVectorLength(len(value.OtherUpdates)); err != nil {
		return 0, encodeError("updates.channelDifference", "other_updates", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.OtherUpdates {
		if value.OtherUpdates[_index2] == nil {
			return 0, encodeError("updates.channelDifference", "other_updates", ErrNilObject)
		}
		_fieldSize3, err := value.OtherUpdates[_index2].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifference", "other_updates", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("updates.channelDifference", "other_updates", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("updates.channelDifference", "other_updates", err)
	}
	size = _totalSize2
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("updates.channelDifference", "chats", err)
	}
	_vectorSize4 := 8
	for _index4 := range value.Chats {
		if value.Chats[_index4] == nil {
			return 0, encodeError("updates.channelDifference", "chats", ErrNilObject)
		}
		_fieldSize5, err := value.Chats[_index4].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifference", "chats", err)
		}
		_vectorSize4, err = checkedEncodedSizeAdd(_vectorSize4, _fieldSize5)
		if err != nil {
			return 0, encodeError("updates.channelDifference", "chats", err)
		}
	}
	_totalSize4, err := checkedEncodedSizeAdd(size, _vectorSize4)
	if err != nil {
		return 0, encodeError("updates.channelDifference", "chats", err)
	}
	size = _totalSize4
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("updates.channelDifference", "users", err)
	}
	_vectorSize6 := 8
	for _index6 := range value.Users {
		if value.Users[_index6] == nil {
			return 0, encodeError("updates.channelDifference", "users", ErrNilObject)
		}
		_fieldSize7, err := value.Users[_index6].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifference", "users", err)
		}
		_vectorSize6, err = checkedEncodedSizeAdd(_vectorSize6, _fieldSize7)
		if err != nil {
			return 0, encodeError("updates.channelDifference", "users", err)
		}
	}
	_totalSize6, err := checkedEncodedSizeAdd(size, _vectorSize6)
	if err != nil {
		return 0, encodeError("updates.channelDifference", "users", err)
	}
	size = _totalSize6
	return size, nil
}

func (value *UpdatesChannelDifference) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.channelDifference", "", ErrNilObject)
	}
	output.putUint32(UpdatesChannelDifferenceConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesChannelDifference) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.channelDifference", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Final
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.Timeout != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	output.putInt32(value.PTS)
	if _present1 {
		output.putInt32(*value.Timeout)
	}
	if err := output.putVectorHeader(len(value.NewMessages)); err != nil {
		return output, encodeError("updates.channelDifference", "new_messages", err)
	}
	for _index := range value.NewMessages {
		if value.NewMessages[_index] == nil {
			return output, encodeError("updates.channelDifference", "new_messages", ErrNilObject)
		}
		_output0, err := value.NewMessages[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifference", "new_messages", err)
		}
		output = _output0
	}
	if err := output.putVectorHeader(len(value.OtherUpdates)); err != nil {
		return output, encodeError("updates.channelDifference", "other_updates", err)
	}
	for _index := range value.OtherUpdates {
		if value.OtherUpdates[_index] == nil {
			return output, encodeError("updates.channelDifference", "other_updates", ErrNilObject)
		}
		_output1, err := value.OtherUpdates[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifference", "other_updates", err)
		}
		output = _output1
	}
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("updates.channelDifference", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("updates.channelDifference", "chats", ErrNilObject)
		}
		_output2, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifference", "chats", err)
		}
		output = _output2
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("updates.channelDifference", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("updates.channelDifference", "users", ErrNilObject)
		}
		_output3, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifference", "users", err)
		}
		output = _output3
	}
	return output, nil
}

// decodeUpdatesChannelDifference decodes a TL updates.ChannelDifference.
func decodeUpdatesChannelDifference(input *decoder) (*UpdatesChannelDifference, error) {
	if err := input.reserveAllocation("updates.channelDifference", decodedAllocationSize(60, 120)); err != nil {
		return nil, err
	}
	value := new(UpdatesChannelDifference)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesChannelDifference) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Final = _flags0&(uint32(1)<<0) != 0
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.PTS = _field0
	if _flags0&(uint32(1)<<1) != 0 {
		_field1, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("updates.channelDifference.timeout", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.Timeout = &_field1
	}
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifference.new_messages", _count2, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.NewMessages = make([]MessageClass, _count2)
	for _index2 := range value.NewMessages {
		_field3, err := decodeMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.NewMessages[_index2] = _field3
	}
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifference.other_updates", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.OtherUpdates = make([]UpdateClass, _count4)
	for _index4 := range value.OtherUpdates {
		_field5, err := decodeUpdateClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.OtherUpdates[_index4] = _field5
	}
	_count6, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifference.chats", _count6, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count6)
	for _index6 := range value.Chats {
		_field7, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index6] = _field7
	}
	_count8, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifference.users", _count8, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count8)
	for _index8 := range value.Users {
		_field9, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index8] = _field9
	}
	input.leave()
	return nil
}

// UpdatesChannelDifferenceEmpty represents TL class updates.channelDifferenceEmpty (ID 0x3e11affb).
type UpdatesChannelDifferenceEmpty struct {
	Final   bool
	PTS     int32
	Timeout *int32
}

// UpdatesChannelDifferenceEmptyConstructorID is the TL constructor ID for updates.channelDifferenceEmpty.
const UpdatesChannelDifferenceEmptyConstructorID uint32 = 0x3e11affb

// ConstructorID returns the TL constructor ID.
func (*UpdatesChannelDifferenceEmpty) ConstructorID() uint32 {
	return UpdatesChannelDifferenceEmptyConstructorID
}

func (*UpdatesChannelDifferenceEmpty) isUpdatesChannelDifferenceClass() {
}

func (value *UpdatesChannelDifferenceEmpty) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.channelDifferenceEmpty", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesChannelDifferenceEmpty) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.channelDifferenceEmpty", "", ErrNilObject)
	}
	_present1 := value.Timeout != nil
	size := 0
	size += 4
	size += 4
	if _present1 {
		size += 4
	}
	return size, nil
}

func (value *UpdatesChannelDifferenceEmpty) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.channelDifferenceEmpty", "", ErrNilObject)
	}
	output.putUint32(UpdatesChannelDifferenceEmptyConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesChannelDifferenceEmpty) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.channelDifferenceEmpty", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Final
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.Timeout != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	output.putInt32(value.PTS)
	if _present1 {
		output.putInt32(*value.Timeout)
	}
	return output, nil
}

// decodeUpdatesChannelDifferenceEmpty decodes a TL updates.ChannelDifference.
func decodeUpdatesChannelDifferenceEmpty(input *decoder) (*UpdatesChannelDifferenceEmpty, error) {
	if err := input.reserveAllocation("updates.channelDifferenceEmpty", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(UpdatesChannelDifferenceEmpty)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesChannelDifferenceEmpty) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Final = _flags0&(uint32(1)<<0) != 0
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.PTS = _field0
	if _flags0&(uint32(1)<<1) != 0 {
		_field1, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("updates.channelDifferenceEmpty.timeout", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.Timeout = &_field1
	}
	input.leave()
	return nil
}

// UpdatesDifferenceTooLong represents TL class updates.differenceTooLong (ID 0x4afe8f6d).
type UpdatesDifferenceTooLong struct {
	PTS int32
}

// UpdatesDifferenceTooLongConstructorID is the TL constructor ID for updates.differenceTooLong.
const UpdatesDifferenceTooLongConstructorID uint32 = 0x4afe8f6d

// ConstructorID returns the TL constructor ID.
func (*UpdatesDifferenceTooLong) ConstructorID() uint32 {
	return UpdatesDifferenceTooLongConstructorID
}

func (*UpdatesDifferenceTooLong) isUpdatesDifferenceClass() {
}

func (value *UpdatesDifferenceTooLong) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.differenceTooLong", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesDifferenceTooLong) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.differenceTooLong", "", ErrNilObject)
	}
	size := 0
	size += 4
	return size, nil
}

func (value *UpdatesDifferenceTooLong) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.differenceTooLong", "", ErrNilObject)
	}
	output.putUint32(UpdatesDifferenceTooLongConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesDifferenceTooLong) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.differenceTooLong", "", ErrNilObject)
	}
	output.putInt32(value.PTS)
	return output, nil
}

// decodeUpdatesDifferenceTooLong decodes a TL updates.Difference.
func decodeUpdatesDifferenceTooLong(input *decoder) (*UpdatesDifferenceTooLong, error) {
	if err := input.reserveAllocation("updates.differenceTooLong", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(UpdatesDifferenceTooLong)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesDifferenceTooLong) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.PTS = _field0
	input.leave()
	return nil
}

// UpdatesDifferenceEmpty represents TL class updates.differenceEmpty (ID 0x5d75a138).
type UpdatesDifferenceEmpty struct {
	Date int32
	Seq  int32
}

// UpdatesDifferenceEmptyConstructorID is the TL constructor ID for updates.differenceEmpty.
const UpdatesDifferenceEmptyConstructorID uint32 = 0x5d75a138

// ConstructorID returns the TL constructor ID.
func (*UpdatesDifferenceEmpty) ConstructorID() uint32 {
	return UpdatesDifferenceEmptyConstructorID
}

func (*UpdatesDifferenceEmpty) isUpdatesDifferenceClass() {
}

func (value *UpdatesDifferenceEmpty) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.differenceEmpty", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesDifferenceEmpty) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.differenceEmpty", "", ErrNilObject)
	}
	size := 0
	size += 4
	size += 4
	return size, nil
}

func (value *UpdatesDifferenceEmpty) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.differenceEmpty", "", ErrNilObject)
	}
	output.putUint32(UpdatesDifferenceEmptyConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesDifferenceEmpty) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.differenceEmpty", "", ErrNilObject)
	}
	output.putInt32(value.Date)
	output.putInt32(value.Seq)
	return output, nil
}

// decodeUpdatesDifferenceEmpty decodes a TL updates.Difference.
func decodeUpdatesDifferenceEmpty(input *decoder) (*UpdatesDifferenceEmpty, error) {
	if err := input.reserveAllocation("updates.differenceEmpty", decodedAllocationSize(8, 16)); err != nil {
		return nil, err
	}
	value := new(UpdatesDifferenceEmpty)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesDifferenceEmpty) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Date = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Seq = _field1
	input.leave()
	return nil
}

// UpdatesChannelDifferenceTooLong represents TL class updates.channelDifferenceTooLong (ID 0xa4bcc6fe).
type UpdatesChannelDifferenceTooLong struct {
	Final    bool
	Timeout  *int32
	Dialog   DialogClass
	Messages []MessageClass
	Chats    []ChatClass
	Users    []UserClass
}

// UpdatesChannelDifferenceTooLongConstructorID is the TL constructor ID for updates.channelDifferenceTooLong.
const UpdatesChannelDifferenceTooLongConstructorID uint32 = 0xa4bcc6fe

// ConstructorID returns the TL constructor ID.
func (*UpdatesChannelDifferenceTooLong) ConstructorID() uint32 {
	return UpdatesChannelDifferenceTooLongConstructorID
}

func (*UpdatesChannelDifferenceTooLong) isUpdatesChannelDifferenceClass() {
}

func (value *UpdatesChannelDifferenceTooLong) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesChannelDifferenceTooLong) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "", ErrNilObject)
	}
	_present1 := value.Timeout != nil
	size := 0
	size += 4
	if _present1 {
		size += 4
	}
	if value.Dialog == nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "dialog", ErrNilObject)
	}
	_fieldSize0, err := value.Dialog.encodedSize()
	if err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "dialog", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "dialog", err)
	}
	if err := validateVectorLength(len(value.Messages)); err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "messages", err)
	}
	_vectorSize1 := 8
	for _index1 := range value.Messages {
		if value.Messages[_index1] == nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "messages", ErrNilObject)
		}
		_fieldSize2, err := value.Messages[_index1].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "messages", err)
		}
		_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _fieldSize2)
		if err != nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "messages", err)
		}
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "messages", err)
	}
	size = _totalSize1
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "chats", err)
	}
	_vectorSize3 := 8
	for _index3 := range value.Chats {
		if value.Chats[_index3] == nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "chats", ErrNilObject)
		}
		_fieldSize4, err := value.Chats[_index3].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "chats", err)
		}
		_vectorSize3, err = checkedEncodedSizeAdd(_vectorSize3, _fieldSize4)
		if err != nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "chats", err)
		}
	}
	_totalSize3, err := checkedEncodedSizeAdd(size, _vectorSize3)
	if err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "chats", err)
	}
	size = _totalSize3
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "users", err)
	}
	_vectorSize5 := 8
	for _index5 := range value.Users {
		if value.Users[_index5] == nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "users", ErrNilObject)
		}
		_fieldSize6, err := value.Users[_index5].encodedSize()
		if err != nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "users", err)
		}
		_vectorSize5, err = checkedEncodedSizeAdd(_vectorSize5, _fieldSize6)
		if err != nil {
			return 0, encodeError("updates.channelDifferenceTooLong", "users", err)
		}
	}
	_totalSize5, err := checkedEncodedSizeAdd(size, _vectorSize5)
	if err != nil {
		return 0, encodeError("updates.channelDifferenceTooLong", "users", err)
	}
	size = _totalSize5
	return size, nil
}

func (value *UpdatesChannelDifferenceTooLong) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.channelDifferenceTooLong", "", ErrNilObject)
	}
	output.putUint32(UpdatesChannelDifferenceTooLongConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesChannelDifferenceTooLong) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.channelDifferenceTooLong", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Final
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.Timeout != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	if _present1 {
		output.putInt32(*value.Timeout)
	}
	if value.Dialog == nil {
		return output, encodeError("updates.channelDifferenceTooLong", "dialog", ErrNilObject)
	}
	_output0, err := value.Dialog.encode(output)
	if err != nil {
		return output, encodeError("updates.channelDifferenceTooLong", "dialog", err)
	}
	output = _output0
	if err := output.putVectorHeader(len(value.Messages)); err != nil {
		return output, encodeError("updates.channelDifferenceTooLong", "messages", err)
	}
	for _index := range value.Messages {
		if value.Messages[_index] == nil {
			return output, encodeError("updates.channelDifferenceTooLong", "messages", ErrNilObject)
		}
		_output1, err := value.Messages[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifferenceTooLong", "messages", err)
		}
		output = _output1
	}
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("updates.channelDifferenceTooLong", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("updates.channelDifferenceTooLong", "chats", ErrNilObject)
		}
		_output2, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifferenceTooLong", "chats", err)
		}
		output = _output2
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("updates.channelDifferenceTooLong", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("updates.channelDifferenceTooLong", "users", ErrNilObject)
		}
		_output3, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.channelDifferenceTooLong", "users", err)
		}
		output = _output3
	}
	return output, nil
}

// decodeUpdatesChannelDifferenceTooLong decodes a TL updates.ChannelDifference.
func decodeUpdatesChannelDifferenceTooLong(input *decoder) (*UpdatesChannelDifferenceTooLong, error) {
	if err := input.reserveAllocation("updates.channelDifferenceTooLong", decodedAllocationSize(52, 104)); err != nil {
		return nil, err
	}
	value := new(UpdatesChannelDifferenceTooLong)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesChannelDifferenceTooLong) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Final = _flags0&(uint32(1)<<0) != 0
	if _flags0&(uint32(1)<<1) != 0 {
		_field0, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("updates.channelDifferenceTooLong.timeout", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.Timeout = &_field0
	}
	_field1, err := decodeDialogClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.Dialog = _field1
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifferenceTooLong.messages", _count2, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Messages = make([]MessageClass, _count2)
	for _index2 := range value.Messages {
		_field3, err := decodeMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Messages[_index2] = _field3
	}
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifferenceTooLong.chats", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count4)
	for _index4 := range value.Chats {
		_field5, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index4] = _field5
	}
	_count6, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.channelDifferenceTooLong.users", _count6, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count6)
	for _index6 := range value.Users {
		_field7, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index6] = _field7
	}
	input.leave()
	return nil
}

// UpdatesState represents TL class updates.state (ID 0xa56c2a3e).
type UpdatesState struct {
	PTS         int32
	QTS         int32
	Date        int32
	Seq         int32
	UnreadCount int32
}

// UpdatesStateConstructorID is the TL constructor ID for updates.state.
const UpdatesStateConstructorID uint32 = 0xa56c2a3e

// ConstructorID returns the TL constructor ID.
func (*UpdatesState) ConstructorID() uint32 {
	return UpdatesStateConstructorID
}

func (*UpdatesState) isUpdatesStateClass() {
}

func (value *UpdatesState) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.state", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesState) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.state", "", ErrNilObject)
	}
	size := 0
	size += 4
	size += 4
	size += 4
	size += 4
	size += 4
	return size, nil
}

func (value *UpdatesState) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.state", "", ErrNilObject)
	}
	output.putUint32(UpdatesStateConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesState) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.state", "", ErrNilObject)
	}
	output.putInt32(value.PTS)
	output.putInt32(value.QTS)
	output.putInt32(value.Date)
	output.putInt32(value.Seq)
	output.putInt32(value.UnreadCount)
	return output, nil
}

// decodeUpdatesState decodes a TL updates.State.
func decodeUpdatesState(input *decoder) (*UpdatesState, error) {
	if err := input.reserveAllocation("updates.state", decodedAllocationSize(20, 40)); err != nil {
		return nil, err
	}
	value := new(UpdatesState)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesState) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.PTS = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.QTS = _field1
	_field2, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Date = _field2
	_field3, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Seq = _field3
	_field4, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.UnreadCount = _field4
	input.leave()
	return nil
}

// UpdatesDifferenceSlice represents TL class updates.differenceSlice (ID 0xa8fb1981).
type UpdatesDifferenceSlice struct {
	NewMessages          []MessageClass
	NewEncryptedMessages []EncryptedMessageClass
	OtherUpdates         []UpdateClass
	Chats                []ChatClass
	Users                []UserClass
	IntermediateState    UpdatesStateClass
}

// UpdatesDifferenceSliceConstructorID is the TL constructor ID for updates.differenceSlice.
const UpdatesDifferenceSliceConstructorID uint32 = 0xa8fb1981

// ConstructorID returns the TL constructor ID.
func (*UpdatesDifferenceSlice) ConstructorID() uint32 {
	return UpdatesDifferenceSliceConstructorID
}

func (*UpdatesDifferenceSlice) isUpdatesDifferenceClass() {
}

func (value *UpdatesDifferenceSlice) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.differenceSlice", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesDifferenceSlice) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.differenceSlice", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.NewMessages)); err != nil {
		return 0, encodeError("updates.differenceSlice", "new_messages", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.NewMessages {
		if value.NewMessages[_index0] == nil {
			return 0, encodeError("updates.differenceSlice", "new_messages", ErrNilObject)
		}
		_fieldSize1, err := value.NewMessages[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "new_messages", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "new_messages", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "new_messages", err)
	}
	size = _totalSize0
	if err := validateVectorLength(len(value.NewEncryptedMessages)); err != nil {
		return 0, encodeError("updates.differenceSlice", "new_encrypted_messages", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.NewEncryptedMessages {
		if value.NewEncryptedMessages[_index2] == nil {
			return 0, encodeError("updates.differenceSlice", "new_encrypted_messages", ErrNilObject)
		}
		_fieldSize3, err := value.NewEncryptedMessages[_index2].encodedSize()
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "new_encrypted_messages", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "new_encrypted_messages", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "new_encrypted_messages", err)
	}
	size = _totalSize2
	if err := validateVectorLength(len(value.OtherUpdates)); err != nil {
		return 0, encodeError("updates.differenceSlice", "other_updates", err)
	}
	_vectorSize4 := 8
	for _index4 := range value.OtherUpdates {
		if value.OtherUpdates[_index4] == nil {
			return 0, encodeError("updates.differenceSlice", "other_updates", ErrNilObject)
		}
		_fieldSize5, err := value.OtherUpdates[_index4].encodedSize()
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "other_updates", err)
		}
		_vectorSize4, err = checkedEncodedSizeAdd(_vectorSize4, _fieldSize5)
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "other_updates", err)
		}
	}
	_totalSize4, err := checkedEncodedSizeAdd(size, _vectorSize4)
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "other_updates", err)
	}
	size = _totalSize4
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("updates.differenceSlice", "chats", err)
	}
	_vectorSize6 := 8
	for _index6 := range value.Chats {
		if value.Chats[_index6] == nil {
			return 0, encodeError("updates.differenceSlice", "chats", ErrNilObject)
		}
		_fieldSize7, err := value.Chats[_index6].encodedSize()
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "chats", err)
		}
		_vectorSize6, err = checkedEncodedSizeAdd(_vectorSize6, _fieldSize7)
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "chats", err)
		}
	}
	_totalSize6, err := checkedEncodedSizeAdd(size, _vectorSize6)
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "chats", err)
	}
	size = _totalSize6
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("updates.differenceSlice", "users", err)
	}
	_vectorSize8 := 8
	for _index8 := range value.Users {
		if value.Users[_index8] == nil {
			return 0, encodeError("updates.differenceSlice", "users", ErrNilObject)
		}
		_fieldSize9, err := value.Users[_index8].encodedSize()
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "users", err)
		}
		_vectorSize8, err = checkedEncodedSizeAdd(_vectorSize8, _fieldSize9)
		if err != nil {
			return 0, encodeError("updates.differenceSlice", "users", err)
		}
	}
	_totalSize8, err := checkedEncodedSizeAdd(size, _vectorSize8)
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "users", err)
	}
	size = _totalSize8
	if value.IntermediateState == nil {
		return 0, encodeError("updates.differenceSlice", "intermediate_state", ErrNilObject)
	}
	_fieldSize10, err := value.IntermediateState.encodedSize()
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "intermediate_state", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize10)
	if err != nil {
		return 0, encodeError("updates.differenceSlice", "intermediate_state", err)
	}
	return size, nil
}

func (value *UpdatesDifferenceSlice) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.differenceSlice", "", ErrNilObject)
	}
	output.putUint32(UpdatesDifferenceSliceConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesDifferenceSlice) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.differenceSlice", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.NewMessages)); err != nil {
		return output, encodeError("updates.differenceSlice", "new_messages", err)
	}
	for _index := range value.NewMessages {
		if value.NewMessages[_index] == nil {
			return output, encodeError("updates.differenceSlice", "new_messages", ErrNilObject)
		}
		_output0, err := value.NewMessages[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.differenceSlice", "new_messages", err)
		}
		output = _output0
	}
	if err := output.putVectorHeader(len(value.NewEncryptedMessages)); err != nil {
		return output, encodeError("updates.differenceSlice", "new_encrypted_messages", err)
	}
	for _index := range value.NewEncryptedMessages {
		if value.NewEncryptedMessages[_index] == nil {
			return output, encodeError("updates.differenceSlice", "new_encrypted_messages", ErrNilObject)
		}
		_output1, err := value.NewEncryptedMessages[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.differenceSlice", "new_encrypted_messages", err)
		}
		output = _output1
	}
	if err := output.putVectorHeader(len(value.OtherUpdates)); err != nil {
		return output, encodeError("updates.differenceSlice", "other_updates", err)
	}
	for _index := range value.OtherUpdates {
		if value.OtherUpdates[_index] == nil {
			return output, encodeError("updates.differenceSlice", "other_updates", ErrNilObject)
		}
		_output2, err := value.OtherUpdates[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.differenceSlice", "other_updates", err)
		}
		output = _output2
	}
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("updates.differenceSlice", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("updates.differenceSlice", "chats", ErrNilObject)
		}
		_output3, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.differenceSlice", "chats", err)
		}
		output = _output3
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("updates.differenceSlice", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("updates.differenceSlice", "users", ErrNilObject)
		}
		_output4, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("updates.differenceSlice", "users", err)
		}
		output = _output4
	}
	if value.IntermediateState == nil {
		return output, encodeError("updates.differenceSlice", "intermediate_state", ErrNilObject)
	}
	_output5, err := value.IntermediateState.encode(output)
	if err != nil {
		return output, encodeError("updates.differenceSlice", "intermediate_state", err)
	}
	output = _output5
	return output, nil
}

// decodeUpdatesDifferenceSlice decodes a TL updates.Difference.
func decodeUpdatesDifferenceSlice(input *decoder) (*UpdatesDifferenceSlice, error) {
	if err := input.reserveAllocation("updates.differenceSlice", decodedAllocationSize(68, 136)); err != nil {
		return nil, err
	}
	value := new(UpdatesDifferenceSlice)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UpdatesDifferenceSlice) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_count0, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.differenceSlice.new_messages", _count0, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.NewMessages = make([]MessageClass, _count0)
	for _index0 := range value.NewMessages {
		_field1, err := decodeMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.NewMessages[_index0] = _field1
	}
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.differenceSlice.new_encrypted_messages", _count2, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.NewEncryptedMessages = make([]EncryptedMessageClass, _count2)
	for _index2 := range value.NewEncryptedMessages {
		_field3, err := decodeEncryptedMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.NewEncryptedMessages[_index2] = _field3
	}
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.differenceSlice.other_updates", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.OtherUpdates = make([]UpdateClass, _count4)
	for _index4 := range value.OtherUpdates {
		_field5, err := decodeUpdateClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.OtherUpdates[_index4] = _field5
	}
	_count6, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.differenceSlice.chats", _count6, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count6)
	for _index6 := range value.Chats {
		_field7, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index6] = _field7
	}
	_count8, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("updates.differenceSlice.users", _count8, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count8)
	for _index8 := range value.Users {
		_field9, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index8] = _field9
	}
	_field10, err := decodeUpdatesStateClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.IntermediateState = _field10
	input.leave()
	return nil
}

// UpdatesGetStateRequest represents TL method updates.getState (ID 0xedd4882a).
type UpdatesGetStateRequest struct {
}

// UpdatesGetStateRequestConstructorID is the TL constructor ID for updates.getState.
const UpdatesGetStateRequestConstructorID uint32 = 0xedd4882a

// ConstructorID returns the TL constructor ID.
func (*UpdatesGetStateRequest) ConstructorID() uint32 {
	return UpdatesGetStateRequestConstructorID
}

func (*UpdatesGetStateRequest) requestResult(*UpdatesState) {}

func (value *UpdatesGetStateRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.getState", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UpdatesGetStateRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("updates.getState", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *UpdatesGetStateRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.getState", "", ErrNilObject)
	}
	output.putUint32(UpdatesGetStateRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UpdatesGetStateRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("updates.getState", "", ErrNilObject)
	}
	return output, nil
}

func (request *UpdatesGetStateRequest) decodeResult(state decoder) (*UpdatesState, decoder, error) {
	var zero *UpdatesState
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *UpdatesState
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0xa56c2a3e {
		err := input.unexpectedConstructor(_start0, "UpdatesState", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("updates.getState.result", decodedAllocationSize(20, 40)); err != nil {
		return zero, state, err
	}
	_field1 := new(UpdatesState)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}
