// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// SmsjobsEligibilityToJoinClass is the TL union smsjobs.EligibilityToJoin.
type SmsjobsEligibilityToJoinClass interface {
	Object
	isSmsjobsEligibilityToJoinClass()
}

// decodeSmsjobsEligibilityToJoinClass decodes the TL union smsjobs.EligibilityToJoin.
func decodeSmsjobsEligibilityToJoinClass(input *decoder) (SmsjobsEligibilityToJoinClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case SmsjobsEligibleToJoinConstructorID:
		value, err := decodeSmsjobsEligibleToJoin(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "SmsjobsEligibilityToJoinClass", constructor)
	}
}

// SmsjobsStatusClass is the TL union smsjobs.Status.
type SmsjobsStatusClass interface {
	Object
	isSmsjobsStatusClass()
}

// decodeSmsjobsStatusClass decodes the TL union smsjobs.Status.
func decodeSmsjobsStatusClass(input *decoder) (SmsjobsStatusClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case SmsjobsStatusConstructorID:
		value, err := decodeSmsjobsStatus(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "SmsjobsStatusClass", constructor)
	}
}

// SmsjobsUpdateSettingsRequest represents TL method smsjobs.updateSettings (ID 0x093fa0bf).
type SmsjobsUpdateSettingsRequest struct {
	AllowInternational bool
}

// SmsjobsUpdateSettingsRequestConstructorID is the TL constructor ID for smsjobs.updateSettings.
const SmsjobsUpdateSettingsRequestConstructorID uint32 = 0x093fa0bf

// ConstructorID returns the TL constructor ID.
func (*SmsjobsUpdateSettingsRequest) ConstructorID() uint32 {
	return SmsjobsUpdateSettingsRequestConstructorID
}

func (*SmsjobsUpdateSettingsRequest) requestResult(bool) {}

func (value *SmsjobsUpdateSettingsRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.updateSettings", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsUpdateSettingsRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.updateSettings", "", ErrNilObject)
	}
	size := 0
	size += 4
	return size, nil
}

func (value *SmsjobsUpdateSettingsRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.updateSettings", "", ErrNilObject)
	}
	output.putUint32(SmsjobsUpdateSettingsRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsUpdateSettingsRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.updateSettings", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.AllowInternational
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	return output, nil
}

func (request *SmsjobsUpdateSettingsRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// SmsjobsIsEligibleToJoinRequest represents TL method smsjobs.isEligibleToJoin (ID 0x0edc39d0).
type SmsjobsIsEligibleToJoinRequest struct {
}

// SmsjobsIsEligibleToJoinRequestConstructorID is the TL constructor ID for smsjobs.isEligibleToJoin.
const SmsjobsIsEligibleToJoinRequestConstructorID uint32 = 0x0edc39d0

// ConstructorID returns the TL constructor ID.
func (*SmsjobsIsEligibleToJoinRequest) ConstructorID() uint32 {
	return SmsjobsIsEligibleToJoinRequestConstructorID
}

func (*SmsjobsIsEligibleToJoinRequest) requestResult(*SmsjobsEligibleToJoin) {}

func (value *SmsjobsIsEligibleToJoinRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.isEligibleToJoin", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsIsEligibleToJoinRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.isEligibleToJoin", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *SmsjobsIsEligibleToJoinRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.isEligibleToJoin", "", ErrNilObject)
	}
	output.putUint32(SmsjobsIsEligibleToJoinRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsIsEligibleToJoinRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.isEligibleToJoin", "", ErrNilObject)
	}
	return output, nil
}

func (request *SmsjobsIsEligibleToJoinRequest) decodeResult(state decoder) (*SmsjobsEligibleToJoin, decoder, error) {
	var zero *SmsjobsEligibleToJoin
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *SmsjobsEligibleToJoin
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0xdc8b44cf {
		err := input.unexpectedConstructor(_start0, "SmsjobsEligibleToJoin", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("smsjobs.isEligibleToJoin.result", decodedAllocationSize(12, 24)); err != nil {
		return zero, state, err
	}
	_field1 := new(SmsjobsEligibleToJoin)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// SmsjobsGetStatusRequest represents TL method smsjobs.getStatus (ID 0x10a698e8).
type SmsjobsGetStatusRequest struct {
}

// SmsjobsGetStatusRequestConstructorID is the TL constructor ID for smsjobs.getStatus.
const SmsjobsGetStatusRequestConstructorID uint32 = 0x10a698e8

// ConstructorID returns the TL constructor ID.
func (*SmsjobsGetStatusRequest) ConstructorID() uint32 {
	return SmsjobsGetStatusRequestConstructorID
}

func (*SmsjobsGetStatusRequest) requestResult(*SmsjobsStatus) {}

func (value *SmsjobsGetStatusRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.getStatus", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsGetStatusRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.getStatus", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *SmsjobsGetStatusRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.getStatus", "", ErrNilObject)
	}
	output.putUint32(SmsjobsGetStatusRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsGetStatusRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.getStatus", "", ErrNilObject)
	}
	return output, nil
}

func (request *SmsjobsGetStatusRequest) decodeResult(state decoder) (*SmsjobsStatus, decoder, error) {
	var zero *SmsjobsStatus
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *SmsjobsStatus
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0x2aee9191 {
		err := input.unexpectedConstructor(_start0, "SmsjobsStatus", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("smsjobs.getStatus.result", decodedAllocationSize(36, 72)); err != nil {
		return zero, state, err
	}
	_field1 := new(SmsjobsStatus)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// SmsjobsStatus represents TL class smsjobs.status (ID 0x2aee9191).
type SmsjobsStatus struct {
	AllowInternational bool
	RecentSent         int32
	RecentSince        int32
	RecentRemains      int32
	TotalSent          int32
	TotalSince         int32
	LastGiftSlug       *string
	TermsURL           string
}

// SmsjobsStatusConstructorID is the TL constructor ID for smsjobs.status.
const SmsjobsStatusConstructorID uint32 = 0x2aee9191

// ConstructorID returns the TL constructor ID.
func (*SmsjobsStatus) ConstructorID() uint32 {
	return SmsjobsStatusConstructorID
}

func (*SmsjobsStatus) isSmsjobsStatusClass() {
}

func (value *SmsjobsStatus) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.status", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsStatus) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.status", "", ErrNilObject)
	}
	_present1 := value.LastGiftSlug != nil
	size := 0
	size += 4
	size += 4
	size += 4
	size += 4
	size += 4
	size += 4
	if _present1 {
		_fieldSize0, err := bytesEncodedSize(len(*value.LastGiftSlug))
		if err != nil {
			return 0, encodeError("smsjobs.status", "last_gift_slug", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("smsjobs.status", "last_gift_slug", err)
		}
	}
	_fieldSize1, err := bytesEncodedSize(len(value.TermsURL))
	if err != nil {
		return 0, encodeError("smsjobs.status", "terms_url", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("smsjobs.status", "terms_url", err)
	}
	return size, nil
}

func (value *SmsjobsStatus) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.status", "", ErrNilObject)
	}
	output.putUint32(SmsjobsStatusConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsStatus) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.status", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.AllowInternational
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.LastGiftSlug != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	output.putInt32(value.RecentSent)
	output.putInt32(value.RecentSince)
	output.putInt32(value.RecentRemains)
	output.putInt32(value.TotalSent)
	output.putInt32(value.TotalSince)
	if _present1 {
		if err := output.putString(*value.LastGiftSlug); err != nil {
			return output, encodeError("smsjobs.status", "last_gift_slug", err)
		}
	}
	if err := output.putString(value.TermsURL); err != nil {
		return output, encodeError("smsjobs.status", "terms_url", err)
	}
	return output, nil
}

// decodeSmsjobsStatus decodes a TL smsjobs.Status.
func decodeSmsjobsStatus(input *decoder) (*SmsjobsStatus, error) {
	if err := input.reserveAllocation("smsjobs.status", decodedAllocationSize(36, 72)); err != nil {
		return nil, err
	}
	value := new(SmsjobsStatus)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *SmsjobsStatus) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.AllowInternational = _flags0&(uint32(1)<<0) != 0
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.RecentSent = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.RecentSince = _field1
	_field2, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.RecentRemains = _field2
	_field3, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.TotalSent = _field3
	_field4, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.TotalSince = _field4
	if _flags0&(uint32(1)<<1) != 0 {
		_field5, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("smsjobs.status.last_gift_slug", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.LastGiftSlug = &_field5
	}
	_field6, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.TermsURL = _field6
	input.leave()
	return nil
}

// SmsjobsFinishJobRequest represents TL method smsjobs.finishJob (ID 0x4f1ebf24).
type SmsjobsFinishJobRequest struct {
	JobID string
	Error *string
}

// SmsjobsFinishJobRequestConstructorID is the TL constructor ID for smsjobs.finishJob.
const SmsjobsFinishJobRequestConstructorID uint32 = 0x4f1ebf24

// ConstructorID returns the TL constructor ID.
func (*SmsjobsFinishJobRequest) ConstructorID() uint32 {
	return SmsjobsFinishJobRequestConstructorID
}

func (*SmsjobsFinishJobRequest) requestResult(bool) {}

func (value *SmsjobsFinishJobRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.finishJob", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsFinishJobRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.finishJob", "", ErrNilObject)
	}
	_present0 := value.Error != nil
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.JobID))
	if err != nil {
		return 0, encodeError("smsjobs.finishJob", "job_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("smsjobs.finishJob", "job_id", err)
	}
	if _present0 {
		_fieldSize1, err := bytesEncodedSize(len(*value.Error))
		if err != nil {
			return 0, encodeError("smsjobs.finishJob", "error", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("smsjobs.finishJob", "error", err)
		}
	}
	return size, nil
}

func (value *SmsjobsFinishJobRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.finishJob", "", ErrNilObject)
	}
	output.putUint32(SmsjobsFinishJobRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsFinishJobRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.finishJob", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Error != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if err := output.putString(value.JobID); err != nil {
		return output, encodeError("smsjobs.finishJob", "job_id", err)
	}
	if _present0 {
		if err := output.putString(*value.Error); err != nil {
			return output, encodeError("smsjobs.finishJob", "error", err)
		}
	}
	return output, nil
}

func (request *SmsjobsFinishJobRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// SmsjobsGetSMSJobRequest represents TL method smsjobs.getSmsJob (ID 0x778d902f).
type SmsjobsGetSMSJobRequest struct {
	JobID string
}

// SmsjobsGetSMSJobRequestConstructorID is the TL constructor ID for smsjobs.getSmsJob.
const SmsjobsGetSMSJobRequestConstructorID uint32 = 0x778d902f

// ConstructorID returns the TL constructor ID.
func (*SmsjobsGetSMSJobRequest) ConstructorID() uint32 {
	return SmsjobsGetSMSJobRequestConstructorID
}

func (*SmsjobsGetSMSJobRequest) requestResult(*SMSJob) {}

func (value *SmsjobsGetSMSJobRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.getSmsJob", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsGetSMSJobRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.getSmsJob", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.JobID))
	if err != nil {
		return 0, encodeError("smsjobs.getSmsJob", "job_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("smsjobs.getSmsJob", "job_id", err)
	}
	return size, nil
}

func (value *SmsjobsGetSMSJobRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.getSmsJob", "", ErrNilObject)
	}
	output.putUint32(SmsjobsGetSMSJobRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsGetSMSJobRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.getSmsJob", "", ErrNilObject)
	}
	if err := output.putString(value.JobID); err != nil {
		return output, encodeError("smsjobs.getSmsJob", "job_id", err)
	}
	return output, nil
}

func (request *SmsjobsGetSMSJobRequest) decodeResult(state decoder) (*SMSJob, decoder, error) {
	var zero *SMSJob
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *SMSJob
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0xe6a1eeb8 {
		err := input.unexpectedConstructor(_start0, "SMSJob", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("smsjobs.getSmsJob.result", decodedAllocationSize(24, 48)); err != nil {
		return zero, state, err
	}
	_field1 := new(SMSJob)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// SmsjobsLeaveRequest represents TL method smsjobs.leave (ID 0x9898ad73).
type SmsjobsLeaveRequest struct {
}

// SmsjobsLeaveRequestConstructorID is the TL constructor ID for smsjobs.leave.
const SmsjobsLeaveRequestConstructorID uint32 = 0x9898ad73

// ConstructorID returns the TL constructor ID.
func (*SmsjobsLeaveRequest) ConstructorID() uint32 {
	return SmsjobsLeaveRequestConstructorID
}

func (*SmsjobsLeaveRequest) requestResult(bool) {}

func (value *SmsjobsLeaveRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.leave", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsLeaveRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.leave", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *SmsjobsLeaveRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.leave", "", ErrNilObject)
	}
	output.putUint32(SmsjobsLeaveRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsLeaveRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.leave", "", ErrNilObject)
	}
	return output, nil
}

func (request *SmsjobsLeaveRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// SmsjobsJoinRequest represents TL method smsjobs.join (ID 0xa74ece2d).
type SmsjobsJoinRequest struct {
}

// SmsjobsJoinRequestConstructorID is the TL constructor ID for smsjobs.join.
const SmsjobsJoinRequestConstructorID uint32 = 0xa74ece2d

// ConstructorID returns the TL constructor ID.
func (*SmsjobsJoinRequest) ConstructorID() uint32 {
	return SmsjobsJoinRequestConstructorID
}

func (*SmsjobsJoinRequest) requestResult(bool) {}

func (value *SmsjobsJoinRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.join", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsJoinRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.join", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *SmsjobsJoinRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.join", "", ErrNilObject)
	}
	output.putUint32(SmsjobsJoinRequestConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsJoinRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.join", "", ErrNilObject)
	}
	return output, nil
}

func (request *SmsjobsJoinRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// SmsjobsEligibleToJoin represents TL class smsjobs.eligibleToJoin (ID 0xdc8b44cf).
type SmsjobsEligibleToJoin struct {
	TermsURL       string
	MonthlySentSMS int32
}

// SmsjobsEligibleToJoinConstructorID is the TL constructor ID for smsjobs.eligibleToJoin.
const SmsjobsEligibleToJoinConstructorID uint32 = 0xdc8b44cf

// ConstructorID returns the TL constructor ID.
func (*SmsjobsEligibleToJoin) ConstructorID() uint32 {
	return SmsjobsEligibleToJoinConstructorID
}

func (*SmsjobsEligibleToJoin) isSmsjobsEligibilityToJoinClass() {
}

func (value *SmsjobsEligibleToJoin) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.eligibleToJoin", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *SmsjobsEligibleToJoin) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("smsjobs.eligibleToJoin", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.TermsURL))
	if err != nil {
		return 0, encodeError("smsjobs.eligibleToJoin", "terms_url", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("smsjobs.eligibleToJoin", "terms_url", err)
	}
	size += 4
	return size, nil
}

func (value *SmsjobsEligibleToJoin) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.eligibleToJoin", "", ErrNilObject)
	}
	output.putUint32(SmsjobsEligibleToJoinConstructorID)
	return value.encodeBody(output)
}

func (value *SmsjobsEligibleToJoin) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("smsjobs.eligibleToJoin", "", ErrNilObject)
	}
	if err := output.putString(value.TermsURL); err != nil {
		return output, encodeError("smsjobs.eligibleToJoin", "terms_url", err)
	}
	output.putInt32(value.MonthlySentSMS)
	return output, nil
}

// decodeSmsjobsEligibleToJoin decodes a TL smsjobs.EligibilityToJoin.
func decodeSmsjobsEligibleToJoin(input *decoder) (*SmsjobsEligibleToJoin, error) {
	if err := input.reserveAllocation("smsjobs.eligibleToJoin", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(SmsjobsEligibleToJoin)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *SmsjobsEligibleToJoin) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.TermsURL = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.MonthlySentSMS = _field1
	input.leave()
	return nil
}
