// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// CommunitiesParticipantJoinedChatsClass is the TL union communities.ParticipantJoinedChats.
type CommunitiesParticipantJoinedChatsClass interface {
	Object
	isCommunitiesParticipantJoinedChatsClass()
}

// decodeCommunitiesParticipantJoinedChatsClass decodes the TL union communities.ParticipantJoinedChats.
func decodeCommunitiesParticipantJoinedChatsClass(input *decoder) (CommunitiesParticipantJoinedChatsClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case CommunitiesParticipantJoinedChatsConstructorID:
		value, err := decodeCommunitiesParticipantJoinedChats(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "CommunitiesParticipantJoinedChatsClass", constructor)
	}
}

// CommunitiesPeerLinkRequestsClass is the TL union communities.PeerLinkRequests.
type CommunitiesPeerLinkRequestsClass interface {
	Object
	isCommunitiesPeerLinkRequestsClass()
}

// decodeCommunitiesPeerLinkRequestsClass decodes the TL union communities.PeerLinkRequests.
func decodeCommunitiesPeerLinkRequestsClass(input *decoder) (CommunitiesPeerLinkRequestsClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case CommunitiesPeerLinkRequestsConstructorID:
		value, err := decodeCommunitiesPeerLinkRequests(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "CommunitiesPeerLinkRequestsClass", constructor)
	}
}

// CommunitiesPeerLinkRequests represents TL class communities.peerLinkRequests (ID 0x2244afad).
type CommunitiesPeerLinkRequests struct {
	TotalCount int32
	Requests   []CommunityPeerRequestClass
	NextOffset *string
	Chats      []ChatClass
	Users      []UserClass
}

// CommunitiesPeerLinkRequestsConstructorID is the TL constructor ID for communities.peerLinkRequests.
const CommunitiesPeerLinkRequestsConstructorID uint32 = 0x2244afad

// ConstructorID returns the TL constructor ID.
func (*CommunitiesPeerLinkRequests) ConstructorID() uint32 {
	return CommunitiesPeerLinkRequestsConstructorID
}

func (*CommunitiesPeerLinkRequests) isCommunitiesPeerLinkRequestsClass() {
}

func (value *CommunitiesPeerLinkRequests) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.peerLinkRequests", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesPeerLinkRequests) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.peerLinkRequests", "", ErrNilObject)
	}
	_present0 := value.NextOffset != nil
	size := 0
	size += 4
	size += 4
	if err := validateVectorLength(len(value.Requests)); err != nil {
		return 0, encodeError("communities.peerLinkRequests", "requests", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.Requests {
		if value.Requests[_index0] == nil {
			return 0, encodeError("communities.peerLinkRequests", "requests", ErrNilObject)
		}
		_fieldSize1, err := value.Requests[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "requests", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "requests", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("communities.peerLinkRequests", "requests", err)
	}
	size = _totalSize0
	if _present0 {
		_fieldSize2, err := bytesEncodedSize(len(*value.NextOffset))
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "next_offset", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "next_offset", err)
		}
	}
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("communities.peerLinkRequests", "chats", err)
	}
	_vectorSize3 := 8
	for _index3 := range value.Chats {
		if value.Chats[_index3] == nil {
			return 0, encodeError("communities.peerLinkRequests", "chats", ErrNilObject)
		}
		_fieldSize4, err := value.Chats[_index3].encodedSize()
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "chats", err)
		}
		_vectorSize3, err = checkedEncodedSizeAdd(_vectorSize3, _fieldSize4)
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "chats", err)
		}
	}
	_totalSize3, err := checkedEncodedSizeAdd(size, _vectorSize3)
	if err != nil {
		return 0, encodeError("communities.peerLinkRequests", "chats", err)
	}
	size = _totalSize3
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("communities.peerLinkRequests", "users", err)
	}
	_vectorSize5 := 8
	for _index5 := range value.Users {
		if value.Users[_index5] == nil {
			return 0, encodeError("communities.peerLinkRequests", "users", ErrNilObject)
		}
		_fieldSize6, err := value.Users[_index5].encodedSize()
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "users", err)
		}
		_vectorSize5, err = checkedEncodedSizeAdd(_vectorSize5, _fieldSize6)
		if err != nil {
			return 0, encodeError("communities.peerLinkRequests", "users", err)
		}
	}
	_totalSize5, err := checkedEncodedSizeAdd(size, _vectorSize5)
	if err != nil {
		return 0, encodeError("communities.peerLinkRequests", "users", err)
	}
	size = _totalSize5
	return size, nil
}

func (value *CommunitiesPeerLinkRequests) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.peerLinkRequests", "", ErrNilObject)
	}
	output.putUint32(CommunitiesPeerLinkRequestsConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesPeerLinkRequests) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.peerLinkRequests", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.NextOffset != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	output.putInt32(value.TotalCount)
	if err := output.putVectorHeader(len(value.Requests)); err != nil {
		return output, encodeError("communities.peerLinkRequests", "requests", err)
	}
	for _index := range value.Requests {
		if value.Requests[_index] == nil {
			return output, encodeError("communities.peerLinkRequests", "requests", ErrNilObject)
		}
		_output0, err := value.Requests[_index].encode(output)
		if err != nil {
			return output, encodeError("communities.peerLinkRequests", "requests", err)
		}
		output = _output0
	}
	if _present0 {
		if err := output.putString(*value.NextOffset); err != nil {
			return output, encodeError("communities.peerLinkRequests", "next_offset", err)
		}
	}
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("communities.peerLinkRequests", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("communities.peerLinkRequests", "chats", ErrNilObject)
		}
		_output1, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("communities.peerLinkRequests", "chats", err)
		}
		output = _output1
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("communities.peerLinkRequests", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("communities.peerLinkRequests", "users", ErrNilObject)
		}
		_output2, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("communities.peerLinkRequests", "users", err)
		}
		output = _output2
	}
	return output, nil
}

// decodeCommunitiesPeerLinkRequests decodes a TL communities.PeerLinkRequests.
func decodeCommunitiesPeerLinkRequests(input *decoder) (*CommunitiesPeerLinkRequests, error) {
	if err := input.reserveAllocation("communities.peerLinkRequests", decodedAllocationSize(44, 88)); err != nil {
		return nil, err
	}
	value := new(CommunitiesPeerLinkRequests)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *CommunitiesPeerLinkRequests) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.TotalCount = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.peerLinkRequests.requests", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Requests = make([]CommunityPeerRequestClass, _count1)
	for _index1 := range value.Requests {
		_field2, err := decodeCommunityPeerRequestClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Requests[_index1] = _field2
	}
	if _flags0&(uint32(1)<<0) != 0 {
		_field3, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("communities.peerLinkRequests.next_offset", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.NextOffset = &_field3
	}
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.peerLinkRequests.chats", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count4)
	for _index4 := range value.Chats {
		_field5, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index4] = _field5
	}
	_count6, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.peerLinkRequests.users", _count6, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count6)
	for _index6 := range value.Users {
		_field7, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index6] = _field7
	}
	input.leave()
	return nil
}

// CommunitiesTogglePeerLinkRequest represents TL method communities.togglePeerLink (ID 0x736dcfea).
type CommunitiesTogglePeerLinkRequest struct {
	Visible   bool
	Hidden    bool
	Deleted   bool
	Community InputChannelClass
	Peer      InputPeerClass
}

// CommunitiesTogglePeerLinkRequestConstructorID is the TL constructor ID for communities.togglePeerLink.
const CommunitiesTogglePeerLinkRequestConstructorID uint32 = 0x736dcfea

// ConstructorID returns the TL constructor ID.
func (*CommunitiesTogglePeerLinkRequest) ConstructorID() uint32 {
	return CommunitiesTogglePeerLinkRequestConstructorID
}

func (*CommunitiesTogglePeerLinkRequest) requestResult(bool) {}

func (value *CommunitiesTogglePeerLinkRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.togglePeerLink", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesTogglePeerLinkRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.togglePeerLink", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Community == nil {
		return 0, encodeError("communities.togglePeerLink", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.togglePeerLink", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.togglePeerLink", "community", err)
	}
	if value.Peer == nil {
		return 0, encodeError("communities.togglePeerLink", "peer", ErrNilObject)
	}
	_fieldSize1, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("communities.togglePeerLink", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("communities.togglePeerLink", "peer", err)
	}
	return size, nil
}

func (value *CommunitiesTogglePeerLinkRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.togglePeerLink", "", ErrNilObject)
	}
	output.putUint32(CommunitiesTogglePeerLinkRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesTogglePeerLinkRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.togglePeerLink", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Visible
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.Hidden
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.Deleted
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	output.putUint32(_flags0)
	if value.Community == nil {
		return output, encodeError("communities.togglePeerLink", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.togglePeerLink", "community", err)
	}
	output = _output0
	if value.Peer == nil {
		return output, encodeError("communities.togglePeerLink", "peer", ErrNilObject)
	}
	_output1, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("communities.togglePeerLink", "peer", err)
	}
	output = _output1
	return output, nil
}

func (request *CommunitiesTogglePeerLinkRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesTogglePeerLinkRequestApprovalRequest represents TL method communities.togglePeerLinkRequestApproval (ID 0x8c8219a8).
type CommunitiesTogglePeerLinkRequestApprovalRequest struct {
	Reject    bool
	Community InputChannelClass
	Peer      InputPeerClass
}

// CommunitiesTogglePeerLinkRequestApprovalRequestConstructorID is the TL constructor ID for communities.togglePeerLinkRequestApproval.
const CommunitiesTogglePeerLinkRequestApprovalRequestConstructorID uint32 = 0x8c8219a8

// ConstructorID returns the TL constructor ID.
func (*CommunitiesTogglePeerLinkRequestApprovalRequest) ConstructorID() uint32 {
	return CommunitiesTogglePeerLinkRequestApprovalRequestConstructorID
}

func (*CommunitiesTogglePeerLinkRequestApprovalRequest) requestResult(bool) {}

func (value *CommunitiesTogglePeerLinkRequestApprovalRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesTogglePeerLinkRequestApprovalRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Community == nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "community", err)
	}
	if value.Peer == nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "peer", ErrNilObject)
	}
	_fieldSize1, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("communities.togglePeerLinkRequestApproval", "peer", err)
	}
	return size, nil
}

func (value *CommunitiesTogglePeerLinkRequestApprovalRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.togglePeerLinkRequestApproval", "", ErrNilObject)
	}
	output.putUint32(CommunitiesTogglePeerLinkRequestApprovalRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesTogglePeerLinkRequestApprovalRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.togglePeerLinkRequestApproval", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Reject
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if value.Community == nil {
		return output, encodeError("communities.togglePeerLinkRequestApproval", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.togglePeerLinkRequestApproval", "community", err)
	}
	output = _output0
	if value.Peer == nil {
		return output, encodeError("communities.togglePeerLinkRequestApproval", "peer", ErrNilObject)
	}
	_output1, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("communities.togglePeerLinkRequestApproval", "peer", err)
	}
	output = _output1
	return output, nil
}

func (request *CommunitiesTogglePeerLinkRequestApprovalRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesParticipantJoinedChats represents TL class communities.participantJoinedChats (ID 0x8d78512a).
type CommunitiesParticipantJoinedChats struct {
	CreatorChatIDs []int64
	JoinedChatIDs  []int64
	Chats          []ChatClass
	Users          []UserClass
}

// CommunitiesParticipantJoinedChatsConstructorID is the TL constructor ID for communities.participantJoinedChats.
const CommunitiesParticipantJoinedChatsConstructorID uint32 = 0x8d78512a

// ConstructorID returns the TL constructor ID.
func (*CommunitiesParticipantJoinedChats) ConstructorID() uint32 {
	return CommunitiesParticipantJoinedChatsConstructorID
}

func (*CommunitiesParticipantJoinedChats) isCommunitiesParticipantJoinedChatsClass() {
}

func (value *CommunitiesParticipantJoinedChats) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.participantJoinedChats", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesParticipantJoinedChats) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.participantJoinedChats", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.CreatorChatIDs)); err != nil {
		return 0, encodeError("communities.participantJoinedChats", "creator_chat_ids", err)
	}
	_vectorSize0 := 8
	_elementsSize0, err := checkedEncodedSizeProduct(len(value.CreatorChatIDs), 8)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "creator_chat_ids", err)
	}
	_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _elementsSize0)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "creator_chat_ids", err)
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "creator_chat_ids", err)
	}
	size = _totalSize0
	if err := validateVectorLength(len(value.JoinedChatIDs)); err != nil {
		return 0, encodeError("communities.participantJoinedChats", "joined_chat_ids", err)
	}
	_vectorSize1 := 8
	_elementsSize1, err := checkedEncodedSizeProduct(len(value.JoinedChatIDs), 8)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "joined_chat_ids", err)
	}
	_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _elementsSize1)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "joined_chat_ids", err)
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "joined_chat_ids", err)
	}
	size = _totalSize1
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("communities.participantJoinedChats", "chats", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.Chats {
		if value.Chats[_index2] == nil {
			return 0, encodeError("communities.participantJoinedChats", "chats", ErrNilObject)
		}
		_fieldSize3, err := value.Chats[_index2].encodedSize()
		if err != nil {
			return 0, encodeError("communities.participantJoinedChats", "chats", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("communities.participantJoinedChats", "chats", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "chats", err)
	}
	size = _totalSize2
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("communities.participantJoinedChats", "users", err)
	}
	_vectorSize4 := 8
	for _index4 := range value.Users {
		if value.Users[_index4] == nil {
			return 0, encodeError("communities.participantJoinedChats", "users", ErrNilObject)
		}
		_fieldSize5, err := value.Users[_index4].encodedSize()
		if err != nil {
			return 0, encodeError("communities.participantJoinedChats", "users", err)
		}
		_vectorSize4, err = checkedEncodedSizeAdd(_vectorSize4, _fieldSize5)
		if err != nil {
			return 0, encodeError("communities.participantJoinedChats", "users", err)
		}
	}
	_totalSize4, err := checkedEncodedSizeAdd(size, _vectorSize4)
	if err != nil {
		return 0, encodeError("communities.participantJoinedChats", "users", err)
	}
	size = _totalSize4
	return size, nil
}

func (value *CommunitiesParticipantJoinedChats) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.participantJoinedChats", "", ErrNilObject)
	}
	output.putUint32(CommunitiesParticipantJoinedChatsConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesParticipantJoinedChats) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.participantJoinedChats", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.CreatorChatIDs)); err != nil {
		return output, encodeError("communities.participantJoinedChats", "creator_chat_ids", err)
	}
	for _index := range value.CreatorChatIDs {
		output.putInt64(value.CreatorChatIDs[_index])
	}
	if err := output.putVectorHeader(len(value.JoinedChatIDs)); err != nil {
		return output, encodeError("communities.participantJoinedChats", "joined_chat_ids", err)
	}
	for _index := range value.JoinedChatIDs {
		output.putInt64(value.JoinedChatIDs[_index])
	}
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("communities.participantJoinedChats", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("communities.participantJoinedChats", "chats", ErrNilObject)
		}
		_output0, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("communities.participantJoinedChats", "chats", err)
		}
		output = _output0
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("communities.participantJoinedChats", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("communities.participantJoinedChats", "users", ErrNilObject)
		}
		_output1, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("communities.participantJoinedChats", "users", err)
		}
		output = _output1
	}
	return output, nil
}

// decodeCommunitiesParticipantJoinedChats decodes a TL communities.ParticipantJoinedChats.
func decodeCommunitiesParticipantJoinedChats(input *decoder) (*CommunitiesParticipantJoinedChats, error) {
	if err := input.reserveAllocation("communities.participantJoinedChats", decodedAllocationSize(48, 96)); err != nil {
		return nil, err
	}
	value := new(CommunitiesParticipantJoinedChats)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *CommunitiesParticipantJoinedChats) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_count0, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.participantJoinedChats.creator_chat_ids", _count0, decodedAllocationSize(8, 8)); err != nil {
		input.leave()
		return err
	}
	value.CreatorChatIDs = make([]int64, _count0)
	for _index0 := range value.CreatorChatIDs {
		_field1, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		value.CreatorChatIDs[_index0] = _field1
	}
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.participantJoinedChats.joined_chat_ids", _count2, decodedAllocationSize(8, 8)); err != nil {
		input.leave()
		return err
	}
	value.JoinedChatIDs = make([]int64, _count2)
	for _index2 := range value.JoinedChatIDs {
		_field3, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		value.JoinedChatIDs[_index2] = _field3
	}
	_count4, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.participantJoinedChats.chats", _count4, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count4)
	for _index4 := range value.Chats {
		_field5, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index4] = _field5
	}
	_count6, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("communities.participantJoinedChats.users", _count6, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count6)
	for _index6 := range value.Users {
		_field7, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index6] = _field7
	}
	input.leave()
	return nil
}

// CommunitiesGetPeerLinkRequestsRequest represents TL method communities.getPeerLinkRequests (ID 0x93773344).
type CommunitiesGetPeerLinkRequestsRequest struct {
	Community InputChannelClass
	Offset    string
	Limit     int32
}

// CommunitiesGetPeerLinkRequestsRequestConstructorID is the TL constructor ID for communities.getPeerLinkRequests.
const CommunitiesGetPeerLinkRequestsRequestConstructorID uint32 = 0x93773344

// ConstructorID returns the TL constructor ID.
func (*CommunitiesGetPeerLinkRequestsRequest) ConstructorID() uint32 {
	return CommunitiesGetPeerLinkRequestsRequestConstructorID
}

func (*CommunitiesGetPeerLinkRequestsRequest) requestResult(*CommunitiesPeerLinkRequests) {}

func (value *CommunitiesGetPeerLinkRequestsRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.getPeerLinkRequests", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesGetPeerLinkRequestsRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.getPeerLinkRequests", "", ErrNilObject)
	}
	size := 0
	if value.Community == nil {
		return 0, encodeError("communities.getPeerLinkRequests", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.getPeerLinkRequests", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.getPeerLinkRequests", "community", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.Offset))
	if err != nil {
		return 0, encodeError("communities.getPeerLinkRequests", "offset", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("communities.getPeerLinkRequests", "offset", err)
	}
	size += 4
	return size, nil
}

func (value *CommunitiesGetPeerLinkRequestsRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.getPeerLinkRequests", "", ErrNilObject)
	}
	output.putUint32(CommunitiesGetPeerLinkRequestsRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesGetPeerLinkRequestsRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.getPeerLinkRequests", "", ErrNilObject)
	}
	if value.Community == nil {
		return output, encodeError("communities.getPeerLinkRequests", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.getPeerLinkRequests", "community", err)
	}
	output = _output0
	if err := output.putString(value.Offset); err != nil {
		return output, encodeError("communities.getPeerLinkRequests", "offset", err)
	}
	output.putInt32(value.Limit)
	return output, nil
}

func (request *CommunitiesGetPeerLinkRequestsRequest) decodeResult(state decoder) (*CommunitiesPeerLinkRequests, decoder, error) {
	var zero *CommunitiesPeerLinkRequests
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *CommunitiesPeerLinkRequests
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0x2244afad {
		err := input.unexpectedConstructor(_start0, "CommunitiesPeerLinkRequests", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("communities.getPeerLinkRequests.result", decodedAllocationSize(44, 88)); err != nil {
		return zero, state, err
	}
	_field1 := new(CommunitiesPeerLinkRequests)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// CommunitiesToggleParticipantBannedRequest represents TL method communities.toggleParticipantBanned (ID 0x9967ad0f).
type CommunitiesToggleParticipantBannedRequest struct {
	Unban       bool
	Community   InputChannelClass
	Participant InputPeerClass
}

// CommunitiesToggleParticipantBannedRequestConstructorID is the TL constructor ID for communities.toggleParticipantBanned.
const CommunitiesToggleParticipantBannedRequestConstructorID uint32 = 0x9967ad0f

// ConstructorID returns the TL constructor ID.
func (*CommunitiesToggleParticipantBannedRequest) ConstructorID() uint32 {
	return CommunitiesToggleParticipantBannedRequestConstructorID
}

func (*CommunitiesToggleParticipantBannedRequest) requestResult(bool) {}

func (value *CommunitiesToggleParticipantBannedRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.toggleParticipantBanned", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesToggleParticipantBannedRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.toggleParticipantBanned", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Community == nil {
		return 0, encodeError("communities.toggleParticipantBanned", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.toggleParticipantBanned", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.toggleParticipantBanned", "community", err)
	}
	if value.Participant == nil {
		return 0, encodeError("communities.toggleParticipantBanned", "participant", ErrNilObject)
	}
	_fieldSize1, err := value.Participant.encodedSize()
	if err != nil {
		return 0, encodeError("communities.toggleParticipantBanned", "participant", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("communities.toggleParticipantBanned", "participant", err)
	}
	return size, nil
}

func (value *CommunitiesToggleParticipantBannedRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.toggleParticipantBanned", "", ErrNilObject)
	}
	output.putUint32(CommunitiesToggleParticipantBannedRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesToggleParticipantBannedRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.toggleParticipantBanned", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Unban
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if value.Community == nil {
		return output, encodeError("communities.toggleParticipantBanned", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.toggleParticipantBanned", "community", err)
	}
	output = _output0
	if value.Participant == nil {
		return output, encodeError("communities.toggleParticipantBanned", "participant", ErrNilObject)
	}
	_output1, err := value.Participant.encode(output)
	if err != nil {
		return output, encodeError("communities.toggleParticipantBanned", "participant", err)
	}
	output = _output1
	return output, nil
}

func (request *CommunitiesToggleParticipantBannedRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesCreateRequest represents TL method communities.create (ID 0xa63859ec).
type CommunitiesCreateRequest struct {
	Hidden bool
	Title  string
	About  *string
	Peer   InputPeerClass
}

// CommunitiesCreateRequestConstructorID is the TL constructor ID for communities.create.
const CommunitiesCreateRequestConstructorID uint32 = 0xa63859ec

// ConstructorID returns the TL constructor ID.
func (*CommunitiesCreateRequest) ConstructorID() uint32 {
	return CommunitiesCreateRequestConstructorID
}

func (*CommunitiesCreateRequest) requestResult(UpdatesClass) {}

func (value *CommunitiesCreateRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.create", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesCreateRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.create", "", ErrNilObject)
	}
	_present1 := value.About != nil
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.Title))
	if err != nil {
		return 0, encodeError("communities.create", "title", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.create", "title", err)
	}
	if _present1 {
		_fieldSize1, err := bytesEncodedSize(len(*value.About))
		if err != nil {
			return 0, encodeError("communities.create", "about", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("communities.create", "about", err)
		}
	}
	if value.Peer == nil {
		return 0, encodeError("communities.create", "peer", ErrNilObject)
	}
	_fieldSize2, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("communities.create", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("communities.create", "peer", err)
	}
	return size, nil
}

func (value *CommunitiesCreateRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.create", "", ErrNilObject)
	}
	output.putUint32(CommunitiesCreateRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesCreateRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.create", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Hidden
	if _present0 {
		_flags0 |= uint32(1) << 1
	}
	_present1 := value.About != nil
	if _present1 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if err := output.putString(value.Title); err != nil {
		return output, encodeError("communities.create", "title", err)
	}
	if _present1 {
		if err := output.putString(*value.About); err != nil {
			return output, encodeError("communities.create", "about", err)
		}
	}
	if value.Peer == nil {
		return output, encodeError("communities.create", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("communities.create", "peer", err)
	}
	output = _output0
	return output, nil
}

func (request *CommunitiesCreateRequest) decodeResult(state decoder) (UpdatesClass, decoder, error) {
	var zero UpdatesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesClass
	_field0, err := decodeUpdatesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesGetJoinedCommunitiesRequest represents TL method communities.getJoinedCommunities (ID 0xa663e830).
type CommunitiesGetJoinedCommunitiesRequest struct {
}

// CommunitiesGetJoinedCommunitiesRequestConstructorID is the TL constructor ID for communities.getJoinedCommunities.
const CommunitiesGetJoinedCommunitiesRequestConstructorID uint32 = 0xa663e830

// ConstructorID returns the TL constructor ID.
func (*CommunitiesGetJoinedCommunitiesRequest) ConstructorID() uint32 {
	return CommunitiesGetJoinedCommunitiesRequestConstructorID
}

func (*CommunitiesGetJoinedCommunitiesRequest) requestResult(MessagesChatsClass) {}

func (value *CommunitiesGetJoinedCommunitiesRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.getJoinedCommunities", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesGetJoinedCommunitiesRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.getJoinedCommunities", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *CommunitiesGetJoinedCommunitiesRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.getJoinedCommunities", "", ErrNilObject)
	}
	output.putUint32(CommunitiesGetJoinedCommunitiesRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesGetJoinedCommunitiesRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.getJoinedCommunities", "", ErrNilObject)
	}
	return output, nil
}

func (request *CommunitiesGetJoinedCommunitiesRequest) decodeResult(state decoder) (MessagesChatsClass, decoder, error) {
	var zero MessagesChatsClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result MessagesChatsClass
	_field0, err := decodeMessagesChatsClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesToggleAllPeerLinkRequestApprovalRequest represents TL method communities.toggleAllPeerLinkRequestApproval (ID 0xbfe3dd3d).
type CommunitiesToggleAllPeerLinkRequestApprovalRequest struct {
	Reject    bool
	Community InputChannelClass
}

// CommunitiesToggleAllPeerLinkRequestApprovalRequestConstructorID is the TL constructor ID for communities.toggleAllPeerLinkRequestApproval.
const CommunitiesToggleAllPeerLinkRequestApprovalRequestConstructorID uint32 = 0xbfe3dd3d

// ConstructorID returns the TL constructor ID.
func (*CommunitiesToggleAllPeerLinkRequestApprovalRequest) ConstructorID() uint32 {
	return CommunitiesToggleAllPeerLinkRequestApprovalRequestConstructorID
}

func (*CommunitiesToggleAllPeerLinkRequestApprovalRequest) requestResult(bool) {}

func (value *CommunitiesToggleAllPeerLinkRequestApprovalRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.toggleAllPeerLinkRequestApproval", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesToggleAllPeerLinkRequestApprovalRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.toggleAllPeerLinkRequestApproval", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Community == nil {
		return 0, encodeError("communities.toggleAllPeerLinkRequestApproval", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.toggleAllPeerLinkRequestApproval", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.toggleAllPeerLinkRequestApproval", "community", err)
	}
	return size, nil
}

func (value *CommunitiesToggleAllPeerLinkRequestApprovalRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.toggleAllPeerLinkRequestApproval", "", ErrNilObject)
	}
	output.putUint32(CommunitiesToggleAllPeerLinkRequestApprovalRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesToggleAllPeerLinkRequestApprovalRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.toggleAllPeerLinkRequestApproval", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Reject
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if value.Community == nil {
		return output, encodeError("communities.toggleAllPeerLinkRequestApproval", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.toggleAllPeerLinkRequestApproval", "community", err)
	}
	output = _output0
	return output, nil
}

func (request *CommunitiesToggleAllPeerLinkRequestApprovalRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesToggleCommunityCollapsedInDialogsRequest represents TL method communities.toggleCommunityCollapsedInDialogs (ID 0xd766e3ea).
type CommunitiesToggleCommunityCollapsedInDialogsRequest struct {
	Collapsed bool
	Community InputChannelClass
}

// CommunitiesToggleCommunityCollapsedInDialogsRequestConstructorID is the TL constructor ID for communities.toggleCommunityCollapsedInDialogs.
const CommunitiesToggleCommunityCollapsedInDialogsRequestConstructorID uint32 = 0xd766e3ea

// ConstructorID returns the TL constructor ID.
func (*CommunitiesToggleCommunityCollapsedInDialogsRequest) ConstructorID() uint32 {
	return CommunitiesToggleCommunityCollapsedInDialogsRequestConstructorID
}

func (*CommunitiesToggleCommunityCollapsedInDialogsRequest) requestResult(UpdatesClass) {}

func (value *CommunitiesToggleCommunityCollapsedInDialogsRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.toggleCommunityCollapsedInDialogs", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesToggleCommunityCollapsedInDialogsRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.toggleCommunityCollapsedInDialogs", "", ErrNilObject)
	}
	size := 0
	size += 4
	if value.Community == nil {
		return 0, encodeError("communities.toggleCommunityCollapsedInDialogs", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.toggleCommunityCollapsedInDialogs", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.toggleCommunityCollapsedInDialogs", "community", err)
	}
	return size, nil
}

func (value *CommunitiesToggleCommunityCollapsedInDialogsRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.toggleCommunityCollapsedInDialogs", "", ErrNilObject)
	}
	output.putUint32(CommunitiesToggleCommunityCollapsedInDialogsRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesToggleCommunityCollapsedInDialogsRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.toggleCommunityCollapsedInDialogs", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Collapsed
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if value.Community == nil {
		return output, encodeError("communities.toggleCommunityCollapsedInDialogs", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.toggleCommunityCollapsedInDialogs", "community", err)
	}
	output = _output0
	return output, nil
}

func (request *CommunitiesToggleCommunityCollapsedInDialogsRequest) decodeResult(state decoder) (UpdatesClass, decoder, error) {
	var zero UpdatesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesClass
	_field0, err := decodeUpdatesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// CommunitiesGetParticipantJoinedChatsRequest represents TL method communities.getParticipantJoinedChats (ID 0xf87eabab).
type CommunitiesGetParticipantJoinedChatsRequest struct {
	Community   InputChannelClass
	Participant InputPeerClass
}

// CommunitiesGetParticipantJoinedChatsRequestConstructorID is the TL constructor ID for communities.getParticipantJoinedChats.
const CommunitiesGetParticipantJoinedChatsRequestConstructorID uint32 = 0xf87eabab

// ConstructorID returns the TL constructor ID.
func (*CommunitiesGetParticipantJoinedChatsRequest) ConstructorID() uint32 {
	return CommunitiesGetParticipantJoinedChatsRequestConstructorID
}

func (*CommunitiesGetParticipantJoinedChatsRequest) requestResult(*CommunitiesParticipantJoinedChats) {
}

func (value *CommunitiesGetParticipantJoinedChatsRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *CommunitiesGetParticipantJoinedChatsRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "", ErrNilObject)
	}
	size := 0
	if value.Community == nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "community", ErrNilObject)
	}
	_fieldSize0, err := value.Community.encodedSize()
	if err != nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "community", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "community", err)
	}
	if value.Participant == nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "participant", ErrNilObject)
	}
	_fieldSize1, err := value.Participant.encodedSize()
	if err != nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "participant", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("communities.getParticipantJoinedChats", "participant", err)
	}
	return size, nil
}

func (value *CommunitiesGetParticipantJoinedChatsRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.getParticipantJoinedChats", "", ErrNilObject)
	}
	output.putUint32(CommunitiesGetParticipantJoinedChatsRequestConstructorID)
	return value.encodeBody(output)
}

func (value *CommunitiesGetParticipantJoinedChatsRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("communities.getParticipantJoinedChats", "", ErrNilObject)
	}
	if value.Community == nil {
		return output, encodeError("communities.getParticipantJoinedChats", "community", ErrNilObject)
	}
	_output0, err := value.Community.encode(output)
	if err != nil {
		return output, encodeError("communities.getParticipantJoinedChats", "community", err)
	}
	output = _output0
	if value.Participant == nil {
		return output, encodeError("communities.getParticipantJoinedChats", "participant", ErrNilObject)
	}
	_output1, err := value.Participant.encode(output)
	if err != nil {
		return output, encodeError("communities.getParticipantJoinedChats", "participant", err)
	}
	output = _output1
	return output, nil
}

func (request *CommunitiesGetParticipantJoinedChatsRequest) decodeResult(state decoder) (*CommunitiesParticipantJoinedChats, decoder, error) {
	var zero *CommunitiesParticipantJoinedChats
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *CommunitiesParticipantJoinedChats
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0x8d78512a {
		err := input.unexpectedConstructor(_start0, "CommunitiesParticipantJoinedChats", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("communities.getParticipantJoinedChats.result", decodedAllocationSize(48, 96)); err != nil {
		return zero, state, err
	}
	_field1 := new(CommunitiesParticipantJoinedChats)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}
