// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// UsersSavedMusicClass is the TL union users.SavedMusic.
type UsersSavedMusicClass interface {
	Object
	isUsersSavedMusicClass()
}

// decodeUsersSavedMusicClass decodes the TL union users.SavedMusic.
func decodeUsersSavedMusicClass(input *decoder) (UsersSavedMusicClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UsersSavedMusicConstructorID:
		value, err := decodeUsersSavedMusic(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UsersSavedMusicNotModifiedConstructorID:
		value, err := decodeUsersSavedMusicNotModified(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UsersSavedMusicClass", constructor)
	}
}

// UsersUserFullClass is the TL union users.UserFull.
type UsersUserFullClass interface {
	Object
	isUsersUserFullClass()
}

// decodeUsersUserFullClass decodes the TL union users.UserFull.
func decodeUsersUserFullClass(input *decoder) (UsersUserFullClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UsersUserFullConstructorID:
		value, err := decodeUsersUserFull(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UsersUserFullClass", constructor)
	}
}

// UsersUsersClass is the TL union users.Users.
type UsersUsersClass interface {
	Object
	isUsersUsersClass()
}

// decodeUsersUsersClass decodes the TL union users.Users.
func decodeUsersUsersClass(input *decoder) (UsersUsersClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case UsersUsersSliceConstructorID:
		value, err := decodeUsersUsersSlice(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case UsersUsersConstructorID:
		value, err := decodeUsersUsers(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "UsersUsersClass", constructor)
	}
}

// UsersGetUsersRequest represents TL method users.getUsers (ID 0x0d91a548).
type UsersGetUsersRequest struct {
	ID []InputUserClass
}

// UsersGetUsersRequestConstructorID is the TL constructor ID for users.getUsers.
const UsersGetUsersRequestConstructorID uint32 = 0x0d91a548

// ConstructorID returns the TL constructor ID.
func (*UsersGetUsersRequest) ConstructorID() uint32 {
	return UsersGetUsersRequestConstructorID
}

func (*UsersGetUsersRequest) requestResult([]UserClass) {}

func (value *UsersGetUsersRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getUsers", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersGetUsersRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getUsers", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.ID)); err != nil {
		return 0, encodeError("users.getUsers", "id", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.ID {
		if value.ID[_index0] == nil {
			return 0, encodeError("users.getUsers", "id", ErrNilObject)
		}
		_fieldSize1, err := value.ID[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("users.getUsers", "id", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("users.getUsers", "id", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("users.getUsers", "id", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *UsersGetUsersRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getUsers", "", ErrNilObject)
	}
	output.putUint32(UsersGetUsersRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersGetUsersRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getUsers", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.ID)); err != nil {
		return output, encodeError("users.getUsers", "id", err)
	}
	for _index := range value.ID {
		if value.ID[_index] == nil {
			return output, encodeError("users.getUsers", "id", ErrNilObject)
		}
		_output0, err := value.ID[_index].encode(output)
		if err != nil {
			return output, encodeError("users.getUsers", "id", err)
		}
		output = _output0
	}
	return output, nil
}

func (request *UsersGetUsersRequest) decodeResult(state decoder) ([]UserClass, decoder, error) {
	var zero []UserClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result []UserClass
	_count0, err := input.readVectorHeader()
	if err != nil {
		return zero, state, err
	}
	if err := input.reserveAllocationProduct("users.getUsers.result", _count0, decodedAllocationSize(8, 16)); err != nil {
		return zero, state, err
	}
	result = make([]UserClass, _count0)
	for _index0 := range result {
		_field1, err := decodeUserClass(input)
		if err != nil {
			return zero, state, err
		}
		result[_index0] = _field1
	}
	return result, state, nil
}

// UsersUsersSlice represents TL class users.usersSlice (ID 0x315a4974).
type UsersUsersSlice struct {
	Count int32
	Users []UserClass
}

// UsersUsersSliceConstructorID is the TL constructor ID for users.usersSlice.
const UsersUsersSliceConstructorID uint32 = 0x315a4974

// ConstructorID returns the TL constructor ID.
func (*UsersUsersSlice) ConstructorID() uint32 {
	return UsersUsersSliceConstructorID
}

func (*UsersUsersSlice) isUsersUsersClass() {
}

func (value *UsersUsersSlice) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.usersSlice", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersUsersSlice) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.usersSlice", "", ErrNilObject)
	}
	size := 0
	size += 4
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("users.usersSlice", "users", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.Users {
		if value.Users[_index0] == nil {
			return 0, encodeError("users.usersSlice", "users", ErrNilObject)
		}
		_fieldSize1, err := value.Users[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("users.usersSlice", "users", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("users.usersSlice", "users", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("users.usersSlice", "users", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *UsersUsersSlice) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.usersSlice", "", ErrNilObject)
	}
	output.putUint32(UsersUsersSliceConstructorID)
	return value.encodeBody(output)
}

func (value *UsersUsersSlice) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.usersSlice", "", ErrNilObject)
	}
	output.putInt32(value.Count)
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("users.usersSlice", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("users.usersSlice", "users", ErrNilObject)
		}
		_output0, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("users.usersSlice", "users", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeUsersUsersSlice decodes a TL users.Users.
func decodeUsersUsersSlice(input *decoder) (*UsersUsersSlice, error) {
	if err := input.reserveAllocation("users.usersSlice", decodedAllocationSize(16, 32)); err != nil {
		return nil, err
	}
	value := new(UsersUsersSlice)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UsersUsersSlice) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Count = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("users.usersSlice.users", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count1)
	for _index1 := range value.Users {
		_field2, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index1] = _field2
	}
	input.leave()
	return nil
}

// UsersSavedMusic represents TL class users.savedMusic (ID 0x34a2f297).
type UsersSavedMusic struct {
	Count     int32
	Documents []DocumentClass
}

// UsersSavedMusicConstructorID is the TL constructor ID for users.savedMusic.
const UsersSavedMusicConstructorID uint32 = 0x34a2f297

// ConstructorID returns the TL constructor ID.
func (*UsersSavedMusic) ConstructorID() uint32 {
	return UsersSavedMusicConstructorID
}

func (*UsersSavedMusic) isUsersSavedMusicClass() {
}

func (value *UsersSavedMusic) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.savedMusic", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersSavedMusic) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.savedMusic", "", ErrNilObject)
	}
	size := 0
	size += 4
	if err := validateVectorLength(len(value.Documents)); err != nil {
		return 0, encodeError("users.savedMusic", "documents", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.Documents {
		if value.Documents[_index0] == nil {
			return 0, encodeError("users.savedMusic", "documents", ErrNilObject)
		}
		_fieldSize1, err := value.Documents[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("users.savedMusic", "documents", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("users.savedMusic", "documents", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("users.savedMusic", "documents", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *UsersSavedMusic) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.savedMusic", "", ErrNilObject)
	}
	output.putUint32(UsersSavedMusicConstructorID)
	return value.encodeBody(output)
}

func (value *UsersSavedMusic) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.savedMusic", "", ErrNilObject)
	}
	output.putInt32(value.Count)
	if err := output.putVectorHeader(len(value.Documents)); err != nil {
		return output, encodeError("users.savedMusic", "documents", err)
	}
	for _index := range value.Documents {
		if value.Documents[_index] == nil {
			return output, encodeError("users.savedMusic", "documents", ErrNilObject)
		}
		_output0, err := value.Documents[_index].encode(output)
		if err != nil {
			return output, encodeError("users.savedMusic", "documents", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeUsersSavedMusic decodes a TL users.SavedMusic.
func decodeUsersSavedMusic(input *decoder) (*UsersSavedMusic, error) {
	if err := input.reserveAllocation("users.savedMusic", decodedAllocationSize(16, 32)); err != nil {
		return nil, err
	}
	value := new(UsersSavedMusic)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UsersSavedMusic) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Count = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("users.savedMusic.documents", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Documents = make([]DocumentClass, _count1)
	for _index1 := range value.Documents {
		_field2, err := decodeDocumentClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Documents[_index1] = _field2
	}
	input.leave()
	return nil
}

// UsersUserFull represents TL class users.userFull (ID 0x3b6d152e).
type UsersUserFull struct {
	FullUser UserFullClass
	Chats    []ChatClass
	Users    []UserClass
}

// UsersUserFullConstructorID is the TL constructor ID for users.userFull.
const UsersUserFullConstructorID uint32 = 0x3b6d152e

// ConstructorID returns the TL constructor ID.
func (*UsersUserFull) ConstructorID() uint32 {
	return UsersUserFullConstructorID
}

func (*UsersUserFull) isUsersUserFullClass() {
}

func (value *UsersUserFull) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.userFull", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersUserFull) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.userFull", "", ErrNilObject)
	}
	size := 0
	if value.FullUser == nil {
		return 0, encodeError("users.userFull", "full_user", ErrNilObject)
	}
	_fieldSize0, err := value.FullUser.encodedSize()
	if err != nil {
		return 0, encodeError("users.userFull", "full_user", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("users.userFull", "full_user", err)
	}
	if err := validateVectorLength(len(value.Chats)); err != nil {
		return 0, encodeError("users.userFull", "chats", err)
	}
	_vectorSize1 := 8
	for _index1 := range value.Chats {
		if value.Chats[_index1] == nil {
			return 0, encodeError("users.userFull", "chats", ErrNilObject)
		}
		_fieldSize2, err := value.Chats[_index1].encodedSize()
		if err != nil {
			return 0, encodeError("users.userFull", "chats", err)
		}
		_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _fieldSize2)
		if err != nil {
			return 0, encodeError("users.userFull", "chats", err)
		}
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("users.userFull", "chats", err)
	}
	size = _totalSize1
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("users.userFull", "users", err)
	}
	_vectorSize3 := 8
	for _index3 := range value.Users {
		if value.Users[_index3] == nil {
			return 0, encodeError("users.userFull", "users", ErrNilObject)
		}
		_fieldSize4, err := value.Users[_index3].encodedSize()
		if err != nil {
			return 0, encodeError("users.userFull", "users", err)
		}
		_vectorSize3, err = checkedEncodedSizeAdd(_vectorSize3, _fieldSize4)
		if err != nil {
			return 0, encodeError("users.userFull", "users", err)
		}
	}
	_totalSize3, err := checkedEncodedSizeAdd(size, _vectorSize3)
	if err != nil {
		return 0, encodeError("users.userFull", "users", err)
	}
	size = _totalSize3
	return size, nil
}

func (value *UsersUserFull) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.userFull", "", ErrNilObject)
	}
	output.putUint32(UsersUserFullConstructorID)
	return value.encodeBody(output)
}

func (value *UsersUserFull) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.userFull", "", ErrNilObject)
	}
	if value.FullUser == nil {
		return output, encodeError("users.userFull", "full_user", ErrNilObject)
	}
	_output0, err := value.FullUser.encode(output)
	if err != nil {
		return output, encodeError("users.userFull", "full_user", err)
	}
	output = _output0
	if err := output.putVectorHeader(len(value.Chats)); err != nil {
		return output, encodeError("users.userFull", "chats", err)
	}
	for _index := range value.Chats {
		if value.Chats[_index] == nil {
			return output, encodeError("users.userFull", "chats", ErrNilObject)
		}
		_output1, err := value.Chats[_index].encode(output)
		if err != nil {
			return output, encodeError("users.userFull", "chats", err)
		}
		output = _output1
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("users.userFull", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("users.userFull", "users", ErrNilObject)
		}
		_output2, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("users.userFull", "users", err)
		}
		output = _output2
	}
	return output, nil
}

// decodeUsersUserFull decodes a TL users.UserFull.
func decodeUsersUserFull(input *decoder) (*UsersUserFull, error) {
	if err := input.reserveAllocation("users.userFull", decodedAllocationSize(32, 64)); err != nil {
		return nil, err
	}
	value := new(UsersUserFull)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UsersUserFull) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := decodeUserFullClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.FullUser = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("users.userFull.chats", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Chats = make([]ChatClass, _count1)
	for _index1 := range value.Chats {
		_field2, err := decodeChatClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Chats[_index1] = _field2
	}
	_count3, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("users.userFull.users", _count3, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count3)
	for _index3 := range value.Users {
		_field4, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index3] = _field4
	}
	input.leave()
	return nil
}

// UsersUsers represents TL class users.users (ID 0x62d706b8).
type UsersUsers struct {
	Users []UserClass
}

// UsersUsersConstructorID is the TL constructor ID for users.users.
const UsersUsersConstructorID uint32 = 0x62d706b8

// ConstructorID returns the TL constructor ID.
func (*UsersUsers) ConstructorID() uint32 {
	return UsersUsersConstructorID
}

func (*UsersUsers) isUsersUsersClass() {
}

func (value *UsersUsers) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.users", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersUsers) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.users", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("users.users", "users", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.Users {
		if value.Users[_index0] == nil {
			return 0, encodeError("users.users", "users", ErrNilObject)
		}
		_fieldSize1, err := value.Users[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("users.users", "users", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("users.users", "users", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("users.users", "users", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *UsersUsers) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.users", "", ErrNilObject)
	}
	output.putUint32(UsersUsersConstructorID)
	return value.encodeBody(output)
}

func (value *UsersUsers) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.users", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("users.users", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("users.users", "users", ErrNilObject)
		}
		_output0, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("users.users", "users", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeUsersUsers decodes a TL users.Users.
func decodeUsersUsers(input *decoder) (*UsersUsers, error) {
	if err := input.reserveAllocation("users.users", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(UsersUsers)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UsersUsers) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_count0, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("users.users.users", _count0, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count0)
	for _index0 := range value.Users {
		_field1, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index0] = _field1
	}
	input.leave()
	return nil
}

// UsersGetSavedMusicByIDRequest represents TL method users.getSavedMusicByID (ID 0x7573a4e9).
type UsersGetSavedMusicByIDRequest struct {
	ID        InputUserClass
	Documents []InputDocumentClass
}

// UsersGetSavedMusicByIDRequestConstructorID is the TL constructor ID for users.getSavedMusicByID.
const UsersGetSavedMusicByIDRequestConstructorID uint32 = 0x7573a4e9

// ConstructorID returns the TL constructor ID.
func (*UsersGetSavedMusicByIDRequest) ConstructorID() uint32 {
	return UsersGetSavedMusicByIDRequestConstructorID
}

func (*UsersGetSavedMusicByIDRequest) requestResult(UsersSavedMusicClass) {}

func (value *UsersGetSavedMusicByIDRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getSavedMusicByID", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersGetSavedMusicByIDRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getSavedMusicByID", "", ErrNilObject)
	}
	size := 0
	if value.ID == nil {
		return 0, encodeError("users.getSavedMusicByID", "id", ErrNilObject)
	}
	_fieldSize0, err := value.ID.encodedSize()
	if err != nil {
		return 0, encodeError("users.getSavedMusicByID", "id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("users.getSavedMusicByID", "id", err)
	}
	if err := validateVectorLength(len(value.Documents)); err != nil {
		return 0, encodeError("users.getSavedMusicByID", "documents", err)
	}
	_vectorSize1 := 8
	for _index1 := range value.Documents {
		if value.Documents[_index1] == nil {
			return 0, encodeError("users.getSavedMusicByID", "documents", ErrNilObject)
		}
		_fieldSize2, err := value.Documents[_index1].encodedSize()
		if err != nil {
			return 0, encodeError("users.getSavedMusicByID", "documents", err)
		}
		_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _fieldSize2)
		if err != nil {
			return 0, encodeError("users.getSavedMusicByID", "documents", err)
		}
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("users.getSavedMusicByID", "documents", err)
	}
	size = _totalSize1
	return size, nil
}

func (value *UsersGetSavedMusicByIDRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getSavedMusicByID", "", ErrNilObject)
	}
	output.putUint32(UsersGetSavedMusicByIDRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersGetSavedMusicByIDRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getSavedMusicByID", "", ErrNilObject)
	}
	if value.ID == nil {
		return output, encodeError("users.getSavedMusicByID", "id", ErrNilObject)
	}
	_output0, err := value.ID.encode(output)
	if err != nil {
		return output, encodeError("users.getSavedMusicByID", "id", err)
	}
	output = _output0
	if err := output.putVectorHeader(len(value.Documents)); err != nil {
		return output, encodeError("users.getSavedMusicByID", "documents", err)
	}
	for _index := range value.Documents {
		if value.Documents[_index] == nil {
			return output, encodeError("users.getSavedMusicByID", "documents", ErrNilObject)
		}
		_output1, err := value.Documents[_index].encode(output)
		if err != nil {
			return output, encodeError("users.getSavedMusicByID", "documents", err)
		}
		output = _output1
	}
	return output, nil
}

func (request *UsersGetSavedMusicByIDRequest) decodeResult(state decoder) (UsersSavedMusicClass, decoder, error) {
	var zero UsersSavedMusicClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UsersSavedMusicClass
	_field0, err := decodeUsersSavedMusicClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UsersGetSavedMusicRequest represents TL method users.getSavedMusic (ID 0x788d7fe3).
type UsersGetSavedMusicRequest struct {
	ID     InputUserClass
	Offset int32
	Limit  int32
	Hash   int64
}

// UsersGetSavedMusicRequestConstructorID is the TL constructor ID for users.getSavedMusic.
const UsersGetSavedMusicRequestConstructorID uint32 = 0x788d7fe3

// ConstructorID returns the TL constructor ID.
func (*UsersGetSavedMusicRequest) ConstructorID() uint32 {
	return UsersGetSavedMusicRequestConstructorID
}

func (*UsersGetSavedMusicRequest) requestResult(UsersSavedMusicClass) {}

func (value *UsersGetSavedMusicRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getSavedMusic", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersGetSavedMusicRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getSavedMusic", "", ErrNilObject)
	}
	size := 0
	if value.ID == nil {
		return 0, encodeError("users.getSavedMusic", "id", ErrNilObject)
	}
	_fieldSize0, err := value.ID.encodedSize()
	if err != nil {
		return 0, encodeError("users.getSavedMusic", "id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("users.getSavedMusic", "id", err)
	}
	size += 4
	size += 4
	size += 8
	return size, nil
}

func (value *UsersGetSavedMusicRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getSavedMusic", "", ErrNilObject)
	}
	output.putUint32(UsersGetSavedMusicRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersGetSavedMusicRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getSavedMusic", "", ErrNilObject)
	}
	if value.ID == nil {
		return output, encodeError("users.getSavedMusic", "id", ErrNilObject)
	}
	_output0, err := value.ID.encode(output)
	if err != nil {
		return output, encodeError("users.getSavedMusic", "id", err)
	}
	output = _output0
	output.putInt32(value.Offset)
	output.putInt32(value.Limit)
	output.putInt64(value.Hash)
	return output, nil
}

func (request *UsersGetSavedMusicRequest) decodeResult(state decoder) (UsersSavedMusicClass, decoder, error) {
	var zero UsersSavedMusicClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UsersSavedMusicClass
	_field0, err := decodeUsersSavedMusicClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UsersSetSecureValueErrorsRequest represents TL method users.setSecureValueErrors (ID 0x90c894b5).
type UsersSetSecureValueErrorsRequest struct {
	ID     InputUserClass
	Errors []SecureValueErrorClass
}

// UsersSetSecureValueErrorsRequestConstructorID is the TL constructor ID for users.setSecureValueErrors.
const UsersSetSecureValueErrorsRequestConstructorID uint32 = 0x90c894b5

// ConstructorID returns the TL constructor ID.
func (*UsersSetSecureValueErrorsRequest) ConstructorID() uint32 {
	return UsersSetSecureValueErrorsRequestConstructorID
}

func (*UsersSetSecureValueErrorsRequest) requestResult(bool) {}

func (value *UsersSetSecureValueErrorsRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.setSecureValueErrors", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersSetSecureValueErrorsRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.setSecureValueErrors", "", ErrNilObject)
	}
	size := 0
	if value.ID == nil {
		return 0, encodeError("users.setSecureValueErrors", "id", ErrNilObject)
	}
	_fieldSize0, err := value.ID.encodedSize()
	if err != nil {
		return 0, encodeError("users.setSecureValueErrors", "id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("users.setSecureValueErrors", "id", err)
	}
	if err := validateVectorLength(len(value.Errors)); err != nil {
		return 0, encodeError("users.setSecureValueErrors", "errors", err)
	}
	_vectorSize1 := 8
	for _index1 := range value.Errors {
		if value.Errors[_index1] == nil {
			return 0, encodeError("users.setSecureValueErrors", "errors", ErrNilObject)
		}
		_fieldSize2, err := value.Errors[_index1].encodedSize()
		if err != nil {
			return 0, encodeError("users.setSecureValueErrors", "errors", err)
		}
		_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _fieldSize2)
		if err != nil {
			return 0, encodeError("users.setSecureValueErrors", "errors", err)
		}
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("users.setSecureValueErrors", "errors", err)
	}
	size = _totalSize1
	return size, nil
}

func (value *UsersSetSecureValueErrorsRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.setSecureValueErrors", "", ErrNilObject)
	}
	output.putUint32(UsersSetSecureValueErrorsRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersSetSecureValueErrorsRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.setSecureValueErrors", "", ErrNilObject)
	}
	if value.ID == nil {
		return output, encodeError("users.setSecureValueErrors", "id", ErrNilObject)
	}
	_output0, err := value.ID.encode(output)
	if err != nil {
		return output, encodeError("users.setSecureValueErrors", "id", err)
	}
	output = _output0
	if err := output.putVectorHeader(len(value.Errors)); err != nil {
		return output, encodeError("users.setSecureValueErrors", "errors", err)
	}
	for _index := range value.Errors {
		if value.Errors[_index] == nil {
			return output, encodeError("users.setSecureValueErrors", "errors", ErrNilObject)
		}
		_output1, err := value.Errors[_index].encode(output)
		if err != nil {
			return output, encodeError("users.setSecureValueErrors", "errors", err)
		}
		output = _output1
	}
	return output, nil
}

func (request *UsersSetSecureValueErrorsRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// UsersGetFullUserRequest represents TL method users.getFullUser (ID 0xb60f5918).
type UsersGetFullUserRequest struct {
	ID InputUserClass
}

// UsersGetFullUserRequestConstructorID is the TL constructor ID for users.getFullUser.
const UsersGetFullUserRequestConstructorID uint32 = 0xb60f5918

// ConstructorID returns the TL constructor ID.
func (*UsersGetFullUserRequest) ConstructorID() uint32 {
	return UsersGetFullUserRequestConstructorID
}

func (*UsersGetFullUserRequest) requestResult(*UsersUserFull) {}

func (value *UsersGetFullUserRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getFullUser", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersGetFullUserRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getFullUser", "", ErrNilObject)
	}
	size := 0
	if value.ID == nil {
		return 0, encodeError("users.getFullUser", "id", ErrNilObject)
	}
	_fieldSize0, err := value.ID.encodedSize()
	if err != nil {
		return 0, encodeError("users.getFullUser", "id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("users.getFullUser", "id", err)
	}
	return size, nil
}

func (value *UsersGetFullUserRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getFullUser", "", ErrNilObject)
	}
	output.putUint32(UsersGetFullUserRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersGetFullUserRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getFullUser", "", ErrNilObject)
	}
	if value.ID == nil {
		return output, encodeError("users.getFullUser", "id", ErrNilObject)
	}
	_output0, err := value.ID.encode(output)
	if err != nil {
		return output, encodeError("users.getFullUser", "id", err)
	}
	output = _output0
	return output, nil
}

func (request *UsersGetFullUserRequest) decodeResult(state decoder) (*UsersUserFull, decoder, error) {
	var zero *UsersUserFull
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *UsersUserFull
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0x3b6d152e {
		err := input.unexpectedConstructor(_start0, "UsersUserFull", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("users.getFullUser.result", decodedAllocationSize(32, 64)); err != nil {
		return zero, state, err
	}
	_field1 := new(UsersUserFull)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// UsersGetRequirementsToContactRequest represents TL method users.getRequirementsToContact (ID 0xd89a83a3).
type UsersGetRequirementsToContactRequest struct {
	ID []InputUserClass
}

// UsersGetRequirementsToContactRequestConstructorID is the TL constructor ID for users.getRequirementsToContact.
const UsersGetRequirementsToContactRequestConstructorID uint32 = 0xd89a83a3

// ConstructorID returns the TL constructor ID.
func (*UsersGetRequirementsToContactRequest) ConstructorID() uint32 {
	return UsersGetRequirementsToContactRequestConstructorID
}

func (*UsersGetRequirementsToContactRequest) requestResult([]RequirementToContactClass) {}

func (value *UsersGetRequirementsToContactRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getRequirementsToContact", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersGetRequirementsToContactRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.getRequirementsToContact", "", ErrNilObject)
	}
	size := 0
	if err := validateVectorLength(len(value.ID)); err != nil {
		return 0, encodeError("users.getRequirementsToContact", "id", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.ID {
		if value.ID[_index0] == nil {
			return 0, encodeError("users.getRequirementsToContact", "id", ErrNilObject)
		}
		_fieldSize1, err := value.ID[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("users.getRequirementsToContact", "id", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("users.getRequirementsToContact", "id", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("users.getRequirementsToContact", "id", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *UsersGetRequirementsToContactRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getRequirementsToContact", "", ErrNilObject)
	}
	output.putUint32(UsersGetRequirementsToContactRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersGetRequirementsToContactRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.getRequirementsToContact", "", ErrNilObject)
	}
	if err := output.putVectorHeader(len(value.ID)); err != nil {
		return output, encodeError("users.getRequirementsToContact", "id", err)
	}
	for _index := range value.ID {
		if value.ID[_index] == nil {
			return output, encodeError("users.getRequirementsToContact", "id", ErrNilObject)
		}
		_output0, err := value.ID[_index].encode(output)
		if err != nil {
			return output, encodeError("users.getRequirementsToContact", "id", err)
		}
		output = _output0
	}
	return output, nil
}

func (request *UsersGetRequirementsToContactRequest) decodeResult(state decoder) ([]RequirementToContactClass, decoder, error) {
	var zero []RequirementToContactClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result []RequirementToContactClass
	_count0, err := input.readVectorHeader()
	if err != nil {
		return zero, state, err
	}
	if err := input.reserveAllocationProduct("users.getRequirementsToContact.result", _count0, decodedAllocationSize(8, 16)); err != nil {
		return zero, state, err
	}
	result = make([]RequirementToContactClass, _count0)
	for _index0 := range result {
		_field1, err := decodeRequirementToContactClass(input)
		if err != nil {
			return zero, state, err
		}
		result[_index0] = _field1
	}
	return result, state, nil
}

// UsersSavedMusicNotModified represents TL class users.savedMusicNotModified (ID 0xe3878aa4).
type UsersSavedMusicNotModified struct {
	Count int32
}

// UsersSavedMusicNotModifiedConstructorID is the TL constructor ID for users.savedMusicNotModified.
const UsersSavedMusicNotModifiedConstructorID uint32 = 0xe3878aa4

// ConstructorID returns the TL constructor ID.
func (*UsersSavedMusicNotModified) ConstructorID() uint32 {
	return UsersSavedMusicNotModifiedConstructorID
}

func (*UsersSavedMusicNotModified) isUsersSavedMusicClass() {
}

func (value *UsersSavedMusicNotModified) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.savedMusicNotModified", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersSavedMusicNotModified) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.savedMusicNotModified", "", ErrNilObject)
	}
	size := 0
	size += 4
	return size, nil
}

func (value *UsersSavedMusicNotModified) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.savedMusicNotModified", "", ErrNilObject)
	}
	output.putUint32(UsersSavedMusicNotModifiedConstructorID)
	return value.encodeBody(output)
}

func (value *UsersSavedMusicNotModified) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.savedMusicNotModified", "", ErrNilObject)
	}
	output.putInt32(value.Count)
	return output, nil
}

// decodeUsersSavedMusicNotModified decodes a TL users.SavedMusic.
func decodeUsersSavedMusicNotModified(input *decoder) (*UsersSavedMusicNotModified, error) {
	if err := input.reserveAllocation("users.savedMusicNotModified", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(UsersSavedMusicNotModified)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *UsersSavedMusicNotModified) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Count = _field0
	input.leave()
	return nil
}

// UsersSuggestBirthdayRequest represents TL method users.suggestBirthday (ID 0xfc533372).
type UsersSuggestBirthdayRequest struct {
	ID       InputUserClass
	Birthday BirthdayClass
}

// UsersSuggestBirthdayRequestConstructorID is the TL constructor ID for users.suggestBirthday.
const UsersSuggestBirthdayRequestConstructorID uint32 = 0xfc533372

// ConstructorID returns the TL constructor ID.
func (*UsersSuggestBirthdayRequest) ConstructorID() uint32 {
	return UsersSuggestBirthdayRequestConstructorID
}

func (*UsersSuggestBirthdayRequest) requestResult(UpdatesClass) {}

func (value *UsersSuggestBirthdayRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("users.suggestBirthday", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *UsersSuggestBirthdayRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("users.suggestBirthday", "", ErrNilObject)
	}
	size := 0
	if value.ID == nil {
		return 0, encodeError("users.suggestBirthday", "id", ErrNilObject)
	}
	_fieldSize0, err := value.ID.encodedSize()
	if err != nil {
		return 0, encodeError("users.suggestBirthday", "id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("users.suggestBirthday", "id", err)
	}
	if value.Birthday == nil {
		return 0, encodeError("users.suggestBirthday", "birthday", ErrNilObject)
	}
	_fieldSize1, err := value.Birthday.encodedSize()
	if err != nil {
		return 0, encodeError("users.suggestBirthday", "birthday", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("users.suggestBirthday", "birthday", err)
	}
	return size, nil
}

func (value *UsersSuggestBirthdayRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.suggestBirthday", "", ErrNilObject)
	}
	output.putUint32(UsersSuggestBirthdayRequestConstructorID)
	return value.encodeBody(output)
}

func (value *UsersSuggestBirthdayRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("users.suggestBirthday", "", ErrNilObject)
	}
	if value.ID == nil {
		return output, encodeError("users.suggestBirthday", "id", ErrNilObject)
	}
	_output0, err := value.ID.encode(output)
	if err != nil {
		return output, encodeError("users.suggestBirthday", "id", err)
	}
	output = _output0
	if value.Birthday == nil {
		return output, encodeError("users.suggestBirthday", "birthday", ErrNilObject)
	}
	_output1, err := value.Birthday.encode(output)
	if err != nil {
		return output, encodeError("users.suggestBirthday", "birthday", err)
	}
	output = _output1
	return output, nil
}

func (request *UsersSuggestBirthdayRequest) decodeResult(state decoder) (UpdatesClass, decoder, error) {
	var zero UpdatesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesClass
	_field0, err := decodeUpdatesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}
