// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// EphemeralWelcomeMessagesClass is the TL union ephemeral.WelcomeMessages.
type EphemeralWelcomeMessagesClass interface {
	Object
	isEphemeralWelcomeMessagesClass()
}

// decodeEphemeralWelcomeMessagesClass decodes the TL union ephemeral.WelcomeMessages.
func decodeEphemeralWelcomeMessagesClass(input *decoder) (EphemeralWelcomeMessagesClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case EphemeralWelcomeMessagesConstructorID:
		value, err := decodeEphemeralWelcomeMessages(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case EphemeralWelcomeMessagesNotModifiedConstructorID:
		value, err := decodeEphemeralWelcomeMessagesNotModified(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "EphemeralWelcomeMessagesClass", constructor)
	}
}

// EphemeralWelcomeMessages represents TL class ephemeral.welcomeMessages (ID 0x104fc872).
type EphemeralWelcomeMessages struct {
	Hash     int64
	Messages []EphemeralMessageClass
}

// EphemeralWelcomeMessagesConstructorID is the TL constructor ID for ephemeral.welcomeMessages.
const EphemeralWelcomeMessagesConstructorID uint32 = 0x104fc872

// ConstructorID returns the TL constructor ID.
func (*EphemeralWelcomeMessages) ConstructorID() uint32 {
	return EphemeralWelcomeMessagesConstructorID
}

func (*EphemeralWelcomeMessages) isEphemeralWelcomeMessagesClass() {
}

func (value *EphemeralWelcomeMessages) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.welcomeMessages", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralWelcomeMessages) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.welcomeMessages", "", ErrNilObject)
	}
	size := 0
	size += 8
	if err := validateVectorLength(len(value.Messages)); err != nil {
		return 0, encodeError("ephemeral.welcomeMessages", "messages", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.Messages {
		if value.Messages[_index0] == nil {
			return 0, encodeError("ephemeral.welcomeMessages", "messages", ErrNilObject)
		}
		_fieldSize1, err := value.Messages[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.welcomeMessages", "messages", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("ephemeral.welcomeMessages", "messages", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("ephemeral.welcomeMessages", "messages", err)
	}
	size = _totalSize0
	return size, nil
}

func (value *EphemeralWelcomeMessages) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.welcomeMessages", "", ErrNilObject)
	}
	output.putUint32(EphemeralWelcomeMessagesConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralWelcomeMessages) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.welcomeMessages", "", ErrNilObject)
	}
	output.putInt64(value.Hash)
	if err := output.putVectorHeader(len(value.Messages)); err != nil {
		return output, encodeError("ephemeral.welcomeMessages", "messages", err)
	}
	for _index := range value.Messages {
		if value.Messages[_index] == nil {
			return output, encodeError("ephemeral.welcomeMessages", "messages", ErrNilObject)
		}
		_output0, err := value.Messages[_index].encode(output)
		if err != nil {
			return output, encodeError("ephemeral.welcomeMessages", "messages", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeEphemeralWelcomeMessages decodes a TL ephemeral.WelcomeMessages.
func decodeEphemeralWelcomeMessages(input *decoder) (*EphemeralWelcomeMessages, error) {
	if err := input.reserveAllocation("ephemeral.welcomeMessages", decodedAllocationSize(20, 32)); err != nil {
		return nil, err
	}
	value := new(EphemeralWelcomeMessages)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *EphemeralWelcomeMessages) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.Hash = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("ephemeral.welcomeMessages.messages", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Messages = make([]EphemeralMessageClass, _count1)
	for _index1 := range value.Messages {
		_field2, err := decodeEphemeralMessageClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Messages[_index1] = _field2
	}
	input.leave()
	return nil
}

// EphemeralGetCallbackAnswerRequest represents TL method ephemeral.getCallbackAnswer (ID 0x3fa464c8).
type EphemeralGetCallbackAnswerRequest struct {
	Peer InputPeerClass
	ID   int32
	Data []byte
}

// EphemeralGetCallbackAnswerRequestConstructorID is the TL constructor ID for ephemeral.getCallbackAnswer.
const EphemeralGetCallbackAnswerRequestConstructorID uint32 = 0x3fa464c8

// ConstructorID returns the TL constructor ID.
func (*EphemeralGetCallbackAnswerRequest) ConstructorID() uint32 {
	return EphemeralGetCallbackAnswerRequestConstructorID
}

func (*EphemeralGetCallbackAnswerRequest) requestResult(*MessagesBotCallbackAnswer) {}

func (value *EphemeralGetCallbackAnswerRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.getCallbackAnswer", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralGetCallbackAnswerRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.getCallbackAnswer", "", ErrNilObject)
	}
	_present0 := value.Data != nil
	size := 0
	size += 4
	if value.Peer == nil {
		return 0, encodeError("ephemeral.getCallbackAnswer", "peer", ErrNilObject)
	}
	_fieldSize0, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.getCallbackAnswer", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("ephemeral.getCallbackAnswer", "peer", err)
	}
	size += 4
	if _present0 {
		_fieldSize1, err := bytesEncodedSize(len(value.Data))
		if err != nil {
			return 0, encodeError("ephemeral.getCallbackAnswer", "data", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("ephemeral.getCallbackAnswer", "data", err)
		}
	}
	return size, nil
}

func (value *EphemeralGetCallbackAnswerRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.getCallbackAnswer", "", ErrNilObject)
	}
	output.putUint32(EphemeralGetCallbackAnswerRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralGetCallbackAnswerRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.getCallbackAnswer", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Data != nil
	if _present0 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	if value.Peer == nil {
		return output, encodeError("ephemeral.getCallbackAnswer", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.getCallbackAnswer", "peer", err)
	}
	output = _output0
	output.putInt32(value.ID)
	if _present0 {
		if err := output.putBytes(value.Data); err != nil {
			return output, encodeError("ephemeral.getCallbackAnswer", "data", err)
		}
	}
	return output, nil
}

func (request *EphemeralGetCallbackAnswerRequest) decodeResult(state decoder) (*MessagesBotCallbackAnswer, decoder, error) {
	var zero *MessagesBotCallbackAnswer
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *MessagesBotCallbackAnswer
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0x36585ea4 {
		err := input.unexpectedConstructor(_start0, "MessagesBotCallbackAnswer", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("ephemeral.getCallbackAnswer.result", decodedAllocationSize(24, 48)); err != nil {
		return zero, state, err
	}
	_field1 := new(MessagesBotCallbackAnswer)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// EphemeralWelcomeMessagesNotModified represents TL class ephemeral.welcomeMessagesNotModified (ID 0x59ffdb31).
type EphemeralWelcomeMessagesNotModified struct {
}

// EphemeralWelcomeMessagesNotModifiedConstructorID is the TL constructor ID for ephemeral.welcomeMessagesNotModified.
const EphemeralWelcomeMessagesNotModifiedConstructorID uint32 = 0x59ffdb31

// ConstructorID returns the TL constructor ID.
func (*EphemeralWelcomeMessagesNotModified) ConstructorID() uint32 {
	return EphemeralWelcomeMessagesNotModifiedConstructorID
}

func (*EphemeralWelcomeMessagesNotModified) isEphemeralWelcomeMessagesClass() {
}

func (value *EphemeralWelcomeMessagesNotModified) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.welcomeMessagesNotModified", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralWelcomeMessagesNotModified) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.welcomeMessagesNotModified", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *EphemeralWelcomeMessagesNotModified) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.welcomeMessagesNotModified", "", ErrNilObject)
	}
	output.putUint32(EphemeralWelcomeMessagesNotModifiedConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralWelcomeMessagesNotModified) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.welcomeMessagesNotModified", "", ErrNilObject)
	}
	return output, nil
}

// decodeEphemeralWelcomeMessagesNotModified decodes a TL ephemeral.WelcomeMessages.
func decodeEphemeralWelcomeMessagesNotModified(input *decoder) (*EphemeralWelcomeMessagesNotModified, error) {
	if err := input.reserveAllocation("ephemeral.welcomeMessagesNotModified", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(EphemeralWelcomeMessagesNotModified)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *EphemeralWelcomeMessagesNotModified) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	input.leave()
	return nil
}

// EphemeralDeleteAllWelcomeMessagesRequest represents TL method ephemeral.deleteAllWelcomeMessages (ID 0x734f9721).
type EphemeralDeleteAllWelcomeMessagesRequest struct {
	Peer InputPeerClass
}

// EphemeralDeleteAllWelcomeMessagesRequestConstructorID is the TL constructor ID for ephemeral.deleteAllWelcomeMessages.
const EphemeralDeleteAllWelcomeMessagesRequestConstructorID uint32 = 0x734f9721

// ConstructorID returns the TL constructor ID.
func (*EphemeralDeleteAllWelcomeMessagesRequest) ConstructorID() uint32 {
	return EphemeralDeleteAllWelcomeMessagesRequestConstructorID
}

func (*EphemeralDeleteAllWelcomeMessagesRequest) requestResult(bool) {}

func (value *EphemeralDeleteAllWelcomeMessagesRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.deleteAllWelcomeMessages", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralDeleteAllWelcomeMessagesRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.deleteAllWelcomeMessages", "", ErrNilObject)
	}
	size := 0
	if value.Peer == nil {
		return 0, encodeError("ephemeral.deleteAllWelcomeMessages", "peer", ErrNilObject)
	}
	_fieldSize0, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.deleteAllWelcomeMessages", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("ephemeral.deleteAllWelcomeMessages", "peer", err)
	}
	return size, nil
}

func (value *EphemeralDeleteAllWelcomeMessagesRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.deleteAllWelcomeMessages", "", ErrNilObject)
	}
	output.putUint32(EphemeralDeleteAllWelcomeMessagesRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralDeleteAllWelcomeMessagesRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.deleteAllWelcomeMessages", "", ErrNilObject)
	}
	if value.Peer == nil {
		return output, encodeError("ephemeral.deleteAllWelcomeMessages", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.deleteAllWelcomeMessages", "peer", err)
	}
	output = _output0
	return output, nil
}

func (request *EphemeralDeleteAllWelcomeMessagesRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// EphemeralReportMessageRequest represents TL method ephemeral.reportMessage (ID 0x8704f2bf).
type EphemeralReportMessageRequest struct {
	Peer    InputPeerClass
	ID      int32
	Option  []byte
	Message string
}

// EphemeralReportMessageRequestConstructorID is the TL constructor ID for ephemeral.reportMessage.
const EphemeralReportMessageRequestConstructorID uint32 = 0x8704f2bf

// ConstructorID returns the TL constructor ID.
func (*EphemeralReportMessageRequest) ConstructorID() uint32 {
	return EphemeralReportMessageRequestConstructorID
}

func (*EphemeralReportMessageRequest) requestResult(ReportResultClass) {}

func (value *EphemeralReportMessageRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.reportMessage", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralReportMessageRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.reportMessage", "", ErrNilObject)
	}
	size := 0
	if value.Peer == nil {
		return 0, encodeError("ephemeral.reportMessage", "peer", ErrNilObject)
	}
	_fieldSize0, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.reportMessage", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("ephemeral.reportMessage", "peer", err)
	}
	size += 4
	_fieldSize1, err := bytesEncodedSize(len(value.Option))
	if err != nil {
		return 0, encodeError("ephemeral.reportMessage", "option", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("ephemeral.reportMessage", "option", err)
	}
	_fieldSize2, err := bytesEncodedSize(len(value.Message))
	if err != nil {
		return 0, encodeError("ephemeral.reportMessage", "message", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("ephemeral.reportMessage", "message", err)
	}
	return size, nil
}

func (value *EphemeralReportMessageRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.reportMessage", "", ErrNilObject)
	}
	output.putUint32(EphemeralReportMessageRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralReportMessageRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.reportMessage", "", ErrNilObject)
	}
	if value.Peer == nil {
		return output, encodeError("ephemeral.reportMessage", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.reportMessage", "peer", err)
	}
	output = _output0
	output.putInt32(value.ID)
	if err := output.putBytes(value.Option); err != nil {
		return output, encodeError("ephemeral.reportMessage", "option", err)
	}
	if err := output.putString(value.Message); err != nil {
		return output, encodeError("ephemeral.reportMessage", "message", err)
	}
	return output, nil
}

func (request *EphemeralReportMessageRequest) decodeResult(state decoder) (ReportResultClass, decoder, error) {
	var zero ReportResultClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result ReportResultClass
	_field0, err := decodeReportResultClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// EphemeralDeleteMessageRequest represents TL method ephemeral.deleteMessage (ID 0x92f6e797).
type EphemeralDeleteMessageRequest struct {
	Peer       InputPeerClass
	ReceiverID InputUserClass
	ID         int32
}

// EphemeralDeleteMessageRequestConstructorID is the TL constructor ID for ephemeral.deleteMessage.
const EphemeralDeleteMessageRequestConstructorID uint32 = 0x92f6e797

// ConstructorID returns the TL constructor ID.
func (*EphemeralDeleteMessageRequest) ConstructorID() uint32 {
	return EphemeralDeleteMessageRequestConstructorID
}

func (*EphemeralDeleteMessageRequest) requestResult(bool) {}

func (value *EphemeralDeleteMessageRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.deleteMessage", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralDeleteMessageRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.deleteMessage", "", ErrNilObject)
	}
	_present0 := value.Peer != nil
	size := 0
	size += 4
	if _present0 {
		_fieldSize0, err := value.Peer.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.deleteMessage", "peer", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("ephemeral.deleteMessage", "peer", err)
		}
	}
	if value.ReceiverID == nil {
		return 0, encodeError("ephemeral.deleteMessage", "receiver_id", ErrNilObject)
	}
	_fieldSize1, err := value.ReceiverID.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.deleteMessage", "receiver_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("ephemeral.deleteMessage", "receiver_id", err)
	}
	size += 4
	return size, nil
}

func (value *EphemeralDeleteMessageRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.deleteMessage", "", ErrNilObject)
	}
	output.putUint32(EphemeralDeleteMessageRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralDeleteMessageRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.deleteMessage", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Peer != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if _present0 {
		_output0, err := value.Peer.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.deleteMessage", "peer", err)
		}
		output = _output0
	}
	if value.ReceiverID == nil {
		return output, encodeError("ephemeral.deleteMessage", "receiver_id", ErrNilObject)
	}
	_output1, err := value.ReceiverID.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.deleteMessage", "receiver_id", err)
	}
	output = _output1
	output.putInt32(value.ID)
	return output, nil
}

func (request *EphemeralDeleteMessageRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// EphemeralSendMessageRequest represents TL method ephemeral.sendMessage (ID 0xba8d5f35).
type EphemeralSendMessageRequest struct {
	InvertMedia bool
	Welcome     bool
	Anchor      bool
	Noforwards  bool
	Peer        InputPeerClass
	ReceiverID  InputUserClass
	QueryID     *int64
	Message     string
	Entities    []MessageEntityClass
	Media       InputMediaClass
	ReplyMarkup ReplyMarkupClass
	RichMessage InputRichMessageClass
	RandomID    int64
	ReplyTo     InputReplyToClass
}

// EphemeralSendMessageRequestConstructorID is the TL constructor ID for ephemeral.sendMessage.
const EphemeralSendMessageRequestConstructorID uint32 = 0xba8d5f35

// ConstructorID returns the TL constructor ID.
func (*EphemeralSendMessageRequest) ConstructorID() uint32 {
	return EphemeralSendMessageRequestConstructorID
}

func (*EphemeralSendMessageRequest) requestResult(UpdatesClass) {}

func (value *EphemeralSendMessageRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.sendMessage", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralSendMessageRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.sendMessage", "", ErrNilObject)
	}
	_present4 := value.Peer != nil
	_present5 := value.QueryID != nil
	_present6 := value.Entities != nil
	_present7 := value.Media != nil
	_present8 := value.ReplyMarkup != nil
	_present9 := value.RichMessage != nil
	_present10 := value.ReplyTo != nil
	size := 0
	size += 4
	if _present4 {
		_fieldSize0, err := value.Peer.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "peer", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "peer", err)
		}
	}
	if value.ReceiverID == nil {
		return 0, encodeError("ephemeral.sendMessage", "receiver_id", ErrNilObject)
	}
	_fieldSize1, err := value.ReceiverID.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.sendMessage", "receiver_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("ephemeral.sendMessage", "receiver_id", err)
	}
	if _present5 {
		size += 8
	}
	_fieldSize2, err := bytesEncodedSize(len(value.Message))
	if err != nil {
		return 0, encodeError("ephemeral.sendMessage", "message", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("ephemeral.sendMessage", "message", err)
	}
	if _present6 {
		if err := validateVectorLength(len(value.Entities)); err != nil {
			return 0, encodeError("ephemeral.sendMessage", "entities", err)
		}
		_vectorSize3 := 8
		for _index3 := range value.Entities {
			_fieldSize4, err := value.Entities[_index3].encodedSize()
			if err != nil {
				return 0, encodeError("ephemeral.sendMessage", "entities", err)
			}
			_vectorSize3, err = checkedEncodedSizeAdd(_vectorSize3, _fieldSize4)
			if err != nil {
				return 0, encodeError("ephemeral.sendMessage", "entities", err)
			}
		}
		_totalSize3, err := checkedEncodedSizeAdd(size, _vectorSize3)
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "entities", err)
		}
		size = _totalSize3
	}
	if _present7 {
		_fieldSize5, err := value.Media.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "media", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize5)
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "media", err)
		}
	}
	if _present8 {
		_fieldSize6, err := value.ReplyMarkup.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "reply_markup", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize6)
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "reply_markup", err)
		}
	}
	if _present9 {
		_fieldSize7, err := value.RichMessage.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "rich_message", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize7)
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "rich_message", err)
		}
	}
	size += 8
	if _present10 {
		_fieldSize8, err := value.ReplyTo.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "reply_to", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize8)
		if err != nil {
			return 0, encodeError("ephemeral.sendMessage", "reply_to", err)
		}
	}
	return size, nil
}

func (value *EphemeralSendMessageRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.sendMessage", "", ErrNilObject)
	}
	output.putUint32(EphemeralSendMessageRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralSendMessageRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.sendMessage", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.InvertMedia
	if _present0 {
		_flags0 |= uint32(1) << 6
	}
	_present1 := value.Welcome
	if _present1 {
		_flags0 |= uint32(1) << 7
	}
	_present2 := value.Anchor
	if _present2 {
		_flags0 |= uint32(1) << 9
	}
	_present3 := value.Noforwards
	if _present3 {
		_flags0 |= uint32(1) << 10
	}
	_present4 := value.Peer != nil
	if _present4 {
		_flags0 |= uint32(1) << 8
	}
	_present5 := value.QueryID != nil
	if _present5 {
		_flags0 |= uint32(1) << 0
	}
	_present6 := value.Entities != nil
	if _present6 {
		_flags0 |= uint32(1) << 1
	}
	_present7 := value.Media != nil
	if _present7 {
		_flags0 |= uint32(1) << 2
	}
	_present8 := value.ReplyMarkup != nil
	if _present8 {
		_flags0 |= uint32(1) << 3
	}
	_present9 := value.RichMessage != nil
	if _present9 {
		_flags0 |= uint32(1) << 4
	}
	_present10 := value.ReplyTo != nil
	if _present10 {
		_flags0 |= uint32(1) << 5
	}
	output.putUint32(_flags0)
	if _present4 {
		_output0, err := value.Peer.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.sendMessage", "peer", err)
		}
		output = _output0
	}
	if value.ReceiverID == nil {
		return output, encodeError("ephemeral.sendMessage", "receiver_id", ErrNilObject)
	}
	_output1, err := value.ReceiverID.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.sendMessage", "receiver_id", err)
	}
	output = _output1
	if _present5 {
		output.putInt64(*value.QueryID)
	}
	if err := output.putString(value.Message); err != nil {
		return output, encodeError("ephemeral.sendMessage", "message", err)
	}
	if _present6 {
		if err := output.putVectorHeader(len(value.Entities)); err != nil {
			return output, encodeError("ephemeral.sendMessage", "entities", err)
		}
		for _index := range value.Entities {
			_output2, err := value.Entities[_index].encode(output)
			if err != nil {
				return output, encodeError("ephemeral.sendMessage", "entities", err)
			}
			output = _output2
		}
	}
	if _present7 {
		_output3, err := value.Media.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.sendMessage", "media", err)
		}
		output = _output3
	}
	if _present8 {
		_output4, err := value.ReplyMarkup.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.sendMessage", "reply_markup", err)
		}
		output = _output4
	}
	if _present9 {
		_output5, err := value.RichMessage.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.sendMessage", "rich_message", err)
		}
		output = _output5
	}
	output.putInt64(value.RandomID)
	if _present10 {
		_output6, err := value.ReplyTo.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.sendMessage", "reply_to", err)
		}
		output = _output6
	}
	return output, nil
}

func (request *EphemeralSendMessageRequest) decodeResult(state decoder) (UpdatesClass, decoder, error) {
	var zero UpdatesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesClass
	_field0, err := decodeUpdatesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// EphemeralEditMessageRequest represents TL method ephemeral.editMessage (ID 0xcf9c725b).
type EphemeralEditMessageRequest struct {
	InvertMedia bool
	Welcome     bool
	Peer        InputPeerClass
	ReceiverID  InputUserClass
	ID          int32
	Message     *string
	Media       InputMediaClass
	Entities    []MessageEntityClass
	ReplyMarkup ReplyMarkupClass
	RichMessage InputRichMessageClass
}

// EphemeralEditMessageRequestConstructorID is the TL constructor ID for ephemeral.editMessage.
const EphemeralEditMessageRequestConstructorID uint32 = 0xcf9c725b

// ConstructorID returns the TL constructor ID.
func (*EphemeralEditMessageRequest) ConstructorID() uint32 {
	return EphemeralEditMessageRequestConstructorID
}

func (*EphemeralEditMessageRequest) requestResult(UpdatesClass) {}

func (value *EphemeralEditMessageRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.editMessage", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralEditMessageRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.editMessage", "", ErrNilObject)
	}
	_present2 := value.Peer != nil
	_present3 := value.Message != nil
	_present4 := value.Media != nil
	_present5 := value.Entities != nil
	_present6 := value.ReplyMarkup != nil
	_present7 := value.RichMessage != nil
	size := 0
	size += 4
	if _present2 {
		_fieldSize0, err := value.Peer.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "peer", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "peer", err)
		}
	}
	if value.ReceiverID == nil {
		return 0, encodeError("ephemeral.editMessage", "receiver_id", ErrNilObject)
	}
	_fieldSize1, err := value.ReceiverID.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.editMessage", "receiver_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("ephemeral.editMessage", "receiver_id", err)
	}
	size += 4
	if _present3 {
		_fieldSize2, err := bytesEncodedSize(len(*value.Message))
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "message", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "message", err)
		}
	}
	if _present4 {
		_fieldSize3, err := value.Media.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "media", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize3)
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "media", err)
		}
	}
	if _present5 {
		if err := validateVectorLength(len(value.Entities)); err != nil {
			return 0, encodeError("ephemeral.editMessage", "entities", err)
		}
		_vectorSize4 := 8
		for _index4 := range value.Entities {
			_fieldSize5, err := value.Entities[_index4].encodedSize()
			if err != nil {
				return 0, encodeError("ephemeral.editMessage", "entities", err)
			}
			_vectorSize4, err = checkedEncodedSizeAdd(_vectorSize4, _fieldSize5)
			if err != nil {
				return 0, encodeError("ephemeral.editMessage", "entities", err)
			}
		}
		_totalSize4, err := checkedEncodedSizeAdd(size, _vectorSize4)
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "entities", err)
		}
		size = _totalSize4
	}
	if _present6 {
		_fieldSize6, err := value.ReplyMarkup.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "reply_markup", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize6)
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "reply_markup", err)
		}
	}
	if _present7 {
		_fieldSize7, err := value.RichMessage.encodedSize()
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "rich_message", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize7)
		if err != nil {
			return 0, encodeError("ephemeral.editMessage", "rich_message", err)
		}
	}
	return size, nil
}

func (value *EphemeralEditMessageRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.editMessage", "", ErrNilObject)
	}
	output.putUint32(EphemeralEditMessageRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralEditMessageRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.editMessage", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.InvertMedia
	if _present0 {
		_flags0 |= uint32(1) << 5
	}
	_present1 := value.Welcome
	if _present1 {
		_flags0 |= uint32(1) << 6
	}
	_present2 := value.Peer != nil
	if _present2 {
		_flags0 |= uint32(1) << 7
	}
	_present3 := value.Message != nil
	if _present3 {
		_flags0 |= uint32(1) << 0
	}
	_present4 := value.Media != nil
	if _present4 {
		_flags0 |= uint32(1) << 3
	}
	_present5 := value.Entities != nil
	if _present5 {
		_flags0 |= uint32(1) << 1
	}
	_present6 := value.ReplyMarkup != nil
	if _present6 {
		_flags0 |= uint32(1) << 2
	}
	_present7 := value.RichMessage != nil
	if _present7 {
		_flags0 |= uint32(1) << 4
	}
	output.putUint32(_flags0)
	if _present2 {
		_output0, err := value.Peer.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.editMessage", "peer", err)
		}
		output = _output0
	}
	if value.ReceiverID == nil {
		return output, encodeError("ephemeral.editMessage", "receiver_id", ErrNilObject)
	}
	_output1, err := value.ReceiverID.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.editMessage", "receiver_id", err)
	}
	output = _output1
	output.putInt32(value.ID)
	if _present3 {
		if err := output.putString(*value.Message); err != nil {
			return output, encodeError("ephemeral.editMessage", "message", err)
		}
	}
	if _present4 {
		_output2, err := value.Media.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.editMessage", "media", err)
		}
		output = _output2
	}
	if _present5 {
		if err := output.putVectorHeader(len(value.Entities)); err != nil {
			return output, encodeError("ephemeral.editMessage", "entities", err)
		}
		for _index := range value.Entities {
			_output3, err := value.Entities[_index].encode(output)
			if err != nil {
				return output, encodeError("ephemeral.editMessage", "entities", err)
			}
			output = _output3
		}
	}
	if _present6 {
		_output4, err := value.ReplyMarkup.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.editMessage", "reply_markup", err)
		}
		output = _output4
	}
	if _present7 {
		_output5, err := value.RichMessage.encode(output)
		if err != nil {
			return output, encodeError("ephemeral.editMessage", "rich_message", err)
		}
		output = _output5
	}
	return output, nil
}

func (request *EphemeralEditMessageRequest) decodeResult(state decoder) (UpdatesClass, decoder, error) {
	var zero UpdatesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result UpdatesClass
	_field0, err := decodeUpdatesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// EphemeralGetWelcomeMessagesRequest represents TL method ephemeral.getWelcomeMessages (ID 0xdb9ac18d).
type EphemeralGetWelcomeMessagesRequest struct {
	Peer InputPeerClass
	Hash int64
}

// EphemeralGetWelcomeMessagesRequestConstructorID is the TL constructor ID for ephemeral.getWelcomeMessages.
const EphemeralGetWelcomeMessagesRequestConstructorID uint32 = 0xdb9ac18d

// ConstructorID returns the TL constructor ID.
func (*EphemeralGetWelcomeMessagesRequest) ConstructorID() uint32 {
	return EphemeralGetWelcomeMessagesRequestConstructorID
}

func (*EphemeralGetWelcomeMessagesRequest) requestResult(EphemeralWelcomeMessagesClass) {}

func (value *EphemeralGetWelcomeMessagesRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.getWelcomeMessages", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralGetWelcomeMessagesRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.getWelcomeMessages", "", ErrNilObject)
	}
	size := 0
	if value.Peer == nil {
		return 0, encodeError("ephemeral.getWelcomeMessages", "peer", ErrNilObject)
	}
	_fieldSize0, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.getWelcomeMessages", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("ephemeral.getWelcomeMessages", "peer", err)
	}
	size += 8
	return size, nil
}

func (value *EphemeralGetWelcomeMessagesRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.getWelcomeMessages", "", ErrNilObject)
	}
	output.putUint32(EphemeralGetWelcomeMessagesRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralGetWelcomeMessagesRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.getWelcomeMessages", "", ErrNilObject)
	}
	if value.Peer == nil {
		return output, encodeError("ephemeral.getWelcomeMessages", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.getWelcomeMessages", "peer", err)
	}
	output = _output0
	output.putInt64(value.Hash)
	return output, nil
}

func (request *EphemeralGetWelcomeMessagesRequest) decodeResult(state decoder) (EphemeralWelcomeMessagesClass, decoder, error) {
	var zero EphemeralWelcomeMessagesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result EphemeralWelcomeMessagesClass
	_field0, err := decodeEphemeralWelcomeMessagesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// EphemeralDeleteWelcomeMessageRequest represents TL method ephemeral.deleteWelcomeMessage (ID 0xe882a9e1).
type EphemeralDeleteWelcomeMessageRequest struct {
	Peer InputPeerClass
	ID   int32
}

// EphemeralDeleteWelcomeMessageRequestConstructorID is the TL constructor ID for ephemeral.deleteWelcomeMessage.
const EphemeralDeleteWelcomeMessageRequestConstructorID uint32 = 0xe882a9e1

// ConstructorID returns the TL constructor ID.
func (*EphemeralDeleteWelcomeMessageRequest) ConstructorID() uint32 {
	return EphemeralDeleteWelcomeMessageRequestConstructorID
}

func (*EphemeralDeleteWelcomeMessageRequest) requestResult(bool) {}

func (value *EphemeralDeleteWelcomeMessageRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.deleteWelcomeMessage", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *EphemeralDeleteWelcomeMessageRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("ephemeral.deleteWelcomeMessage", "", ErrNilObject)
	}
	size := 0
	if value.Peer == nil {
		return 0, encodeError("ephemeral.deleteWelcomeMessage", "peer", ErrNilObject)
	}
	_fieldSize0, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("ephemeral.deleteWelcomeMessage", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("ephemeral.deleteWelcomeMessage", "peer", err)
	}
	size += 4
	return size, nil
}

func (value *EphemeralDeleteWelcomeMessageRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.deleteWelcomeMessage", "", ErrNilObject)
	}
	output.putUint32(EphemeralDeleteWelcomeMessageRequestConstructorID)
	return value.encodeBody(output)
}

func (value *EphemeralDeleteWelcomeMessageRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("ephemeral.deleteWelcomeMessage", "", ErrNilObject)
	}
	if value.Peer == nil {
		return output, encodeError("ephemeral.deleteWelcomeMessage", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("ephemeral.deleteWelcomeMessage", "peer", err)
	}
	output = _output0
	output.putInt32(value.ID)
	return output, nil
}

func (request *EphemeralDeleteWelcomeMessageRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}
