// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 230

package tl

// OnrampAvailabilityClass is the TL union OnrampAvailability.
type OnrampAvailabilityClass interface {
	Object
	isOnrampAvailabilityClass()
}

// decodeOnrampAvailabilityClass decodes the TL union OnrampAvailability.
func decodeOnrampAvailabilityClass(input *decoder) (OnrampAvailabilityClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OnrampAvailabilityConstructorID:
		value, err := decodeOnrampAvailability(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OnrampAvailabilityClass", constructor)
	}
}

// OnrampLimitsClass is the TL union OnrampLimits.
type OnrampLimitsClass interface {
	Object
	isOnrampLimitsClass()
}

// decodeOnrampLimitsClass decodes the TL union OnrampLimits.
func decodeOnrampLimitsClass(input *decoder) (OnrampLimitsClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OnrampLimitsConstructorID:
		value, err := decodeOnrampLimits(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OnrampLimitsClass", constructor)
	}
}

// OnrampMethodAvailabilityClass is the TL union OnrampMethodAvailability.
type OnrampMethodAvailabilityClass interface {
	Object
	isOnrampMethodAvailabilityClass()
}

// decodeOnrampMethodAvailabilityClass decodes the TL union OnrampMethodAvailability.
func decodeOnrampMethodAvailabilityClass(input *decoder) (OnrampMethodAvailabilityClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OnrampMethodAvailabilityConstructorID:
		value, err := decodeOnrampMethodAvailability(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OnrampMethodAvailabilityClass", constructor)
	}
}

// OnrampProviderInfoClass is the TL union OnrampProviderInfo.
type OnrampProviderInfoClass interface {
	Object
	isOnrampProviderInfoClass()
}

// decodeOnrampProviderInfoClass decodes the TL union OnrampProviderInfo.
func decodeOnrampProviderInfoClass(input *decoder) (OnrampProviderInfoClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OnrampProviderInfoConstructorID:
		value, err := decodeOnrampProviderInfo(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OnrampProviderInfoClass", constructor)
	}
}

// OnrampQuoteClass is the TL union OnrampQuote.
type OnrampQuoteClass interface {
	Object
	isOnrampQuoteClass()
}

// decodeOnrampQuoteClass decodes the TL union OnrampQuote.
func decodeOnrampQuoteClass(input *decoder) (OnrampQuoteClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OnrampQuoteConstructorID:
		value, err := decodeOnrampQuote(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OnrampQuoteClass", constructor)
	}
}

// OnrampSessionClass is the TL union OnrampSession.
type OnrampSessionClass interface {
	Object
	isOnrampSessionClass()
}

// decodeOnrampSessionClass decodes the TL union OnrampSession.
func decodeOnrampSessionClass(input *decoder) (OnrampSessionClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OnrampSessionConstructorID:
		value, err := decodeOnrampSession(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OnrampSessionClass", constructor)
	}
}

// OutboxReadDateClass is the TL union OutboxReadDate.
type OutboxReadDateClass interface {
	Object
	isOutboxReadDateClass()
}

// decodeOutboxReadDateClass decodes the TL union OutboxReadDate.
func decodeOutboxReadDateClass(input *decoder) (OutboxReadDateClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case OutboxReadDateConstructorID:
		value, err := decodeOutboxReadDate(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "OutboxReadDateClass", constructor)
	}
}

// OnrampProviderInfo represents TL class onrampProviderInfo (ID 0x0dc27582).
type OnrampProviderInfo struct {
	SupportsBaseCurrencies bool
	SupportsLimits         bool
	SupportsQuote          bool
	ID                     string
	Name                   string
	CryptoCurrencies       []string
}

// OnrampProviderInfoConstructorID is the TL constructor ID for onrampProviderInfo.
const OnrampProviderInfoConstructorID uint32 = 0x0dc27582

// ConstructorID returns the TL constructor ID.
func (*OnrampProviderInfo) ConstructorID() uint32 {
	return OnrampProviderInfoConstructorID
}

func (*OnrampProviderInfo) isOnrampProviderInfoClass() {
}

func (value *OnrampProviderInfo) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampProviderInfo", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OnrampProviderInfo) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampProviderInfo", "", ErrNilObject)
	}
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.ID))
	if err != nil {
		return 0, encodeError("onrampProviderInfo", "id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("onrampProviderInfo", "id", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.Name))
	if err != nil {
		return 0, encodeError("onrampProviderInfo", "name", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("onrampProviderInfo", "name", err)
	}
	if err := validateVectorLength(len(value.CryptoCurrencies)); err != nil {
		return 0, encodeError("onrampProviderInfo", "crypto_currencies", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.CryptoCurrencies {
		_fieldSize3, err := bytesEncodedSize(len(value.CryptoCurrencies[_index2]))
		if err != nil {
			return 0, encodeError("onrampProviderInfo", "crypto_currencies", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("onrampProviderInfo", "crypto_currencies", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("onrampProviderInfo", "crypto_currencies", err)
	}
	size = _totalSize2
	return size, nil
}

func (value *OnrampProviderInfo) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampProviderInfo", "", ErrNilObject)
	}
	output.putUint32(OnrampProviderInfoConstructorID)
	return value.encodeBody(output)
}

func (value *OnrampProviderInfo) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampProviderInfo", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.SupportsBaseCurrencies
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.SupportsLimits
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.SupportsQuote
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	output.putUint32(_flags0)
	if err := output.putString(value.ID); err != nil {
		return output, encodeError("onrampProviderInfo", "id", err)
	}
	if err := output.putString(value.Name); err != nil {
		return output, encodeError("onrampProviderInfo", "name", err)
	}
	if err := output.putVectorHeader(len(value.CryptoCurrencies)); err != nil {
		return output, encodeError("onrampProviderInfo", "crypto_currencies", err)
	}
	for _index := range value.CryptoCurrencies {
		if err := output.putString(value.CryptoCurrencies[_index]); err != nil {
			return output, encodeError("onrampProviderInfo", "crypto_currencies", err)
		}
	}
	return output, nil
}

// decodeOnrampProviderInfo decodes a TL OnrampProviderInfo.
func decodeOnrampProviderInfo(input *decoder) (*OnrampProviderInfo, error) {
	if err := input.reserveAllocation("onrampProviderInfo", decodedAllocationSize(40, 80)); err != nil {
		return nil, err
	}
	value := new(OnrampProviderInfo)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OnrampProviderInfo) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.SupportsBaseCurrencies = _flags0&(uint32(1)<<0) != 0
	value.SupportsLimits = _flags0&(uint32(1)<<1) != 0
	value.SupportsQuote = _flags0&(uint32(1)<<2) != 0
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.ID = _field0
	_field1, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.Name = _field1
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("onrampProviderInfo.crypto_currencies", _count2, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.CryptoCurrencies = make([]string, _count2)
	for _index2 := range value.CryptoCurrencies {
		_field3, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		value.CryptoCurrencies[_index2] = _field3
	}
	input.leave()
	return nil
}

// OutboxReadDate represents TL class outboxReadDate (ID 0x3bb842ac).
type OutboxReadDate struct {
	Date int32
}

// OutboxReadDateConstructorID is the TL constructor ID for outboxReadDate.
const OutboxReadDateConstructorID uint32 = 0x3bb842ac

// ConstructorID returns the TL constructor ID.
func (*OutboxReadDate) ConstructorID() uint32 {
	return OutboxReadDateConstructorID
}

func (*OutboxReadDate) isOutboxReadDateClass() {
}

func (value *OutboxReadDate) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("outboxReadDate", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OutboxReadDate) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("outboxReadDate", "", ErrNilObject)
	}
	size := 0
	size += 4
	return size, nil
}

func (value *OutboxReadDate) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("outboxReadDate", "", ErrNilObject)
	}
	output.putUint32(OutboxReadDateConstructorID)
	return value.encodeBody(output)
}

func (value *OutboxReadDate) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("outboxReadDate", "", ErrNilObject)
	}
	output.putInt32(value.Date)
	return output, nil
}

// decodeOutboxReadDate decodes a TL OutboxReadDate.
func decodeOutboxReadDate(input *decoder) (*OutboxReadDate, error) {
	if err := input.reserveAllocation("outboxReadDate", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(OutboxReadDate)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OutboxReadDate) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Date = _field0
	input.leave()
	return nil
}

// OnrampQuote represents TL class onrampQuote (ID 0x7a8011e9).
type OnrampQuote struct {
	BaseCurrency     string
	BaseAmount       string
	CryptoCurrency   string
	CryptoAmount     string
	CryptoPrice      string
	FeeAmount        string
	ExtraFeeAmount   string
	NetworkFeeAmount string
	TotalAmount      string
	PaymentMethod    string
	ExpiresDate      int32
}

// OnrampQuoteConstructorID is the TL constructor ID for onrampQuote.
const OnrampQuoteConstructorID uint32 = 0x7a8011e9

// ConstructorID returns the TL constructor ID.
func (*OnrampQuote) ConstructorID() uint32 {
	return OnrampQuoteConstructorID
}

func (*OnrampQuote) isOnrampQuoteClass() {
}

func (value *OnrampQuote) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampQuote", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OnrampQuote) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampQuote", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.BaseCurrency))
	if err != nil {
		return 0, encodeError("onrampQuote", "base_currency", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("onrampQuote", "base_currency", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.BaseAmount))
	if err != nil {
		return 0, encodeError("onrampQuote", "base_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("onrampQuote", "base_amount", err)
	}
	_fieldSize2, err := bytesEncodedSize(len(value.CryptoCurrency))
	if err != nil {
		return 0, encodeError("onrampQuote", "crypto_currency", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("onrampQuote", "crypto_currency", err)
	}
	_fieldSize3, err := bytesEncodedSize(len(value.CryptoAmount))
	if err != nil {
		return 0, encodeError("onrampQuote", "crypto_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize3)
	if err != nil {
		return 0, encodeError("onrampQuote", "crypto_amount", err)
	}
	_fieldSize4, err := bytesEncodedSize(len(value.CryptoPrice))
	if err != nil {
		return 0, encodeError("onrampQuote", "crypto_price", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize4)
	if err != nil {
		return 0, encodeError("onrampQuote", "crypto_price", err)
	}
	_fieldSize5, err := bytesEncodedSize(len(value.FeeAmount))
	if err != nil {
		return 0, encodeError("onrampQuote", "fee_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize5)
	if err != nil {
		return 0, encodeError("onrampQuote", "fee_amount", err)
	}
	_fieldSize6, err := bytesEncodedSize(len(value.ExtraFeeAmount))
	if err != nil {
		return 0, encodeError("onrampQuote", "extra_fee_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize6)
	if err != nil {
		return 0, encodeError("onrampQuote", "extra_fee_amount", err)
	}
	_fieldSize7, err := bytesEncodedSize(len(value.NetworkFeeAmount))
	if err != nil {
		return 0, encodeError("onrampQuote", "network_fee_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize7)
	if err != nil {
		return 0, encodeError("onrampQuote", "network_fee_amount", err)
	}
	_fieldSize8, err := bytesEncodedSize(len(value.TotalAmount))
	if err != nil {
		return 0, encodeError("onrampQuote", "total_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize8)
	if err != nil {
		return 0, encodeError("onrampQuote", "total_amount", err)
	}
	_fieldSize9, err := bytesEncodedSize(len(value.PaymentMethod))
	if err != nil {
		return 0, encodeError("onrampQuote", "payment_method", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize9)
	if err != nil {
		return 0, encodeError("onrampQuote", "payment_method", err)
	}
	size += 4
	return size, nil
}

func (value *OnrampQuote) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampQuote", "", ErrNilObject)
	}
	output.putUint32(OnrampQuoteConstructorID)
	return value.encodeBody(output)
}

func (value *OnrampQuote) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampQuote", "", ErrNilObject)
	}
	if err := output.putString(value.BaseCurrency); err != nil {
		return output, encodeError("onrampQuote", "base_currency", err)
	}
	if err := output.putString(value.BaseAmount); err != nil {
		return output, encodeError("onrampQuote", "base_amount", err)
	}
	if err := output.putString(value.CryptoCurrency); err != nil {
		return output, encodeError("onrampQuote", "crypto_currency", err)
	}
	if err := output.putString(value.CryptoAmount); err != nil {
		return output, encodeError("onrampQuote", "crypto_amount", err)
	}
	if err := output.putString(value.CryptoPrice); err != nil {
		return output, encodeError("onrampQuote", "crypto_price", err)
	}
	if err := output.putString(value.FeeAmount); err != nil {
		return output, encodeError("onrampQuote", "fee_amount", err)
	}
	if err := output.putString(value.ExtraFeeAmount); err != nil {
		return output, encodeError("onrampQuote", "extra_fee_amount", err)
	}
	if err := output.putString(value.NetworkFeeAmount); err != nil {
		return output, encodeError("onrampQuote", "network_fee_amount", err)
	}
	if err := output.putString(value.TotalAmount); err != nil {
		return output, encodeError("onrampQuote", "total_amount", err)
	}
	if err := output.putString(value.PaymentMethod); err != nil {
		return output, encodeError("onrampQuote", "payment_method", err)
	}
	output.putInt32(value.ExpiresDate)
	return output, nil
}

// decodeOnrampQuote decodes a TL OnrampQuote.
func decodeOnrampQuote(input *decoder) (*OnrampQuote, error) {
	if err := input.reserveAllocation("onrampQuote", decodedAllocationSize(84, 168)); err != nil {
		return nil, err
	}
	value := new(OnrampQuote)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OnrampQuote) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.BaseCurrency = _field0
	_field1, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.BaseAmount = _field1
	_field2, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CryptoCurrency = _field2
	_field3, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CryptoAmount = _field3
	_field4, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CryptoPrice = _field4
	_field5, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.FeeAmount = _field5
	_field6, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.ExtraFeeAmount = _field6
	_field7, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.NetworkFeeAmount = _field7
	_field8, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.TotalAmount = _field8
	_field9, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.PaymentMethod = _field9
	_field10, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.ExpiresDate = _field10
	input.leave()
	return nil
}

// OnrampLimits represents TL class onrampLimits (ID 0x7be2677e).
type OnrampLimits struct {
	BaseCurrency    string
	BaseMinAmount   string
	BaseMaxAmount   string
	CryptoMinAmount string
	CryptoMaxAmount string
	PaymentMethod   string
}

// OnrampLimitsConstructorID is the TL constructor ID for onrampLimits.
const OnrampLimitsConstructorID uint32 = 0x7be2677e

// ConstructorID returns the TL constructor ID.
func (*OnrampLimits) ConstructorID() uint32 {
	return OnrampLimitsConstructorID
}

func (*OnrampLimits) isOnrampLimitsClass() {
}

func (value *OnrampLimits) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampLimits", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OnrampLimits) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampLimits", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.BaseCurrency))
	if err != nil {
		return 0, encodeError("onrampLimits", "base_currency", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("onrampLimits", "base_currency", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.BaseMinAmount))
	if err != nil {
		return 0, encodeError("onrampLimits", "base_min_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("onrampLimits", "base_min_amount", err)
	}
	_fieldSize2, err := bytesEncodedSize(len(value.BaseMaxAmount))
	if err != nil {
		return 0, encodeError("onrampLimits", "base_max_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("onrampLimits", "base_max_amount", err)
	}
	_fieldSize3, err := bytesEncodedSize(len(value.CryptoMinAmount))
	if err != nil {
		return 0, encodeError("onrampLimits", "crypto_min_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize3)
	if err != nil {
		return 0, encodeError("onrampLimits", "crypto_min_amount", err)
	}
	_fieldSize4, err := bytesEncodedSize(len(value.CryptoMaxAmount))
	if err != nil {
		return 0, encodeError("onrampLimits", "crypto_max_amount", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize4)
	if err != nil {
		return 0, encodeError("onrampLimits", "crypto_max_amount", err)
	}
	_fieldSize5, err := bytesEncodedSize(len(value.PaymentMethod))
	if err != nil {
		return 0, encodeError("onrampLimits", "payment_method", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize5)
	if err != nil {
		return 0, encodeError("onrampLimits", "payment_method", err)
	}
	return size, nil
}

func (value *OnrampLimits) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampLimits", "", ErrNilObject)
	}
	output.putUint32(OnrampLimitsConstructorID)
	return value.encodeBody(output)
}

func (value *OnrampLimits) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampLimits", "", ErrNilObject)
	}
	if err := output.putString(value.BaseCurrency); err != nil {
		return output, encodeError("onrampLimits", "base_currency", err)
	}
	if err := output.putString(value.BaseMinAmount); err != nil {
		return output, encodeError("onrampLimits", "base_min_amount", err)
	}
	if err := output.putString(value.BaseMaxAmount); err != nil {
		return output, encodeError("onrampLimits", "base_max_amount", err)
	}
	if err := output.putString(value.CryptoMinAmount); err != nil {
		return output, encodeError("onrampLimits", "crypto_min_amount", err)
	}
	if err := output.putString(value.CryptoMaxAmount); err != nil {
		return output, encodeError("onrampLimits", "crypto_max_amount", err)
	}
	if err := output.putString(value.PaymentMethod); err != nil {
		return output, encodeError("onrampLimits", "payment_method", err)
	}
	return output, nil
}

// decodeOnrampLimits decodes a TL OnrampLimits.
func decodeOnrampLimits(input *decoder) (*OnrampLimits, error) {
	if err := input.reserveAllocation("onrampLimits", decodedAllocationSize(48, 96)); err != nil {
		return nil, err
	}
	value := new(OnrampLimits)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OnrampLimits) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.BaseCurrency = _field0
	_field1, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.BaseMinAmount = _field1
	_field2, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.BaseMaxAmount = _field2
	_field3, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CryptoMinAmount = _field3
	_field4, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CryptoMaxAmount = _field4
	_field5, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.PaymentMethod = _field5
	input.leave()
	return nil
}

// OnrampMethodAvailability represents TL class onrampMethodAvailability (ID 0x9ec8c6a8).
type OnrampMethodAvailability struct {
	Available     bool
	PaymentMethod string
}

// OnrampMethodAvailabilityConstructorID is the TL constructor ID for onrampMethodAvailability.
const OnrampMethodAvailabilityConstructorID uint32 = 0x9ec8c6a8

// ConstructorID returns the TL constructor ID.
func (*OnrampMethodAvailability) ConstructorID() uint32 {
	return OnrampMethodAvailabilityConstructorID
}

func (*OnrampMethodAvailability) isOnrampMethodAvailabilityClass() {
}

func (value *OnrampMethodAvailability) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampMethodAvailability", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OnrampMethodAvailability) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampMethodAvailability", "", ErrNilObject)
	}
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.PaymentMethod))
	if err != nil {
		return 0, encodeError("onrampMethodAvailability", "payment_method", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("onrampMethodAvailability", "payment_method", err)
	}
	return size, nil
}

func (value *OnrampMethodAvailability) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampMethodAvailability", "", ErrNilObject)
	}
	output.putUint32(OnrampMethodAvailabilityConstructorID)
	return value.encodeBody(output)
}

func (value *OnrampMethodAvailability) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampMethodAvailability", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Available
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	if err := output.putString(value.PaymentMethod); err != nil {
		return output, encodeError("onrampMethodAvailability", "payment_method", err)
	}
	return output, nil
}

// decodeOnrampMethodAvailability decodes a TL OnrampMethodAvailability.
func decodeOnrampMethodAvailability(input *decoder) (*OnrampMethodAvailability, error) {
	if err := input.reserveAllocation("onrampMethodAvailability", decodedAllocationSize(12, 24)); err != nil {
		return nil, err
	}
	value := new(OnrampMethodAvailability)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OnrampMethodAvailability) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Available = _flags0&(uint32(1)<<0) != 0
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.PaymentMethod = _field0
	input.leave()
	return nil
}

// OnrampSession represents TL class onrampSession (ID 0xd1e42e24).
type OnrampSession struct {
	Provider    string
	SessionID   string
	URL         string
	ExpiresDate int32
}

// OnrampSessionConstructorID is the TL constructor ID for onrampSession.
const OnrampSessionConstructorID uint32 = 0xd1e42e24

// ConstructorID returns the TL constructor ID.
func (*OnrampSession) ConstructorID() uint32 {
	return OnrampSessionConstructorID
}

func (*OnrampSession) isOnrampSessionClass() {
}

func (value *OnrampSession) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampSession", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OnrampSession) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampSession", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.Provider))
	if err != nil {
		return 0, encodeError("onrampSession", "provider", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("onrampSession", "provider", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.SessionID))
	if err != nil {
		return 0, encodeError("onrampSession", "session_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("onrampSession", "session_id", err)
	}
	_fieldSize2, err := bytesEncodedSize(len(value.URL))
	if err != nil {
		return 0, encodeError("onrampSession", "url", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("onrampSession", "url", err)
	}
	size += 4
	return size, nil
}

func (value *OnrampSession) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampSession", "", ErrNilObject)
	}
	output.putUint32(OnrampSessionConstructorID)
	return value.encodeBody(output)
}

func (value *OnrampSession) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampSession", "", ErrNilObject)
	}
	if err := output.putString(value.Provider); err != nil {
		return output, encodeError("onrampSession", "provider", err)
	}
	if err := output.putString(value.SessionID); err != nil {
		return output, encodeError("onrampSession", "session_id", err)
	}
	if err := output.putString(value.URL); err != nil {
		return output, encodeError("onrampSession", "url", err)
	}
	output.putInt32(value.ExpiresDate)
	return output, nil
}

// decodeOnrampSession decodes a TL OnrampSession.
func decodeOnrampSession(input *decoder) (*OnrampSession, error) {
	if err := input.reserveAllocation("onrampSession", decodedAllocationSize(28, 56)); err != nil {
		return nil, err
	}
	value := new(OnrampSession)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OnrampSession) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.Provider = _field0
	_field1, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.SessionID = _field1
	_field2, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.URL = _field2
	_field3, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.ExpiresDate = _field3
	input.leave()
	return nil
}

// OnrampAvailability represents TL class onrampAvailability (ID 0xf9c84973).
type OnrampAvailability struct {
	Allowed     bool
	BuyAllowed  bool
	CountryCode string
	State       *string
	Methods     []OnrampMethodAvailabilityClass
}

// OnrampAvailabilityConstructorID is the TL constructor ID for onrampAvailability.
const OnrampAvailabilityConstructorID uint32 = 0xf9c84973

// ConstructorID returns the TL constructor ID.
func (*OnrampAvailability) ConstructorID() uint32 {
	return OnrampAvailabilityConstructorID
}

func (*OnrampAvailability) isOnrampAvailabilityClass() {
}

func (value *OnrampAvailability) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampAvailability", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *OnrampAvailability) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("onrampAvailability", "", ErrNilObject)
	}
	_present2 := value.State != nil
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.CountryCode))
	if err != nil {
		return 0, encodeError("onrampAvailability", "country_code", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("onrampAvailability", "country_code", err)
	}
	if _present2 {
		_fieldSize1, err := bytesEncodedSize(len(*value.State))
		if err != nil {
			return 0, encodeError("onrampAvailability", "state", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("onrampAvailability", "state", err)
		}
	}
	if err := validateVectorLength(len(value.Methods)); err != nil {
		return 0, encodeError("onrampAvailability", "methods", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.Methods {
		if value.Methods[_index2] == nil {
			return 0, encodeError("onrampAvailability", "methods", ErrNilObject)
		}
		_fieldSize3, err := value.Methods[_index2].encodedSize()
		if err != nil {
			return 0, encodeError("onrampAvailability", "methods", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("onrampAvailability", "methods", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("onrampAvailability", "methods", err)
	}
	size = _totalSize2
	return size, nil
}

func (value *OnrampAvailability) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampAvailability", "", ErrNilObject)
	}
	output.putUint32(OnrampAvailabilityConstructorID)
	return value.encodeBody(output)
}

func (value *OnrampAvailability) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("onrampAvailability", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Allowed
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.BuyAllowed
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.State != nil
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	output.putUint32(_flags0)
	if err := output.putString(value.CountryCode); err != nil {
		return output, encodeError("onrampAvailability", "country_code", err)
	}
	if _present2 {
		if err := output.putString(*value.State); err != nil {
			return output, encodeError("onrampAvailability", "state", err)
		}
	}
	if err := output.putVectorHeader(len(value.Methods)); err != nil {
		return output, encodeError("onrampAvailability", "methods", err)
	}
	for _index := range value.Methods {
		if value.Methods[_index] == nil {
			return output, encodeError("onrampAvailability", "methods", ErrNilObject)
		}
		_output0, err := value.Methods[_index].encode(output)
		if err != nil {
			return output, encodeError("onrampAvailability", "methods", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeOnrampAvailability decodes a TL OnrampAvailability.
func decodeOnrampAvailability(input *decoder) (*OnrampAvailability, error) {
	if err := input.reserveAllocation("onrampAvailability", decodedAllocationSize(32, 64)); err != nil {
		return nil, err
	}
	value := new(OnrampAvailability)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *OnrampAvailability) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Allowed = _flags0&(uint32(1)<<0) != 0
	value.BuyAllowed = _flags0&(uint32(1)<<1) != 0
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CountryCode = _field0
	if _flags0&(uint32(1)<<2) != 0 {
		_field1, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("onrampAvailability.state", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.State = &_field1
	}
	_count2, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("onrampAvailability.methods", _count2, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Methods = make([]OnrampMethodAvailabilityClass, _count2)
	for _index2 := range value.Methods {
		_field3, err := decodeOnrampMethodAvailabilityClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Methods[_index2] = _field3
	}
	input.leave()
	return nil
}
