// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// GameClass is the TL union Game.
type GameClass interface {
	Object
	isGameClass()
}

// decodeGameClass decodes the TL union Game.
func decodeGameClass(input *decoder) (GameClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GameConstructorID:
		value, err := decodeGame(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GameClass", constructor)
	}
}

// GeoPointClass is the TL union GeoPoint.
type GeoPointClass interface {
	Object
	isGeoPointClass()
}

// decodeGeoPointClass decodes the TL union GeoPoint.
func decodeGeoPointClass(input *decoder) (GeoPointClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GeoPointEmptyConstructorID:
		value, err := decodeGeoPointEmpty(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case GeoPointConstructorID:
		value, err := decodeGeoPoint(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GeoPointClass", constructor)
	}
}

// GeoPointAddressClass is the TL union GeoPointAddress.
type GeoPointAddressClass interface {
	Object
	isGeoPointAddressClass()
}

// decodeGeoPointAddressClass decodes the TL union GeoPointAddress.
func decodeGeoPointAddressClass(input *decoder) (GeoPointAddressClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GeoPointAddressConstructorID:
		value, err := decodeGeoPointAddress(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GeoPointAddressClass", constructor)
	}
}

// GlobalPrivacySettingsClass is the TL union GlobalPrivacySettings.
type GlobalPrivacySettingsClass interface {
	Object
	isGlobalPrivacySettingsClass()
}

// decodeGlobalPrivacySettingsClass decodes the TL union GlobalPrivacySettings.
func decodeGlobalPrivacySettingsClass(input *decoder) (GlobalPrivacySettingsClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GlobalPrivacySettingsConstructorID:
		value, err := decodeGlobalPrivacySettings(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GlobalPrivacySettingsClass", constructor)
	}
}

// GroupCallClass is the TL union GroupCall.
type GroupCallClass interface {
	Object
	isGroupCallClass()
}

// decodeGroupCallClass decodes the TL union GroupCall.
func decodeGroupCallClass(input *decoder) (GroupCallClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallDiscardedConstructorID:
		value, err := decodeGroupCallDiscarded(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case GroupCallConstructorID:
		value, err := decodeGroupCall(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallClass", constructor)
	}
}

// GroupCallDonorClass is the TL union GroupCallDonor.
type GroupCallDonorClass interface {
	Object
	isGroupCallDonorClass()
}

// decodeGroupCallDonorClass decodes the TL union GroupCallDonor.
func decodeGroupCallDonorClass(input *decoder) (GroupCallDonorClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallDonorConstructorID:
		value, err := decodeGroupCallDonor(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallDonorClass", constructor)
	}
}

// GroupCallMessageClass is the TL union GroupCallMessage.
type GroupCallMessageClass interface {
	Object
	isGroupCallMessageClass()
}

// decodeGroupCallMessageClass decodes the TL union GroupCallMessage.
func decodeGroupCallMessageClass(input *decoder) (GroupCallMessageClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallMessageConstructorID:
		value, err := decodeGroupCallMessage(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallMessageClass", constructor)
	}
}

// GroupCallParticipantClass is the TL union GroupCallParticipant.
type GroupCallParticipantClass interface {
	Object
	isGroupCallParticipantClass()
}

// decodeGroupCallParticipantClass decodes the TL union GroupCallParticipant.
func decodeGroupCallParticipantClass(input *decoder) (GroupCallParticipantClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallParticipantConstructorID:
		value, err := decodeGroupCallParticipant(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallParticipantClass", constructor)
	}
}

// GroupCallParticipantVideoClass is the TL union GroupCallParticipantVideo.
type GroupCallParticipantVideoClass interface {
	Object
	isGroupCallParticipantVideoClass()
}

// decodeGroupCallParticipantVideoClass decodes the TL union GroupCallParticipantVideo.
func decodeGroupCallParticipantVideoClass(input *decoder) (GroupCallParticipantVideoClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallParticipantVideoConstructorID:
		value, err := decodeGroupCallParticipantVideo(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallParticipantVideoClass", constructor)
	}
}

// GroupCallParticipantVideoSourceGroupClass is the TL union GroupCallParticipantVideoSourceGroup.
type GroupCallParticipantVideoSourceGroupClass interface {
	Object
	isGroupCallParticipantVideoSourceGroupClass()
}

// decodeGroupCallParticipantVideoSourceGroupClass decodes the TL union GroupCallParticipantVideoSourceGroup.
func decodeGroupCallParticipantVideoSourceGroupClass(input *decoder) (GroupCallParticipantVideoSourceGroupClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallParticipantVideoSourceGroupConstructorID:
		value, err := decodeGroupCallParticipantVideoSourceGroup(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallParticipantVideoSourceGroupClass", constructor)
	}
}

// GroupCallStreamChannelClass is the TL union GroupCallStreamChannel.
type GroupCallStreamChannelClass interface {
	Object
	isGroupCallStreamChannelClass()
}

// decodeGroupCallStreamChannelClass decodes the TL union GroupCallStreamChannel.
func decodeGroupCallStreamChannelClass(input *decoder) (GroupCallStreamChannelClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case GroupCallStreamChannelConstructorID:
		value, err := decodeGroupCallStreamChannel(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "GroupCallStreamChannelClass", constructor)
	}
}

// GeoPointEmpty represents TL class geoPointEmpty (ID 0x1117dd5f).
type GeoPointEmpty struct {
}

// GeoPointEmptyConstructorID is the TL constructor ID for geoPointEmpty.
const GeoPointEmptyConstructorID uint32 = 0x1117dd5f

// ConstructorID returns the TL constructor ID.
func (*GeoPointEmpty) ConstructorID() uint32 {
	return GeoPointEmptyConstructorID
}

func (*GeoPointEmpty) isGeoPointClass() {
}

func (value *GeoPointEmpty) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("geoPointEmpty", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GeoPointEmpty) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("geoPointEmpty", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *GeoPointEmpty) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("geoPointEmpty", "", ErrNilObject)
	}
	output.putUint32(GeoPointEmptyConstructorID)
	return value.encodeBody(output)
}

func (value *GeoPointEmpty) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("geoPointEmpty", "", ErrNilObject)
	}
	return output, nil
}

// decodeGeoPointEmpty decodes a TL GeoPoint.
func decodeGeoPointEmpty(input *decoder) (*GeoPointEmpty, error) {
	if err := input.reserveAllocation("geoPointEmpty", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(GeoPointEmpty)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GeoPointEmpty) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	input.leave()
	return nil
}

// GroupCallMessage represents TL class groupCallMessage (ID 0x1a8afc7e).
type GroupCallMessage struct {
	FromAdmin        bool
	ID               int32
	FromID           PeerClass
	Date             int32
	Message          TextWithEntitiesClass
	PaidMessageStars *int64
}

// GroupCallMessageConstructorID is the TL constructor ID for groupCallMessage.
const GroupCallMessageConstructorID uint32 = 0x1a8afc7e

// ConstructorID returns the TL constructor ID.
func (*GroupCallMessage) ConstructorID() uint32 {
	return GroupCallMessageConstructorID
}

func (*GroupCallMessage) isGroupCallMessageClass() {
}

func (value *GroupCallMessage) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallMessage", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallMessage) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallMessage", "", ErrNilObject)
	}
	_present1 := value.PaidMessageStars != nil
	size := 0
	size += 4
	size += 4
	if value.FromID == nil {
		return 0, encodeError("groupCallMessage", "from_id", ErrNilObject)
	}
	_fieldSize0, err := value.FromID.encodedSize()
	if err != nil {
		return 0, encodeError("groupCallMessage", "from_id", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("groupCallMessage", "from_id", err)
	}
	size += 4
	if value.Message == nil {
		return 0, encodeError("groupCallMessage", "message", ErrNilObject)
	}
	_fieldSize1, err := value.Message.encodedSize()
	if err != nil {
		return 0, encodeError("groupCallMessage", "message", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("groupCallMessage", "message", err)
	}
	if _present1 {
		size += 8
	}
	return size, nil
}

func (value *GroupCallMessage) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallMessage", "", ErrNilObject)
	}
	output.putUint32(GroupCallMessageConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallMessage) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallMessage", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.FromAdmin
	if _present0 {
		_flags0 |= uint32(1) << 1
	}
	_present1 := value.PaidMessageStars != nil
	if _present1 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	output.putInt32(value.ID)
	if value.FromID == nil {
		return output, encodeError("groupCallMessage", "from_id", ErrNilObject)
	}
	_output0, err := value.FromID.encode(output)
	if err != nil {
		return output, encodeError("groupCallMessage", "from_id", err)
	}
	output = _output0
	output.putInt32(value.Date)
	if value.Message == nil {
		return output, encodeError("groupCallMessage", "message", ErrNilObject)
	}
	_output1, err := value.Message.encode(output)
	if err != nil {
		return output, encodeError("groupCallMessage", "message", err)
	}
	output = _output1
	if _present1 {
		output.putInt64(*value.PaidMessageStars)
	}
	return output, nil
}

// decodeGroupCallMessage decodes a TL GroupCallMessage.
func decodeGroupCallMessage(input *decoder) (*GroupCallMessage, error) {
	if err := input.reserveAllocation("groupCallMessage", decodedAllocationSize(32, 64)); err != nil {
		return nil, err
	}
	value := new(GroupCallMessage)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallMessage) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.FromAdmin = _flags0&(uint32(1)<<1) != 0
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.ID = _field0
	_field1, err := decodePeerClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.FromID = _field1
	_field2, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Date = _field2
	_field3, err := decodeTextWithEntitiesClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.Message = _field3
	if _flags0&(uint32(1)<<0) != 0 {
		_field4, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallMessage.paid_message_stars", decodedAllocationSize(8, 8)); err != nil {
			input.leave()
			return err
		}
		value.PaidMessageStars = &_field4
	}
	input.leave()
	return nil
}

// GroupCallParticipant represents TL class groupCallParticipant (ID 0x2a3dc7ac).
type GroupCallParticipant struct {
	Muted           bool
	Left            bool
	CanSelfUnmute   bool
	JustJoined      bool
	Versioned       bool
	Min             bool
	MutedByYou      bool
	VolumeByAdmin   bool
	Self            bool
	VideoJoined     bool
	Peer            PeerClass
	Date            int32
	ActiveDate      *int32
	Source          int32
	Volume          *int32
	About           *string
	RaiseHandRating *int64
	Video           GroupCallParticipantVideoClass
	Presentation    GroupCallParticipantVideoClass
	PaidStarsTotal  *int64
}

// GroupCallParticipantConstructorID is the TL constructor ID for groupCallParticipant.
const GroupCallParticipantConstructorID uint32 = 0x2a3dc7ac

// ConstructorID returns the TL constructor ID.
func (*GroupCallParticipant) ConstructorID() uint32 {
	return GroupCallParticipantConstructorID
}

func (*GroupCallParticipant) isGroupCallParticipantClass() {
}

func (value *GroupCallParticipant) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallParticipant", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallParticipant) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallParticipant", "", ErrNilObject)
	}
	_present10 := value.ActiveDate != nil
	_present11 := value.Volume != nil
	_present12 := value.About != nil
	_present13 := value.RaiseHandRating != nil
	_present14 := value.Video != nil
	_present15 := value.Presentation != nil
	_present16 := value.PaidStarsTotal != nil
	size := 0
	size += 4
	if value.Peer == nil {
		return 0, encodeError("groupCallParticipant", "peer", ErrNilObject)
	}
	_fieldSize0, err := value.Peer.encodedSize()
	if err != nil {
		return 0, encodeError("groupCallParticipant", "peer", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("groupCallParticipant", "peer", err)
	}
	size += 4
	if _present10 {
		size += 4
	}
	size += 4
	if _present11 {
		size += 4
	}
	if _present12 {
		_fieldSize1, err := bytesEncodedSize(len(*value.About))
		if err != nil {
			return 0, encodeError("groupCallParticipant", "about", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("groupCallParticipant", "about", err)
		}
	}
	if _present13 {
		size += 8
	}
	if _present14 {
		_fieldSize2, err := value.Video.encodedSize()
		if err != nil {
			return 0, encodeError("groupCallParticipant", "video", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("groupCallParticipant", "video", err)
		}
	}
	if _present15 {
		_fieldSize3, err := value.Presentation.encodedSize()
		if err != nil {
			return 0, encodeError("groupCallParticipant", "presentation", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize3)
		if err != nil {
			return 0, encodeError("groupCallParticipant", "presentation", err)
		}
	}
	if _present16 {
		size += 8
	}
	return size, nil
}

func (value *GroupCallParticipant) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallParticipant", "", ErrNilObject)
	}
	output.putUint32(GroupCallParticipantConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallParticipant) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallParticipant", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Muted
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.Left
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.CanSelfUnmute
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	_present3 := value.JustJoined
	if _present3 {
		_flags0 |= uint32(1) << 4
	}
	_present4 := value.Versioned
	if _present4 {
		_flags0 |= uint32(1) << 5
	}
	_present5 := value.Min
	if _present5 {
		_flags0 |= uint32(1) << 8
	}
	_present6 := value.MutedByYou
	if _present6 {
		_flags0 |= uint32(1) << 9
	}
	_present7 := value.VolumeByAdmin
	if _present7 {
		_flags0 |= uint32(1) << 10
	}
	_present8 := value.Self
	if _present8 {
		_flags0 |= uint32(1) << 12
	}
	_present9 := value.VideoJoined
	if _present9 {
		_flags0 |= uint32(1) << 15
	}
	_present10 := value.ActiveDate != nil
	if _present10 {
		_flags0 |= uint32(1) << 3
	}
	_present11 := value.Volume != nil
	if _present11 {
		_flags0 |= uint32(1) << 7
	}
	_present12 := value.About != nil
	if _present12 {
		_flags0 |= uint32(1) << 11
	}
	_present13 := value.RaiseHandRating != nil
	if _present13 {
		_flags0 |= uint32(1) << 13
	}
	_present14 := value.Video != nil
	if _present14 {
		_flags0 |= uint32(1) << 6
	}
	_present15 := value.Presentation != nil
	if _present15 {
		_flags0 |= uint32(1) << 14
	}
	_present16 := value.PaidStarsTotal != nil
	if _present16 {
		_flags0 |= uint32(1) << 16
	}
	output.putUint32(_flags0)
	if value.Peer == nil {
		return output, encodeError("groupCallParticipant", "peer", ErrNilObject)
	}
	_output0, err := value.Peer.encode(output)
	if err != nil {
		return output, encodeError("groupCallParticipant", "peer", err)
	}
	output = _output0
	output.putInt32(value.Date)
	if _present10 {
		output.putInt32(*value.ActiveDate)
	}
	output.putInt32(value.Source)
	if _present11 {
		output.putInt32(*value.Volume)
	}
	if _present12 {
		if err := output.putString(*value.About); err != nil {
			return output, encodeError("groupCallParticipant", "about", err)
		}
	}
	if _present13 {
		output.putInt64(*value.RaiseHandRating)
	}
	if _present14 {
		_output1, err := value.Video.encode(output)
		if err != nil {
			return output, encodeError("groupCallParticipant", "video", err)
		}
		output = _output1
	}
	if _present15 {
		_output2, err := value.Presentation.encode(output)
		if err != nil {
			return output, encodeError("groupCallParticipant", "presentation", err)
		}
		output = _output2
	}
	if _present16 {
		output.putInt64(*value.PaidStarsTotal)
	}
	return output, nil
}

// decodeGroupCallParticipant decodes a TL GroupCallParticipant.
func decodeGroupCallParticipant(input *decoder) (*GroupCallParticipant, error) {
	if err := input.reserveAllocation("groupCallParticipant", decodedAllocationSize(92, 184)); err != nil {
		return nil, err
	}
	value := new(GroupCallParticipant)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallParticipant) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Muted = _flags0&(uint32(1)<<0) != 0
	value.Left = _flags0&(uint32(1)<<1) != 0
	value.CanSelfUnmute = _flags0&(uint32(1)<<2) != 0
	value.JustJoined = _flags0&(uint32(1)<<4) != 0
	value.Versioned = _flags0&(uint32(1)<<5) != 0
	value.Min = _flags0&(uint32(1)<<8) != 0
	value.MutedByYou = _flags0&(uint32(1)<<9) != 0
	value.VolumeByAdmin = _flags0&(uint32(1)<<10) != 0
	value.Self = _flags0&(uint32(1)<<12) != 0
	value.VideoJoined = _flags0&(uint32(1)<<15) != 0
	_field0, err := decodePeerClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.Peer = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Date = _field1
	if _flags0&(uint32(1)<<3) != 0 {
		_field2, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallParticipant.active_date", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.ActiveDate = &_field2
	}
	_field3, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Source = _field3
	if _flags0&(uint32(1)<<7) != 0 {
		_field4, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallParticipant.volume", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.Volume = &_field4
	}
	if _flags0&(uint32(1)<<11) != 0 {
		_field5, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallParticipant.about", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.About = &_field5
	}
	if _flags0&(uint32(1)<<13) != 0 {
		_field6, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallParticipant.raise_hand_rating", decodedAllocationSize(8, 8)); err != nil {
			input.leave()
			return err
		}
		value.RaiseHandRating = &_field6
	}
	if _flags0&(uint32(1)<<6) != 0 {
		_field7, err := decodeGroupCallParticipantVideoClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Video = _field7
	}
	if _flags0&(uint32(1)<<14) != 0 {
		_field8, err := decodeGroupCallParticipantVideoClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Presentation = _field8
	}
	if _flags0&(uint32(1)<<16) != 0 {
		_field9, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallParticipant.paid_stars_total", decodedAllocationSize(8, 8)); err != nil {
			input.leave()
			return err
		}
		value.PaidStarsTotal = &_field9
	}
	input.leave()
	return nil
}

// GroupCallParticipantVideo represents TL class groupCallParticipantVideo (ID 0x67753ac8).
type GroupCallParticipantVideo struct {
	Paused       bool
	Endpoint     string
	SourceGroups []GroupCallParticipantVideoSourceGroupClass
	AudioSource  *int32
}

// GroupCallParticipantVideoConstructorID is the TL constructor ID for groupCallParticipantVideo.
const GroupCallParticipantVideoConstructorID uint32 = 0x67753ac8

// ConstructorID returns the TL constructor ID.
func (*GroupCallParticipantVideo) ConstructorID() uint32 {
	return GroupCallParticipantVideoConstructorID
}

func (*GroupCallParticipantVideo) isGroupCallParticipantVideoClass() {
}

func (value *GroupCallParticipantVideo) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallParticipantVideo", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallParticipantVideo) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallParticipantVideo", "", ErrNilObject)
	}
	_present1 := value.AudioSource != nil
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.Endpoint))
	if err != nil {
		return 0, encodeError("groupCallParticipantVideo", "endpoint", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("groupCallParticipantVideo", "endpoint", err)
	}
	if err := validateVectorLength(len(value.SourceGroups)); err != nil {
		return 0, encodeError("groupCallParticipantVideo", "source_groups", err)
	}
	_vectorSize1 := 8
	for _index1 := range value.SourceGroups {
		if value.SourceGroups[_index1] == nil {
			return 0, encodeError("groupCallParticipantVideo", "source_groups", ErrNilObject)
		}
		_fieldSize2, err := value.SourceGroups[_index1].encodedSize()
		if err != nil {
			return 0, encodeError("groupCallParticipantVideo", "source_groups", err)
		}
		_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _fieldSize2)
		if err != nil {
			return 0, encodeError("groupCallParticipantVideo", "source_groups", err)
		}
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("groupCallParticipantVideo", "source_groups", err)
	}
	size = _totalSize1
	if _present1 {
		size += 4
	}
	return size, nil
}

func (value *GroupCallParticipantVideo) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallParticipantVideo", "", ErrNilObject)
	}
	output.putUint32(GroupCallParticipantVideoConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallParticipantVideo) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallParticipantVideo", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Paused
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.AudioSource != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	output.putUint32(_flags0)
	if err := output.putString(value.Endpoint); err != nil {
		return output, encodeError("groupCallParticipantVideo", "endpoint", err)
	}
	if err := output.putVectorHeader(len(value.SourceGroups)); err != nil {
		return output, encodeError("groupCallParticipantVideo", "source_groups", err)
	}
	for _index := range value.SourceGroups {
		if value.SourceGroups[_index] == nil {
			return output, encodeError("groupCallParticipantVideo", "source_groups", ErrNilObject)
		}
		_output0, err := value.SourceGroups[_index].encode(output)
		if err != nil {
			return output, encodeError("groupCallParticipantVideo", "source_groups", err)
		}
		output = _output0
	}
	if _present1 {
		output.putInt32(*value.AudioSource)
	}
	return output, nil
}

// decodeGroupCallParticipantVideo decodes a TL GroupCallParticipantVideo.
func decodeGroupCallParticipantVideo(input *decoder) (*GroupCallParticipantVideo, error) {
	if err := input.reserveAllocation("groupCallParticipantVideo", decodedAllocationSize(28, 56)); err != nil {
		return nil, err
	}
	value := new(GroupCallParticipantVideo)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallParticipantVideo) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Paused = _flags0&(uint32(1)<<0) != 0
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.Endpoint = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("groupCallParticipantVideo.source_groups", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.SourceGroups = make([]GroupCallParticipantVideoSourceGroupClass, _count1)
	for _index1 := range value.SourceGroups {
		_field2, err := decodeGroupCallParticipantVideoSourceGroupClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.SourceGroups[_index1] = _field2
	}
	if _flags0&(uint32(1)<<1) != 0 {
		_field3, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCallParticipantVideo.audio_source", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.AudioSource = &_field3
	}
	input.leave()
	return nil
}

// GroupCallDiscarded represents TL class groupCallDiscarded (ID 0x7780bcb4).
type GroupCallDiscarded struct {
	ID         int64
	AccessHash int64
	Duration   int32
}

// GroupCallDiscardedConstructorID is the TL constructor ID for groupCallDiscarded.
const GroupCallDiscardedConstructorID uint32 = 0x7780bcb4

// ConstructorID returns the TL constructor ID.
func (*GroupCallDiscarded) ConstructorID() uint32 {
	return GroupCallDiscardedConstructorID
}

func (*GroupCallDiscarded) isGroupCallClass() {
}

func (value *GroupCallDiscarded) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallDiscarded", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallDiscarded) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallDiscarded", "", ErrNilObject)
	}
	size := 0
	size += 8
	size += 8
	size += 4
	return size, nil
}

func (value *GroupCallDiscarded) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallDiscarded", "", ErrNilObject)
	}
	output.putUint32(GroupCallDiscardedConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallDiscarded) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallDiscarded", "", ErrNilObject)
	}
	output.putInt64(value.ID)
	output.putInt64(value.AccessHash)
	output.putInt32(value.Duration)
	return output, nil
}

// decodeGroupCallDiscarded decodes a TL GroupCall.
func decodeGroupCallDiscarded(input *decoder) (*GroupCallDiscarded, error) {
	if err := input.reserveAllocation("groupCallDiscarded", decodedAllocationSize(20, 24)); err != nil {
		return nil, err
	}
	value := new(GroupCallDiscarded)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallDiscarded) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.ID = _field0
	_field1, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.AccessHash = _field1
	_field2, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Duration = _field2
	input.leave()
	return nil
}

// GroupCallStreamChannel represents TL class groupCallStreamChannel (ID 0x80eb48af).
type GroupCallStreamChannel struct {
	Channel         int32
	Scale           int32
	LastTimestampMs int64
}

// GroupCallStreamChannelConstructorID is the TL constructor ID for groupCallStreamChannel.
const GroupCallStreamChannelConstructorID uint32 = 0x80eb48af

// ConstructorID returns the TL constructor ID.
func (*GroupCallStreamChannel) ConstructorID() uint32 {
	return GroupCallStreamChannelConstructorID
}

func (*GroupCallStreamChannel) isGroupCallStreamChannelClass() {
}

func (value *GroupCallStreamChannel) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallStreamChannel", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallStreamChannel) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallStreamChannel", "", ErrNilObject)
	}
	size := 0
	size += 4
	size += 4
	size += 8
	return size, nil
}

func (value *GroupCallStreamChannel) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallStreamChannel", "", ErrNilObject)
	}
	output.putUint32(GroupCallStreamChannelConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallStreamChannel) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallStreamChannel", "", ErrNilObject)
	}
	output.putInt32(value.Channel)
	output.putInt32(value.Scale)
	output.putInt64(value.LastTimestampMs)
	return output, nil
}

// decodeGroupCallStreamChannel decodes a TL GroupCallStreamChannel.
func decodeGroupCallStreamChannel(input *decoder) (*GroupCallStreamChannel, error) {
	if err := input.reserveAllocation("groupCallStreamChannel", decodedAllocationSize(16, 24)); err != nil {
		return nil, err
	}
	value := new(GroupCallStreamChannel)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallStreamChannel) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Channel = _field0
	_field1, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Scale = _field1
	_field2, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.LastTimestampMs = _field2
	input.leave()
	return nil
}

// GeoPoint represents TL class geoPoint (ID 0xb2a2f663).
type GeoPoint struct {
	Long           float64
	Lat            float64
	AccessHash     int64
	AccuracyRadius *int32
}

// GeoPointConstructorID is the TL constructor ID for geoPoint.
const GeoPointConstructorID uint32 = 0xb2a2f663

// ConstructorID returns the TL constructor ID.
func (*GeoPoint) ConstructorID() uint32 {
	return GeoPointConstructorID
}

func (*GeoPoint) isGeoPointClass() {
}

func (value *GeoPoint) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("geoPoint", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GeoPoint) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("geoPoint", "", ErrNilObject)
	}
	_present0 := value.AccuracyRadius != nil
	size := 0
	size += 4
	size += 8
	size += 8
	size += 8
	if _present0 {
		size += 4
	}
	return size, nil
}

func (value *GeoPoint) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("geoPoint", "", ErrNilObject)
	}
	output.putUint32(GeoPointConstructorID)
	return value.encodeBody(output)
}

func (value *GeoPoint) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("geoPoint", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.AccuracyRadius != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	output.putFloat64(value.Long)
	output.putFloat64(value.Lat)
	output.putInt64(value.AccessHash)
	if _present0 {
		output.putInt32(*value.AccuracyRadius)
	}
	return output, nil
}

// decodeGeoPoint decodes a TL GeoPoint.
func decodeGeoPoint(input *decoder) (*GeoPoint, error) {
	if err := input.reserveAllocation("geoPoint", decodedAllocationSize(28, 32)); err != nil {
		return nil, err
	}
	value := new(GeoPoint)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GeoPoint) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	_field0, err := input.readFloat64()
	if err != nil {
		input.leave()
		return err
	}
	value.Long = _field0
	_field1, err := input.readFloat64()
	if err != nil {
		input.leave()
		return err
	}
	value.Lat = _field1
	_field2, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.AccessHash = _field2
	if _flags0&(uint32(1)<<0) != 0 {
		_field3, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("geoPoint.accuracy_radius", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.AccuracyRadius = &_field3
	}
	input.leave()
	return nil
}

// Game represents TL class game (ID 0xbdf9653b).
type Game struct {
	ID          int64
	AccessHash  int64
	ShortName   string
	Title       string
	Description string
	Photo       PhotoClass
	Document    DocumentClass
}

// GameConstructorID is the TL constructor ID for game.
const GameConstructorID uint32 = 0xbdf9653b

// ConstructorID returns the TL constructor ID.
func (*Game) ConstructorID() uint32 {
	return GameConstructorID
}

func (*Game) isGameClass() {
}

func (value *Game) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("game", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *Game) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("game", "", ErrNilObject)
	}
	_present0 := value.Document != nil
	size := 0
	size += 4
	size += 8
	size += 8
	_fieldSize0, err := bytesEncodedSize(len(value.ShortName))
	if err != nil {
		return 0, encodeError("game", "short_name", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("game", "short_name", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.Title))
	if err != nil {
		return 0, encodeError("game", "title", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("game", "title", err)
	}
	_fieldSize2, err := bytesEncodedSize(len(value.Description))
	if err != nil {
		return 0, encodeError("game", "description", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize2)
	if err != nil {
		return 0, encodeError("game", "description", err)
	}
	if value.Photo == nil {
		return 0, encodeError("game", "photo", ErrNilObject)
	}
	_fieldSize3, err := value.Photo.encodedSize()
	if err != nil {
		return 0, encodeError("game", "photo", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize3)
	if err != nil {
		return 0, encodeError("game", "photo", err)
	}
	if _present0 {
		_fieldSize4, err := value.Document.encodedSize()
		if err != nil {
			return 0, encodeError("game", "document", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize4)
		if err != nil {
			return 0, encodeError("game", "document", err)
		}
	}
	return size, nil
}

func (value *Game) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("game", "", ErrNilObject)
	}
	output.putUint32(GameConstructorID)
	return value.encodeBody(output)
}

func (value *Game) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("game", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Document != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	output.putInt64(value.ID)
	output.putInt64(value.AccessHash)
	if err := output.putString(value.ShortName); err != nil {
		return output, encodeError("game", "short_name", err)
	}
	if err := output.putString(value.Title); err != nil {
		return output, encodeError("game", "title", err)
	}
	if err := output.putString(value.Description); err != nil {
		return output, encodeError("game", "description", err)
	}
	if value.Photo == nil {
		return output, encodeError("game", "photo", ErrNilObject)
	}
	_output0, err := value.Photo.encode(output)
	if err != nil {
		return output, encodeError("game", "photo", err)
	}
	output = _output0
	if _present0 {
		_output1, err := value.Document.encode(output)
		if err != nil {
			return output, encodeError("game", "document", err)
		}
		output = _output1
	}
	return output, nil
}

// decodeGame decodes a TL Game.
func decodeGame(input *decoder) (*Game, error) {
	if err := input.reserveAllocation("game", decodedAllocationSize(56, 96)); err != nil {
		return nil, err
	}
	value := new(Game)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *Game) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	_field0, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.ID = _field0
	_field1, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.AccessHash = _field1
	_field2, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.ShortName = _field2
	_field3, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.Title = _field3
	_field4, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.Description = _field4
	_field5, err := decodePhotoClass(input)
	if err != nil {
		input.leave()
		return err
	}
	value.Photo = _field5
	if _flags0&(uint32(1)<<0) != 0 {
		_field6, err := decodeDocumentClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Document = _field6
	}
	input.leave()
	return nil
}

// GroupCallParticipantVideoSourceGroup represents TL class groupCallParticipantVideoSourceGroup (ID 0xdcb118b7).
type GroupCallParticipantVideoSourceGroup struct {
	Semantics string
	Sources   []int32
}

// GroupCallParticipantVideoSourceGroupConstructorID is the TL constructor ID for groupCallParticipantVideoSourceGroup.
const GroupCallParticipantVideoSourceGroupConstructorID uint32 = 0xdcb118b7

// ConstructorID returns the TL constructor ID.
func (*GroupCallParticipantVideoSourceGroup) ConstructorID() uint32 {
	return GroupCallParticipantVideoSourceGroupConstructorID
}

func (*GroupCallParticipantVideoSourceGroup) isGroupCallParticipantVideoSourceGroupClass() {
}

func (value *GroupCallParticipantVideoSourceGroup) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallParticipantVideoSourceGroup) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "", ErrNilObject)
	}
	size := 0
	_fieldSize0, err := bytesEncodedSize(len(value.Semantics))
	if err != nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "semantics", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "semantics", err)
	}
	if err := validateVectorLength(len(value.Sources)); err != nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "sources", err)
	}
	_vectorSize1 := 8
	_elementsSize1, err := checkedEncodedSizeProduct(len(value.Sources), 4)
	if err != nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "sources", err)
	}
	_vectorSize1, err = checkedEncodedSizeAdd(_vectorSize1, _elementsSize1)
	if err != nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "sources", err)
	}
	_totalSize1, err := checkedEncodedSizeAdd(size, _vectorSize1)
	if err != nil {
		return 0, encodeError("groupCallParticipantVideoSourceGroup", "sources", err)
	}
	size = _totalSize1
	return size, nil
}

func (value *GroupCallParticipantVideoSourceGroup) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallParticipantVideoSourceGroup", "", ErrNilObject)
	}
	output.putUint32(GroupCallParticipantVideoSourceGroupConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallParticipantVideoSourceGroup) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallParticipantVideoSourceGroup", "", ErrNilObject)
	}
	if err := output.putString(value.Semantics); err != nil {
		return output, encodeError("groupCallParticipantVideoSourceGroup", "semantics", err)
	}
	if err := output.putVectorHeader(len(value.Sources)); err != nil {
		return output, encodeError("groupCallParticipantVideoSourceGroup", "sources", err)
	}
	for _index := range value.Sources {
		output.putInt32(value.Sources[_index])
	}
	return output, nil
}

// decodeGroupCallParticipantVideoSourceGroup decodes a TL GroupCallParticipantVideoSourceGroup.
func decodeGroupCallParticipantVideoSourceGroup(input *decoder) (*GroupCallParticipantVideoSourceGroup, error) {
	if err := input.reserveAllocation("groupCallParticipantVideoSourceGroup", decodedAllocationSize(20, 40)); err != nil {
		return nil, err
	}
	value := new(GroupCallParticipantVideoSourceGroup)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallParticipantVideoSourceGroup) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.Semantics = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("groupCallParticipantVideoSourceGroup.sources", _count1, decodedAllocationSize(4, 4)); err != nil {
		input.leave()
		return err
	}
	value.Sources = make([]int32, _count1)
	for _index1 := range value.Sources {
		_field2, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		value.Sources[_index1] = _field2
	}
	input.leave()
	return nil
}

// GeoPointAddress represents TL class geoPointAddress (ID 0xde4c5d93).
type GeoPointAddress struct {
	CountryIso2 string
	State       *string
	City        *string
	Street      *string
}

// GeoPointAddressConstructorID is the TL constructor ID for geoPointAddress.
const GeoPointAddressConstructorID uint32 = 0xde4c5d93

// ConstructorID returns the TL constructor ID.
func (*GeoPointAddress) ConstructorID() uint32 {
	return GeoPointAddressConstructorID
}

func (*GeoPointAddress) isGeoPointAddressClass() {
}

func (value *GeoPointAddress) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("geoPointAddress", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GeoPointAddress) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("geoPointAddress", "", ErrNilObject)
	}
	_present0 := value.State != nil
	_present1 := value.City != nil
	_present2 := value.Street != nil
	size := 0
	size += 4
	_fieldSize0, err := bytesEncodedSize(len(value.CountryIso2))
	if err != nil {
		return 0, encodeError("geoPointAddress", "country_iso2", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("geoPointAddress", "country_iso2", err)
	}
	if _present0 {
		_fieldSize1, err := bytesEncodedSize(len(*value.State))
		if err != nil {
			return 0, encodeError("geoPointAddress", "state", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("geoPointAddress", "state", err)
		}
	}
	if _present1 {
		_fieldSize2, err := bytesEncodedSize(len(*value.City))
		if err != nil {
			return 0, encodeError("geoPointAddress", "city", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("geoPointAddress", "city", err)
		}
	}
	if _present2 {
		_fieldSize3, err := bytesEncodedSize(len(*value.Street))
		if err != nil {
			return 0, encodeError("geoPointAddress", "street", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize3)
		if err != nil {
			return 0, encodeError("geoPointAddress", "street", err)
		}
	}
	return size, nil
}

func (value *GeoPointAddress) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("geoPointAddress", "", ErrNilObject)
	}
	output.putUint32(GeoPointAddressConstructorID)
	return value.encodeBody(output)
}

func (value *GeoPointAddress) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("geoPointAddress", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.State != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.City != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.Street != nil
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	output.putUint32(_flags0)
	if err := output.putString(value.CountryIso2); err != nil {
		return output, encodeError("geoPointAddress", "country_iso2", err)
	}
	if _present0 {
		if err := output.putString(*value.State); err != nil {
			return output, encodeError("geoPointAddress", "state", err)
		}
	}
	if _present1 {
		if err := output.putString(*value.City); err != nil {
			return output, encodeError("geoPointAddress", "city", err)
		}
	}
	if _present2 {
		if err := output.putString(*value.Street); err != nil {
			return output, encodeError("geoPointAddress", "street", err)
		}
	}
	return output, nil
}

// decodeGeoPointAddress decodes a TL GeoPointAddress.
func decodeGeoPointAddress(input *decoder) (*GeoPointAddress, error) {
	if err := input.reserveAllocation("geoPointAddress", decodedAllocationSize(20, 40)); err != nil {
		return nil, err
	}
	value := new(GeoPointAddress)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GeoPointAddress) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	_field0, err := input.readString()
	if err != nil {
		input.leave()
		return err
	}
	value.CountryIso2 = _field0
	if _flags0&(uint32(1)<<0) != 0 {
		_field1, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("geoPointAddress.state", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.State = &_field1
	}
	if _flags0&(uint32(1)<<1) != 0 {
		_field2, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("geoPointAddress.city", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.City = &_field2
	}
	if _flags0&(uint32(1)<<2) != 0 {
		_field3, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("geoPointAddress.street", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.Street = &_field3
	}
	input.leave()
	return nil
}

// GroupCallDonor represents TL class groupCallDonor (ID 0xee430c85).
type GroupCallDonor struct {
	Top    bool
	My     bool
	PeerID PeerClass
	Stars  int64
}

// GroupCallDonorConstructorID is the TL constructor ID for groupCallDonor.
const GroupCallDonorConstructorID uint32 = 0xee430c85

// ConstructorID returns the TL constructor ID.
func (*GroupCallDonor) ConstructorID() uint32 {
	return GroupCallDonorConstructorID
}

func (*GroupCallDonor) isGroupCallDonorClass() {
}

func (value *GroupCallDonor) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallDonor", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCallDonor) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCallDonor", "", ErrNilObject)
	}
	_present2 := value.PeerID != nil
	size := 0
	size += 4
	if _present2 {
		_fieldSize0, err := value.PeerID.encodedSize()
		if err != nil {
			return 0, encodeError("groupCallDonor", "peer_id", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("groupCallDonor", "peer_id", err)
		}
	}
	size += 8
	return size, nil
}

func (value *GroupCallDonor) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallDonor", "", ErrNilObject)
	}
	output.putUint32(GroupCallDonorConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCallDonor) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCallDonor", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.Top
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.My
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.PeerID != nil
	if _present2 {
		_flags0 |= uint32(1) << 3
	}
	output.putUint32(_flags0)
	if _present2 {
		_output0, err := value.PeerID.encode(output)
		if err != nil {
			return output, encodeError("groupCallDonor", "peer_id", err)
		}
		output = _output0
	}
	output.putInt64(value.Stars)
	return output, nil
}

// decodeGroupCallDonor decodes a TL GroupCallDonor.
func decodeGroupCallDonor(input *decoder) (*GroupCallDonor, error) {
	if err := input.reserveAllocation("groupCallDonor", decodedAllocationSize(24, 40)); err != nil {
		return nil, err
	}
	value := new(GroupCallDonor)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCallDonor) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.Top = _flags0&(uint32(1)<<0) != 0
	value.My = _flags0&(uint32(1)<<1) != 0
	if _flags0&(uint32(1)<<3) != 0 {
		_field0, err := decodePeerClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.PeerID = _field0
	}
	_field1, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.Stars = _field1
	input.leave()
	return nil
}

// GroupCall represents TL class groupCall (ID 0xefb2b617).
type GroupCall struct {
	JoinMuted                bool
	CanChangeJoinMuted       bool
	JoinDateAsc              bool
	ScheduleStartSubscribed  bool
	CanStartVideo            bool
	RecordVideoActive        bool
	RTMPStream               bool
	ListenersHidden          bool
	Conference               bool
	Creator                  bool
	MessagesEnabled          bool
	CanChangeMessagesEnabled bool
	Min                      bool
	ID                       int64
	AccessHash               int64
	ParticipantsCount        int32
	Title                    *string
	StreamDCID               *int32
	RecordStartDate          *int32
	ScheduleDate             *int32
	UnmutedVideoCount        *int32
	UnmutedVideoLimit        int32
	Version                  int32
	InviteLink               *string
	SendPaidMessagesStars    *int64
	DefaultSendAs            PeerClass
}

// GroupCallConstructorID is the TL constructor ID for groupCall.
const GroupCallConstructorID uint32 = 0xefb2b617

// ConstructorID returns the TL constructor ID.
func (*GroupCall) ConstructorID() uint32 {
	return GroupCallConstructorID
}

func (*GroupCall) isGroupCallClass() {
}

func (value *GroupCall) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCall", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GroupCall) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("groupCall", "", ErrNilObject)
	}
	_present13 := value.Title != nil
	_present14 := value.StreamDCID != nil
	_present15 := value.RecordStartDate != nil
	_present16 := value.ScheduleDate != nil
	_present17 := value.UnmutedVideoCount != nil
	_present18 := value.InviteLink != nil
	_present19 := value.SendPaidMessagesStars != nil
	_present20 := value.DefaultSendAs != nil
	size := 0
	size += 4
	size += 8
	size += 8
	size += 4
	if _present13 {
		_fieldSize0, err := bytesEncodedSize(len(*value.Title))
		if err != nil {
			return 0, encodeError("groupCall", "title", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("groupCall", "title", err)
		}
	}
	if _present14 {
		size += 4
	}
	if _present15 {
		size += 4
	}
	if _present16 {
		size += 4
	}
	if _present17 {
		size += 4
	}
	size += 4
	size += 4
	if _present18 {
		_fieldSize1, err := bytesEncodedSize(len(*value.InviteLink))
		if err != nil {
			return 0, encodeError("groupCall", "invite_link", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("groupCall", "invite_link", err)
		}
	}
	if _present19 {
		size += 8
	}
	if _present20 {
		_fieldSize2, err := value.DefaultSendAs.encodedSize()
		if err != nil {
			return 0, encodeError("groupCall", "default_send_as", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("groupCall", "default_send_as", err)
		}
	}
	return size, nil
}

func (value *GroupCall) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCall", "", ErrNilObject)
	}
	output.putUint32(GroupCallConstructorID)
	return value.encodeBody(output)
}

func (value *GroupCall) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("groupCall", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.JoinMuted
	if _present0 {
		_flags0 |= uint32(1) << 1
	}
	_present1 := value.CanChangeJoinMuted
	if _present1 {
		_flags0 |= uint32(1) << 2
	}
	_present2 := value.JoinDateAsc
	if _present2 {
		_flags0 |= uint32(1) << 6
	}
	_present3 := value.ScheduleStartSubscribed
	if _present3 {
		_flags0 |= uint32(1) << 8
	}
	_present4 := value.CanStartVideo
	if _present4 {
		_flags0 |= uint32(1) << 9
	}
	_present5 := value.RecordVideoActive
	if _present5 {
		_flags0 |= uint32(1) << 11
	}
	_present6 := value.RTMPStream
	if _present6 {
		_flags0 |= uint32(1) << 12
	}
	_present7 := value.ListenersHidden
	if _present7 {
		_flags0 |= uint32(1) << 13
	}
	_present8 := value.Conference
	if _present8 {
		_flags0 |= uint32(1) << 14
	}
	_present9 := value.Creator
	if _present9 {
		_flags0 |= uint32(1) << 15
	}
	_present10 := value.MessagesEnabled
	if _present10 {
		_flags0 |= uint32(1) << 17
	}
	_present11 := value.CanChangeMessagesEnabled
	if _present11 {
		_flags0 |= uint32(1) << 18
	}
	_present12 := value.Min
	if _present12 {
		_flags0 |= uint32(1) << 19
	}
	_present13 := value.Title != nil
	if _present13 {
		_flags0 |= uint32(1) << 3
	}
	_present14 := value.StreamDCID != nil
	if _present14 {
		_flags0 |= uint32(1) << 4
	}
	_present15 := value.RecordStartDate != nil
	if _present15 {
		_flags0 |= uint32(1) << 5
	}
	_present16 := value.ScheduleDate != nil
	if _present16 {
		_flags0 |= uint32(1) << 7
	}
	_present17 := value.UnmutedVideoCount != nil
	if _present17 {
		_flags0 |= uint32(1) << 10
	}
	_present18 := value.InviteLink != nil
	if _present18 {
		_flags0 |= uint32(1) << 16
	}
	_present19 := value.SendPaidMessagesStars != nil
	if _present19 {
		_flags0 |= uint32(1) << 20
	}
	_present20 := value.DefaultSendAs != nil
	if _present20 {
		_flags0 |= uint32(1) << 21
	}
	output.putUint32(_flags0)
	output.putInt64(value.ID)
	output.putInt64(value.AccessHash)
	output.putInt32(value.ParticipantsCount)
	if _present13 {
		if err := output.putString(*value.Title); err != nil {
			return output, encodeError("groupCall", "title", err)
		}
	}
	if _present14 {
		output.putInt32(*value.StreamDCID)
	}
	if _present15 {
		output.putInt32(*value.RecordStartDate)
	}
	if _present16 {
		output.putInt32(*value.ScheduleDate)
	}
	if _present17 {
		output.putInt32(*value.UnmutedVideoCount)
	}
	output.putInt32(value.UnmutedVideoLimit)
	output.putInt32(value.Version)
	if _present18 {
		if err := output.putString(*value.InviteLink); err != nil {
			return output, encodeError("groupCall", "invite_link", err)
		}
	}
	if _present19 {
		output.putInt64(*value.SendPaidMessagesStars)
	}
	if _present20 {
		_output0, err := value.DefaultSendAs.encode(output)
		if err != nil {
			return output, encodeError("groupCall", "default_send_as", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeGroupCall decodes a TL GroupCall.
func decodeGroupCall(input *decoder) (*GroupCall, error) {
	if err := input.reserveAllocation("groupCall", decodedAllocationSize(116, 216)); err != nil {
		return nil, err
	}
	value := new(GroupCall)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GroupCall) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.JoinMuted = _flags0&(uint32(1)<<1) != 0
	value.CanChangeJoinMuted = _flags0&(uint32(1)<<2) != 0
	value.JoinDateAsc = _flags0&(uint32(1)<<6) != 0
	value.ScheduleStartSubscribed = _flags0&(uint32(1)<<8) != 0
	value.CanStartVideo = _flags0&(uint32(1)<<9) != 0
	value.RecordVideoActive = _flags0&(uint32(1)<<11) != 0
	value.RTMPStream = _flags0&(uint32(1)<<12) != 0
	value.ListenersHidden = _flags0&(uint32(1)<<13) != 0
	value.Conference = _flags0&(uint32(1)<<14) != 0
	value.Creator = _flags0&(uint32(1)<<15) != 0
	value.MessagesEnabled = _flags0&(uint32(1)<<17) != 0
	value.CanChangeMessagesEnabled = _flags0&(uint32(1)<<18) != 0
	value.Min = _flags0&(uint32(1)<<19) != 0
	_field0, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.ID = _field0
	_field1, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.AccessHash = _field1
	_field2, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.ParticipantsCount = _field2
	if _flags0&(uint32(1)<<3) != 0 {
		_field3, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.title", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.Title = &_field3
	}
	if _flags0&(uint32(1)<<4) != 0 {
		_field4, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.stream_dc_id", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.StreamDCID = &_field4
	}
	if _flags0&(uint32(1)<<5) != 0 {
		_field5, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.record_start_date", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.RecordStartDate = &_field5
	}
	if _flags0&(uint32(1)<<7) != 0 {
		_field6, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.schedule_date", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.ScheduleDate = &_field6
	}
	if _flags0&(uint32(1)<<10) != 0 {
		_field7, err := input.readInt32()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.unmuted_video_count", decodedAllocationSize(4, 4)); err != nil {
			input.leave()
			return err
		}
		value.UnmutedVideoCount = &_field7
	}
	_field8, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.UnmutedVideoLimit = _field8
	_field9, err := input.readInt32()
	if err != nil {
		input.leave()
		return err
	}
	value.Version = _field9
	if _flags0&(uint32(1)<<16) != 0 {
		_field10, err := input.readString()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.invite_link", decodedAllocationSize(8, 16)); err != nil {
			input.leave()
			return err
		}
		value.InviteLink = &_field10
	}
	if _flags0&(uint32(1)<<20) != 0 {
		_field11, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("groupCall.send_paid_messages_stars", decodedAllocationSize(8, 8)); err != nil {
			input.leave()
			return err
		}
		value.SendPaidMessagesStars = &_field11
	}
	if _flags0&(uint32(1)<<21) != 0 {
		_field12, err := decodePeerClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.DefaultSendAs = _field12
	}
	input.leave()
	return nil
}

// GlobalPrivacySettings represents TL class globalPrivacySettings (ID 0xfe41b34f).
type GlobalPrivacySettings struct {
	ArchiveAndMuteNewNoncontactPeers bool
	KeepArchivedUnmuted              bool
	KeepArchivedFolders              bool
	HideReadMarks                    bool
	NewNoncontactPeersRequirePremium bool
	DisplayGiftsButton               bool
	NoncontactPeersPaidStars         *int64
	DisallowedGifts                  DisallowedGiftsSettingsClass
}

// GlobalPrivacySettingsConstructorID is the TL constructor ID for globalPrivacySettings.
const GlobalPrivacySettingsConstructorID uint32 = 0xfe41b34f

// ConstructorID returns the TL constructor ID.
func (*GlobalPrivacySettings) ConstructorID() uint32 {
	return GlobalPrivacySettingsConstructorID
}

func (*GlobalPrivacySettings) isGlobalPrivacySettingsClass() {
}

func (value *GlobalPrivacySettings) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("globalPrivacySettings", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *GlobalPrivacySettings) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("globalPrivacySettings", "", ErrNilObject)
	}
	_present6 := value.NoncontactPeersPaidStars != nil
	_present7 := value.DisallowedGifts != nil
	size := 0
	size += 4
	if _present6 {
		size += 8
	}
	if _present7 {
		_fieldSize0, err := value.DisallowedGifts.encodedSize()
		if err != nil {
			return 0, encodeError("globalPrivacySettings", "disallowed_gifts", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize0)
		if err != nil {
			return 0, encodeError("globalPrivacySettings", "disallowed_gifts", err)
		}
	}
	return size, nil
}

func (value *GlobalPrivacySettings) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("globalPrivacySettings", "", ErrNilObject)
	}
	output.putUint32(GlobalPrivacySettingsConstructorID)
	return value.encodeBody(output)
}

func (value *GlobalPrivacySettings) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("globalPrivacySettings", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.ArchiveAndMuteNewNoncontactPeers
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.KeepArchivedUnmuted
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.KeepArchivedFolders
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	_present3 := value.HideReadMarks
	if _present3 {
		_flags0 |= uint32(1) << 3
	}
	_present4 := value.NewNoncontactPeersRequirePremium
	if _present4 {
		_flags0 |= uint32(1) << 4
	}
	_present5 := value.DisplayGiftsButton
	if _present5 {
		_flags0 |= uint32(1) << 7
	}
	_present6 := value.NoncontactPeersPaidStars != nil
	if _present6 {
		_flags0 |= uint32(1) << 5
	}
	_present7 := value.DisallowedGifts != nil
	if _present7 {
		_flags0 |= uint32(1) << 6
	}
	output.putUint32(_flags0)
	if _present6 {
		output.putInt64(*value.NoncontactPeersPaidStars)
	}
	if _present7 {
		_output0, err := value.DisallowedGifts.encode(output)
		if err != nil {
			return output, encodeError("globalPrivacySettings", "disallowed_gifts", err)
		}
		output = _output0
	}
	return output, nil
}

// decodeGlobalPrivacySettings decodes a TL GlobalPrivacySettings.
func decodeGlobalPrivacySettings(input *decoder) (*GlobalPrivacySettings, error) {
	if err := input.reserveAllocation("globalPrivacySettings", decodedAllocationSize(36, 72)); err != nil {
		return nil, err
	}
	value := new(GlobalPrivacySettings)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *GlobalPrivacySettings) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_flags0, err := input.readUint32()
	if err != nil {
		input.leave()
		return err
	}
	value.ArchiveAndMuteNewNoncontactPeers = _flags0&(uint32(1)<<0) != 0
	value.KeepArchivedUnmuted = _flags0&(uint32(1)<<1) != 0
	value.KeepArchivedFolders = _flags0&(uint32(1)<<2) != 0
	value.HideReadMarks = _flags0&(uint32(1)<<3) != 0
	value.NewNoncontactPeersRequirePremium = _flags0&(uint32(1)<<4) != 0
	value.DisplayGiftsButton = _flags0&(uint32(1)<<7) != 0
	if _flags0&(uint32(1)<<5) != 0 {
		_field0, err := input.readInt64()
		if err != nil {
			input.leave()
			return err
		}
		if err := input.reserveAllocation("globalPrivacySettings.noncontact_peers_paid_stars", decodedAllocationSize(8, 8)); err != nil {
			input.leave()
			return err
		}
		value.NoncontactPeersPaidStars = &_field0
	}
	if _flags0&(uint32(1)<<6) != 0 {
		_field1, err := decodeDisallowedGiftsSettingsClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.DisallowedGifts = _field1
	}
	input.leave()
	return nil
}
