// Code generated by cmd/tlgen (tlgen/v1); DO NOT EDIT.
//
// Source: schema/api-schema.json
// Telegram API layer: 229

package tl

// AicomposeTonesClass is the TL union aicompose.Tones.
type AicomposeTonesClass interface {
	Object
	isAicomposeTonesClass()
}

// decodeAicomposeTonesClass decodes the TL union aicompose.Tones.
func decodeAicomposeTonesClass(input *decoder) (AicomposeTonesClass, error) {
	start := input.offset
	constructor, err := input.readUint32()
	if err != nil {
		return nil, err
	}
	switch constructor {
	case AicomposeTonesConstructorID:
		value, err := decodeAicomposeTones(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	case AicomposeTonesNotModifiedConstructorID:
		value, err := decodeAicomposeTonesNotModified(input)
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, input.unexpectedConstructor(start, "AicomposeTonesClass", constructor)
	}
}

// AicomposeSaveToneRequest represents TL method aicompose.saveTone (ID 0x1782cbb1).
type AicomposeSaveToneRequest struct {
	Tone   InputAiComposeToneClass
	Unsave bool
}

// AicomposeSaveToneRequestConstructorID is the TL constructor ID for aicompose.saveTone.
const AicomposeSaveToneRequestConstructorID uint32 = 0x1782cbb1

// ConstructorID returns the TL constructor ID.
func (*AicomposeSaveToneRequest) ConstructorID() uint32 {
	return AicomposeSaveToneRequestConstructorID
}

func (*AicomposeSaveToneRequest) requestResult(bool) {}

func (value *AicomposeSaveToneRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.saveTone", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeSaveToneRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.saveTone", "", ErrNilObject)
	}
	size := 0
	if value.Tone == nil {
		return 0, encodeError("aicompose.saveTone", "tone", ErrNilObject)
	}
	_fieldSize0, err := value.Tone.encodedSize()
	if err != nil {
		return 0, encodeError("aicompose.saveTone", "tone", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("aicompose.saveTone", "tone", err)
	}
	size += 4
	return size, nil
}

func (value *AicomposeSaveToneRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.saveTone", "", ErrNilObject)
	}
	output.putUint32(AicomposeSaveToneRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeSaveToneRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.saveTone", "", ErrNilObject)
	}
	if value.Tone == nil {
		return output, encodeError("aicompose.saveTone", "tone", ErrNilObject)
	}
	_output0, err := value.Tone.encode(output)
	if err != nil {
		return output, encodeError("aicompose.saveTone", "tone", err)
	}
	output = _output0
	output.putBool(value.Unsave)
	return output, nil
}

func (request *AicomposeSaveToneRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// AicomposeCreateToneRequest represents TL method aicompose.createTone (ID 0x4aa83913).
type AicomposeCreateToneRequest struct {
	DisplayAuthor bool
	EmojiID       int64
	Title         string
	Prompt        string
}

// AicomposeCreateToneRequestConstructorID is the TL constructor ID for aicompose.createTone.
const AicomposeCreateToneRequestConstructorID uint32 = 0x4aa83913

// ConstructorID returns the TL constructor ID.
func (*AicomposeCreateToneRequest) ConstructorID() uint32 {
	return AicomposeCreateToneRequestConstructorID
}

func (*AicomposeCreateToneRequest) requestResult(AiComposeToneClass) {}

func (value *AicomposeCreateToneRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.createTone", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeCreateToneRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.createTone", "", ErrNilObject)
	}
	size := 0
	size += 4
	size += 8
	_fieldSize0, err := bytesEncodedSize(len(value.Title))
	if err != nil {
		return 0, encodeError("aicompose.createTone", "title", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("aicompose.createTone", "title", err)
	}
	_fieldSize1, err := bytesEncodedSize(len(value.Prompt))
	if err != nil {
		return 0, encodeError("aicompose.createTone", "prompt", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize1)
	if err != nil {
		return 0, encodeError("aicompose.createTone", "prompt", err)
	}
	return size, nil
}

func (value *AicomposeCreateToneRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.createTone", "", ErrNilObject)
	}
	output.putUint32(AicomposeCreateToneRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeCreateToneRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.createTone", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.DisplayAuthor
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	output.putUint32(_flags0)
	output.putInt64(value.EmojiID)
	if err := output.putString(value.Title); err != nil {
		return output, encodeError("aicompose.createTone", "title", err)
	}
	if err := output.putString(value.Prompt); err != nil {
		return output, encodeError("aicompose.createTone", "prompt", err)
	}
	return output, nil
}

func (request *AicomposeCreateToneRequest) decodeResult(state decoder) (AiComposeToneClass, decoder, error) {
	var zero AiComposeToneClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result AiComposeToneClass
	_field0, err := decodeAiComposeToneClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// AicomposeTones represents TL class aicompose.tones (ID 0x6c9d0efe).
type AicomposeTones struct {
	Hash  int64
	Tones []AiComposeToneClass
	Users []UserClass
}

// AicomposeTonesConstructorID is the TL constructor ID for aicompose.tones.
const AicomposeTonesConstructorID uint32 = 0x6c9d0efe

// ConstructorID returns the TL constructor ID.
func (*AicomposeTones) ConstructorID() uint32 {
	return AicomposeTonesConstructorID
}

func (*AicomposeTones) isAicomposeTonesClass() {
}

func (value *AicomposeTones) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.tones", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeTones) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.tones", "", ErrNilObject)
	}
	size := 0
	size += 8
	if err := validateVectorLength(len(value.Tones)); err != nil {
		return 0, encodeError("aicompose.tones", "tones", err)
	}
	_vectorSize0 := 8
	for _index0 := range value.Tones {
		if value.Tones[_index0] == nil {
			return 0, encodeError("aicompose.tones", "tones", ErrNilObject)
		}
		_fieldSize1, err := value.Tones[_index0].encodedSize()
		if err != nil {
			return 0, encodeError("aicompose.tones", "tones", err)
		}
		_vectorSize0, err = checkedEncodedSizeAdd(_vectorSize0, _fieldSize1)
		if err != nil {
			return 0, encodeError("aicompose.tones", "tones", err)
		}
	}
	_totalSize0, err := checkedEncodedSizeAdd(size, _vectorSize0)
	if err != nil {
		return 0, encodeError("aicompose.tones", "tones", err)
	}
	size = _totalSize0
	if err := validateVectorLength(len(value.Users)); err != nil {
		return 0, encodeError("aicompose.tones", "users", err)
	}
	_vectorSize2 := 8
	for _index2 := range value.Users {
		if value.Users[_index2] == nil {
			return 0, encodeError("aicompose.tones", "users", ErrNilObject)
		}
		_fieldSize3, err := value.Users[_index2].encodedSize()
		if err != nil {
			return 0, encodeError("aicompose.tones", "users", err)
		}
		_vectorSize2, err = checkedEncodedSizeAdd(_vectorSize2, _fieldSize3)
		if err != nil {
			return 0, encodeError("aicompose.tones", "users", err)
		}
	}
	_totalSize2, err := checkedEncodedSizeAdd(size, _vectorSize2)
	if err != nil {
		return 0, encodeError("aicompose.tones", "users", err)
	}
	size = _totalSize2
	return size, nil
}

func (value *AicomposeTones) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.tones", "", ErrNilObject)
	}
	output.putUint32(AicomposeTonesConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeTones) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.tones", "", ErrNilObject)
	}
	output.putInt64(value.Hash)
	if err := output.putVectorHeader(len(value.Tones)); err != nil {
		return output, encodeError("aicompose.tones", "tones", err)
	}
	for _index := range value.Tones {
		if value.Tones[_index] == nil {
			return output, encodeError("aicompose.tones", "tones", ErrNilObject)
		}
		_output0, err := value.Tones[_index].encode(output)
		if err != nil {
			return output, encodeError("aicompose.tones", "tones", err)
		}
		output = _output0
	}
	if err := output.putVectorHeader(len(value.Users)); err != nil {
		return output, encodeError("aicompose.tones", "users", err)
	}
	for _index := range value.Users {
		if value.Users[_index] == nil {
			return output, encodeError("aicompose.tones", "users", ErrNilObject)
		}
		_output1, err := value.Users[_index].encode(output)
		if err != nil {
			return output, encodeError("aicompose.tones", "users", err)
		}
		output = _output1
	}
	return output, nil
}

// decodeAicomposeTones decodes a TL aicompose.Tones.
func decodeAicomposeTones(input *decoder) (*AicomposeTones, error) {
	if err := input.reserveAllocation("aicompose.tones", decodedAllocationSize(32, 56)); err != nil {
		return nil, err
	}
	value := new(AicomposeTones)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *AicomposeTones) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	_field0, err := input.readInt64()
	if err != nil {
		input.leave()
		return err
	}
	value.Hash = _field0
	_count1, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("aicompose.tones.tones", _count1, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Tones = make([]AiComposeToneClass, _count1)
	for _index1 := range value.Tones {
		_field2, err := decodeAiComposeToneClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Tones[_index1] = _field2
	}
	_count3, err := input.readVectorHeader()
	if err != nil {
		input.leave()
		return err
	}
	if err := input.reserveAllocationProduct("aicompose.tones.users", _count3, decodedAllocationSize(8, 16)); err != nil {
		input.leave()
		return err
	}
	value.Users = make([]UserClass, _count3)
	for _index3 := range value.Users {
		_field4, err := decodeUserClass(input)
		if err != nil {
			input.leave()
			return err
		}
		value.Users[_index3] = _field4
	}
	input.leave()
	return nil
}

// AicomposeUpdateToneRequest represents TL method aicompose.updateTone (ID 0x903bcf59).
type AicomposeUpdateToneRequest struct {
	Tone          InputAiComposeToneClass
	DisplayAuthor *bool
	EmojiID       *int64
	Title         *string
	Prompt        *string
}

// AicomposeUpdateToneRequestConstructorID is the TL constructor ID for aicompose.updateTone.
const AicomposeUpdateToneRequestConstructorID uint32 = 0x903bcf59

// ConstructorID returns the TL constructor ID.
func (*AicomposeUpdateToneRequest) ConstructorID() uint32 {
	return AicomposeUpdateToneRequestConstructorID
}

func (*AicomposeUpdateToneRequest) requestResult(AiComposeToneClass) {}

func (value *AicomposeUpdateToneRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.updateTone", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeUpdateToneRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.updateTone", "", ErrNilObject)
	}
	_present0 := value.DisplayAuthor != nil
	_present1 := value.EmojiID != nil
	_present2 := value.Title != nil
	_present3 := value.Prompt != nil
	size := 0
	size += 4
	if value.Tone == nil {
		return 0, encodeError("aicompose.updateTone", "tone", ErrNilObject)
	}
	_fieldSize0, err := value.Tone.encodedSize()
	if err != nil {
		return 0, encodeError("aicompose.updateTone", "tone", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("aicompose.updateTone", "tone", err)
	}
	if _present0 {
		size += 4
	}
	if _present1 {
		size += 8
	}
	if _present2 {
		_fieldSize1, err := bytesEncodedSize(len(*value.Title))
		if err != nil {
			return 0, encodeError("aicompose.updateTone", "title", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize1)
		if err != nil {
			return 0, encodeError("aicompose.updateTone", "title", err)
		}
	}
	if _present3 {
		_fieldSize2, err := bytesEncodedSize(len(*value.Prompt))
		if err != nil {
			return 0, encodeError("aicompose.updateTone", "prompt", err)
		}
		size, err = checkedEncodedSizeAdd(size, _fieldSize2)
		if err != nil {
			return 0, encodeError("aicompose.updateTone", "prompt", err)
		}
	}
	return size, nil
}

func (value *AicomposeUpdateToneRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.updateTone", "", ErrNilObject)
	}
	output.putUint32(AicomposeUpdateToneRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeUpdateToneRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.updateTone", "", ErrNilObject)
	}
	var _flags0 uint32
	_present0 := value.DisplayAuthor != nil
	if _present0 {
		_flags0 |= uint32(1) << 0
	}
	_present1 := value.EmojiID != nil
	if _present1 {
		_flags0 |= uint32(1) << 1
	}
	_present2 := value.Title != nil
	if _present2 {
		_flags0 |= uint32(1) << 2
	}
	_present3 := value.Prompt != nil
	if _present3 {
		_flags0 |= uint32(1) << 3
	}
	output.putUint32(_flags0)
	if value.Tone == nil {
		return output, encodeError("aicompose.updateTone", "tone", ErrNilObject)
	}
	_output0, err := value.Tone.encode(output)
	if err != nil {
		return output, encodeError("aicompose.updateTone", "tone", err)
	}
	output = _output0
	if _present0 {
		output.putBool(*value.DisplayAuthor)
	}
	if _present1 {
		output.putInt64(*value.EmojiID)
	}
	if _present2 {
		if err := output.putString(*value.Title); err != nil {
			return output, encodeError("aicompose.updateTone", "title", err)
		}
	}
	if _present3 {
		if err := output.putString(*value.Prompt); err != nil {
			return output, encodeError("aicompose.updateTone", "prompt", err)
		}
	}
	return output, nil
}

func (request *AicomposeUpdateToneRequest) decodeResult(state decoder) (AiComposeToneClass, decoder, error) {
	var zero AiComposeToneClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result AiComposeToneClass
	_field0, err := decodeAiComposeToneClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// AicomposeGetTonesRequest represents TL method aicompose.getTones (ID 0xabd59201).
type AicomposeGetTonesRequest struct {
	Hash int64
}

// AicomposeGetTonesRequestConstructorID is the TL constructor ID for aicompose.getTones.
const AicomposeGetTonesRequestConstructorID uint32 = 0xabd59201

// ConstructorID returns the TL constructor ID.
func (*AicomposeGetTonesRequest) ConstructorID() uint32 {
	return AicomposeGetTonesRequestConstructorID
}

func (*AicomposeGetTonesRequest) requestResult(AicomposeTonesClass) {}

func (value *AicomposeGetTonesRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.getTones", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeGetTonesRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.getTones", "", ErrNilObject)
	}
	size := 0
	size += 8
	return size, nil
}

func (value *AicomposeGetTonesRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.getTones", "", ErrNilObject)
	}
	output.putUint32(AicomposeGetTonesRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeGetTonesRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.getTones", "", ErrNilObject)
	}
	output.putInt64(value.Hash)
	return output, nil
}

func (request *AicomposeGetTonesRequest) decodeResult(state decoder) (AicomposeTonesClass, decoder, error) {
	var zero AicomposeTonesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result AicomposeTonesClass
	_field0, err := decodeAicomposeTonesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// AicomposeGetToneRequest represents TL method aicompose.getTone (ID 0xb2e8ba03).
type AicomposeGetToneRequest struct {
	Tone InputAiComposeToneClass
}

// AicomposeGetToneRequestConstructorID is the TL constructor ID for aicompose.getTone.
const AicomposeGetToneRequestConstructorID uint32 = 0xb2e8ba03

// ConstructorID returns the TL constructor ID.
func (*AicomposeGetToneRequest) ConstructorID() uint32 {
	return AicomposeGetToneRequestConstructorID
}

func (*AicomposeGetToneRequest) requestResult(AicomposeTonesClass) {}

func (value *AicomposeGetToneRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.getTone", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeGetToneRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.getTone", "", ErrNilObject)
	}
	size := 0
	if value.Tone == nil {
		return 0, encodeError("aicompose.getTone", "tone", ErrNilObject)
	}
	_fieldSize0, err := value.Tone.encodedSize()
	if err != nil {
		return 0, encodeError("aicompose.getTone", "tone", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("aicompose.getTone", "tone", err)
	}
	return size, nil
}

func (value *AicomposeGetToneRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.getTone", "", ErrNilObject)
	}
	output.putUint32(AicomposeGetToneRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeGetToneRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.getTone", "", ErrNilObject)
	}
	if value.Tone == nil {
		return output, encodeError("aicompose.getTone", "tone", ErrNilObject)
	}
	_output0, err := value.Tone.encode(output)
	if err != nil {
		return output, encodeError("aicompose.getTone", "tone", err)
	}
	output = _output0
	return output, nil
}

func (request *AicomposeGetToneRequest) decodeResult(state decoder) (AicomposeTonesClass, decoder, error) {
	var zero AicomposeTonesClass
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result AicomposeTonesClass
	_field0, err := decodeAicomposeTonesClass(input)
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}

// AicomposeTonesNotModified represents TL class aicompose.tonesNotModified (ID 0xc1f46103).
type AicomposeTonesNotModified struct {
}

// AicomposeTonesNotModifiedConstructorID is the TL constructor ID for aicompose.tonesNotModified.
const AicomposeTonesNotModifiedConstructorID uint32 = 0xc1f46103

// ConstructorID returns the TL constructor ID.
func (*AicomposeTonesNotModified) ConstructorID() uint32 {
	return AicomposeTonesNotModifiedConstructorID
}

func (*AicomposeTonesNotModified) isAicomposeTonesClass() {
}

func (value *AicomposeTonesNotModified) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.tonesNotModified", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeTonesNotModified) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.tonesNotModified", "", ErrNilObject)
	}
	size := 0
	return size, nil
}

func (value *AicomposeTonesNotModified) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.tonesNotModified", "", ErrNilObject)
	}
	output.putUint32(AicomposeTonesNotModifiedConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeTonesNotModified) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.tonesNotModified", "", ErrNilObject)
	}
	return output, nil
}

// decodeAicomposeTonesNotModified decodes a TL aicompose.Tones.
func decodeAicomposeTonesNotModified(input *decoder) (*AicomposeTonesNotModified, error) {
	if err := input.reserveAllocation("aicompose.tonesNotModified", decodedAllocationSize(4, 8)); err != nil {
		return nil, err
	}
	value := new(AicomposeTonesNotModified)
	if err := value.decodeBody(input); err != nil {
		return nil, err
	}
	return value, nil
}

func (value *AicomposeTonesNotModified) decodeBody(input *decoder) error {
	if err := input.enter(); err != nil {
		return err
	}
	input.leave()
	return nil
}

// AicomposeGetToneExampleRequest represents TL method aicompose.getToneExample (ID 0xd1b4ab14).
type AicomposeGetToneExampleRequest struct {
	Tone InputAiComposeToneClass
	Num  int32
}

// AicomposeGetToneExampleRequestConstructorID is the TL constructor ID for aicompose.getToneExample.
const AicomposeGetToneExampleRequestConstructorID uint32 = 0xd1b4ab14

// ConstructorID returns the TL constructor ID.
func (*AicomposeGetToneExampleRequest) ConstructorID() uint32 {
	return AicomposeGetToneExampleRequestConstructorID
}

func (*AicomposeGetToneExampleRequest) requestResult(*AiComposeToneExample) {}

func (value *AicomposeGetToneExampleRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.getToneExample", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeGetToneExampleRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.getToneExample", "", ErrNilObject)
	}
	size := 0
	if value.Tone == nil {
		return 0, encodeError("aicompose.getToneExample", "tone", ErrNilObject)
	}
	_fieldSize0, err := value.Tone.encodedSize()
	if err != nil {
		return 0, encodeError("aicompose.getToneExample", "tone", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("aicompose.getToneExample", "tone", err)
	}
	size += 4
	return size, nil
}

func (value *AicomposeGetToneExampleRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.getToneExample", "", ErrNilObject)
	}
	output.putUint32(AicomposeGetToneExampleRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeGetToneExampleRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.getToneExample", "", ErrNilObject)
	}
	if value.Tone == nil {
		return output, encodeError("aicompose.getToneExample", "tone", ErrNilObject)
	}
	_output0, err := value.Tone.encode(output)
	if err != nil {
		return output, encodeError("aicompose.getToneExample", "tone", err)
	}
	output = _output0
	output.putInt32(value.Num)
	return output, nil
}

func (request *AicomposeGetToneExampleRequest) decodeResult(state decoder) (*AiComposeToneExample, decoder, error) {
	var zero *AiComposeToneExample
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result *AiComposeToneExample
	_start0 := input.offset
	_constructor0, err := input.readUint32()
	if err != nil {
		return zero, state, err
	}
	if _constructor0 != 0xf1d628ec {
		err := input.unexpectedConstructor(_start0, "AiComposeToneExample", _constructor0)
		return zero, state, err
	}
	if err := input.reserveAllocation("aicompose.getToneExample.result", decodedAllocationSize(16, 32)); err != nil {
		return zero, state, err
	}
	_field1 := new(AiComposeToneExample)
	if err := _field1.decodeBody(input); err != nil {
		return zero, state, err
	}
	result = _field1
	return result, state, nil
}

// AicomposeDeleteToneRequest represents TL method aicompose.deleteTone (ID 0xdd39316a).
type AicomposeDeleteToneRequest struct {
	Tone InputAiComposeToneClass
}

// AicomposeDeleteToneRequestConstructorID is the TL constructor ID for aicompose.deleteTone.
const AicomposeDeleteToneRequestConstructorID uint32 = 0xdd39316a

// ConstructorID returns the TL constructor ID.
func (*AicomposeDeleteToneRequest) ConstructorID() uint32 {
	return AicomposeDeleteToneRequestConstructorID
}

func (*AicomposeDeleteToneRequest) requestResult(bool) {}

func (value *AicomposeDeleteToneRequest) encodedSize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.deleteTone", "", ErrNilObject)
	}
	body, err := value.encodedBodySize()
	if err != nil {
		return 0, err
	}
	return checkedEncodedSizeAdd(4, body)
}

func (value *AicomposeDeleteToneRequest) encodedBodySize() (int, error) {
	if value == nil {
		return 0, encodeError("aicompose.deleteTone", "", ErrNilObject)
	}
	size := 0
	if value.Tone == nil {
		return 0, encodeError("aicompose.deleteTone", "tone", ErrNilObject)
	}
	_fieldSize0, err := value.Tone.encodedSize()
	if err != nil {
		return 0, encodeError("aicompose.deleteTone", "tone", err)
	}
	size, err = checkedEncodedSizeAdd(size, _fieldSize0)
	if err != nil {
		return 0, encodeError("aicompose.deleteTone", "tone", err)
	}
	return size, nil
}

func (value *AicomposeDeleteToneRequest) encode(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.deleteTone", "", ErrNilObject)
	}
	output.putUint32(AicomposeDeleteToneRequestConstructorID)
	return value.encodeBody(output)
}

func (value *AicomposeDeleteToneRequest) encodeBody(output encoder) (encoder, error) {
	if value == nil {
		return output, encodeError("aicompose.deleteTone", "", ErrNilObject)
	}
	if value.Tone == nil {
		return output, encodeError("aicompose.deleteTone", "tone", ErrNilObject)
	}
	_output0, err := value.Tone.encode(output)
	if err != nil {
		return output, encodeError("aicompose.deleteTone", "tone", err)
	}
	output = _output0
	return output, nil
}

func (request *AicomposeDeleteToneRequest) decodeResult(state decoder) (bool, decoder, error) {
	var zero bool
	if request == nil {
		return zero, state, ErrNilObject
	}
	input := &state
	var result bool
	_field0, err := input.readBool()
	if err != nil {
		return zero, state, err
	}
	result = _field0
	return result, state, nil
}
